### ISSUE TITLE
[Vue Router warn]: No match found for location with path "/null"

### ISSUE THREAD

**Issue by drekembe** [nuxt/framework#5424] opened 2022-06-12 15:54 UTC
### Environment

Nuxt project info:                                                                                            17:45:23

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.5`
- Builder:          `vite`
- User Config:      `strict`, `typeCheck`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/drekembe/nuxt-null-get-warning

### Describe the bug

How to recreate:
* Create a blank project with `npx nuxi init`
* Add an `index.vue` page in `pages`
* Start the dev server and navigate to the root page (i.e. `http://localhost:3000/`)

The problem:
* In the console, you'll see a warning: `[Vue Router warn]: No match found for location with path "/null"`
* In the network inspector, you'll see that a request for `/null` is made, which results in a 404 error

It's not a deal-breaker, but this was literally the first thing I saw when trying to set up a Nuxt 3 project. Hopefully, this will be easy to debug since the reproduction for it is just an empty project with an `index.vue` page.

Great work by the way on Nuxt 3 so far, keep it up! Thanks in advance to anyone who looks at this issue.

**Comment by danielroe** [comment] 2022-06-12 21:27
Hm - how odd! I can't reproduce it - see https://stackblitz.com/github/drekembe/nuxt-null-get-warning. Do you still experience this?

If this goes away after you restart your dev server, then it is likely resolved in https://github.com/nuxt/framework/pull/5002.

**Comment by drekembe** [comment] 2022-06-13 06:41
Thanks for such a fast response. Looks like I jumped the gun a bit -- after further investigation it looks like it was the fault of a chrome extension that was misbehaving. My apologies.

**Closed** 2022-06-13 06:42 UTC
Labels: needs reproduction, pending triage
