### ISSUE TITLE
rc.3 The requested module '/_nuxt/node_modules/@babel/runtime/regenerator/index.js?v=f35a8615' does not provide an export named 'default'

### ISSUE THREAD

**Issue by taoxhsmile** [nuxt/framework#4948] opened 2022-05-12 08:00 UTC
### Environment

Nuxt CLI v3.0.0-rc.3

### Reproduction

[https://codesandbox.io/s/adoring-kapitsa-1qj1ev?file=/pages/index.vue](https://codesandbox.io/s/adoring-kapitsa-1qj1ev?file=/pages/index.vue)

codesandbox Cannot reproduce

### Describe the bug

The requested module '/_nuxt/node_modules/@babel/runtime/regenerator/index.js?v=f35a8615' does not provide an export named 'default'

**Comment by 516310460** [comment] 2022-05-12 08:14
Use.
<img width="368" alt="image" src="https://user-images.githubusercontent.com/17541676/168024227-303fba47-c158-4e62-bc51-5960d6738b40.png">

**Comment by taoxhsmile** [comment] 2022-05-12 08:20
> 采用。 <img alt="图片" width="368" src="https://user-images.githubusercontent.com/17541676/168024227-303fba47-c158-4e62-bc51-5960d6738b40.png">

?

**Comment by taoxhsmile** [comment] 2022-05-12 08:21
![image](https://user-images.githubusercontent.com/17592252/168025569-c0239437-d84a-49c0-b207-077239e38565.png)
the same result

**Comment by taoxhsmile** [comment] 2022-05-12 08:22
> ![image](https://user-images.githubusercontent.com/17592252/168025569-c0239437-d84a-49c0-b207-077239e38565.png) the same result. Can you be more specific

**Comment by danielroe** [comment] 2022-05-12 09:40
I can't reproduce this either locally with your cloned code or in the codesandbox. Perhaps try removing your `node_modules` and reinstalling?

**Comment by taoxhsmile** [comment] 2022-05-12 09:46
> I can't reproduce this either locally with your cloned code or in the codesandbox. Perhaps try removing your `node_modules` and reinstalling?

![image](https://user-images.githubusercontent.com/17592252/168042421-ffc8ace5-8d47-4e43-83ff-0385d7c7b9fd.png)

I used ant design- vue@3.2.3
It relies on @ Babel / Runtime / regenerator
Is a commonjs

**Comment by taoxhsmile** [comment] 2022-05-12 09:54
> reinstalling

you can try run this https://github.com/taoxhsmile/nuxt3-bug-demo

**Comment by danielroe** [comment] 2022-05-12 10:07
This is a common pattern with CJS dependencies and I believe the issue would be resolved by adding it to `vite.optimizeDeps.include` (see [info](https://vitejs.dev/config/#optimizedeps-include)):

```js
import { defineNuxtConfig } from 'nuxt';

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  vite: {
    optimizeDeps: {
      include: ['@babel/runtime/regenerator'],
    },
  }
})
```

**Comment by pi0** [comment] 2022-05-12 10:11
Reopening to see if we can add `@babel/runtime/regenerator` to the defaults.

**Comment by danielroe** [comment] 2022-09-26 11:50
Closing as `@babel/runtime` is not installed by default in new nuxt projects and vite would error if we add it when the dependency can't be resolved. Feel free to reopen @pi0 if you think differently!

**Closed by danielroe** 2022-09-26 11:50 UTC
Labels: needs reproduction, pending triage
