### ISSUE TITLE
[vite:vue] failed to resolve tsconfig.json

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#1098] opened 2021-10-15 18:43 UTC
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3-3.0.0-27237303.6acfdcd`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.0.6`
------------------------------

### Describe the bug

<img width="1137" alt="CleanShot 2021-10-15 at 21 43 02@2x" src="https://user-images.githubusercontent.com/38668796/137537071-b1260b35-0f1e-40ea-ac80-c11a0c2655a2.png">

### Reproduction

~~https://github.com/productfrontenddeveloper/nuxt3-app~~
https://github.com/productdevbook/nuxt3-app

**Comment by danielroe** [comment] 2021-10-16 12:42
duplicate of https://github.com/nuxt/framework/issues/1048

**Closed by danielroe** 2021-10-16 12:42 UTC
Labels: bug, nuxt3
