### ISSUE TITLE
Vue template using this.$nextTick results in "[nuxt] [request error] require is not defined in ES module scope..."

### ISSUE THREAD

**Issue by L422Y** [nuxt/framework#4788] opened 2022-05-04 00:43 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v17.8.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `vue`, `head`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `auth`, `build`, `styleResources`, `css`, `vite`, `bootstrapVue`, `loading`, `loadingIndicator`, `router`, `privateRuntimeConfig`, `publicRuntimeConfig`, `pwa`, `hooks`
- Runtime Modules:  `nuxt-session@1.0.3`, `cookie-universal-nuxt@2.1.5`, `bootstrap-vue/nuxt`, `nuxt-helmet@2.1.1`
- Build Modules:    `@nuxtjs/eslint-module@3.1.0`, `@nuxt-hero-icons/outline/nuxt@1.0.1`

### Reproduction

`yarn run dev` on a project I am attempting to migrate from Nuxt 2

### Describe the bug

Error:
```
[nuxt] [request error] require is not defined in ES module scope, you can use import instead
  at $id_1ccadb5e (./.nuxt/dist/server/server.mjs:14959:22)
```

Offending line in server.mjs:
```
const { nextTick } = require('vue');
```

The Vue template in question uses `this.$nextTick` and if I remove the calls to that, the error goes away.

**Comment by florian-lefebvre** [comment] 2022-05-04 10:44
Maybe you should do the following instead:
```ts
import { nextTick } from "vue";
// some code
nextTick();
```

**Comment by Aareksio** [comment] 2022-05-04 11:01
I failed to reproduce ([StackBlitz](https://stackblitz.com/edit/github-ec9bjb?file=app.vue)), could you provide more details or reproduction?

**Comment by L422Y** [comment] 2022-05-04 13:11
> import { nextTick } from "vue";
// some code
> nextTick();

> Maybe you should do the following instead:
> 
> ```ts
> import { nextTick } from "vue";
> // some code
> nextTick();
> ```

Well, I would, except that the file is being automatically generated, so even if I modify `server.mjs` it is overwritten. 
We are not using use `require` anywhere in the code that is being parsed

**Comment by danielroe** [comment] 2022-05-06 12:18
I can't reproduce with:

```vue
<template>
  <div>
    <button @click="this.$nextTick(() => ({}))">Next tick</button>
  </div>
</template>
```

**Comment by HochinChan** [comment] 2022-06-10 07:43
**I have the same problem.**

`[nuxt] [request error] require is not defined in ES module scope, you can use import instead    
  at $id_c6a85b24 (/D:/workspace/.nuxt/dist/server/server.mjs:64398:22)`

**The server.mjs:64398:22** 

`const { computed } = require('vue');`

**Comment by danielroe** [comment] 2022-06-10 08:13
@HochinChan Would you provide a reproduction?

**Comment by HochinChan** [comment] 2022-06-10 09:37
> @HochinChan Would you provide a reproduction?
Pls kindly visit this website.
https://stackblitz.com/edit/nuxt-starter-uruwag

**Comment by danielroe** [comment] 2022-06-10 09:45
Thanks! It looks like we're auto-importing `computed` from vue in CJS context - cc: @antfu

**Comment by HochinChan** [comment] 2022-06-10 10:43
How do I get it to stop making this error, I don't know why it's making this error.😵

**Comment by antfu** [comment] 2022-06-10 21:34
Fix landed in `unimport@0.2.7`, you may need to update your lockfile to have the latest `unimport` installed

**Closed** 2022-06-10 21:33 UTC
Labels: bug, ❗ p4-important

**Comment by HochinChan** [comment] 2022-06-11 06:39
> Fix landed in `unimport@0.2.7`, you may need to update your lockfile to have the latest `unimport` installed

I would like to ask how to update this dependency package. I tried to change the version number in package-lock.json, but it does not take effect

**Comment by danielroe** [comment] 2022-06-11 06:45
You can run `yarn upgrade unimport` or `npm upgrade unimport`.

**Comment by HochinChan** [comment] 2022-06-11 06:50
> You can run `yarn upgrade unimport` or `npm upgrade unimport`.

It worked!!!!! Thanks!!!!!
