### ISSUE TITLE
Nested Route change causes parent route to re-render

### ISSUE THREAD

**Issue by SergeyMustafin** [nuxt/framework#2500] opened 2021-12-22 03:04 UTC
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.17.6`
- Nuxt Version:     `3.0.0-27335068.804b323`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Vite`
- User Config:      `meta`, `css`, `buildModules`, `modules`, `intlify`, `vite`, `vue`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.6`, `@intlify/nuxt3@0.1.9`
------------------------------

### Reproduction

To reproduce, you need to create multiple child pages and switch between them from the any page or component.

https://codesandbox.io/s/hidden-morning-nqvxj
In this minimal repro you can see the result in console (here's clear nuxt3 latest build without any modules)

### Describe the bug

The parent route is always re-rendered, regardless of the number of nested child routes.
The same result is seen in dynamic nested routes.

### Additional context

Is it possible to keep parent page state?

**Comment by vanling** [comment] 2021-12-24 15:46
Hi @SergeyMustafin  i think i am experiencing the same issue.

Not sure, if exactly the same because i use multiple levels of <NuxtNestedPage/> which makes this issue more obvious because all NuxtNestedPages gets rerendered.

@Atinux Could it be caused by parent component and sub components have the same key ?
<img width="631" alt="Schermafbeelding 2021-12-24 om 16 42 15" src="https://user-images.githubusercontent.com/50699657/147362895-ed782d80-aa07-43f0-a605-a75eeb9d8efe.png">

**Comment by vanling** [comment] 2021-12-24 15:52
@danielroe This might be related/duplicate of https://github.com/nuxt/framework/issues/2309, not sure.

**Comment by danielroe** [comment] 2022-01-14 10:45
closing to follow at #2309.

**Closed by danielroe** 2022-01-14 10:45 UTC
Labels: nuxt3, pending triage
