### ISSUE TITLE
useAsyncData causes hydration issues

### ISSUE THREAD

**Issue by callumgare** [nuxt/framework#4410] opened 2022-04-18 09:46 UTC
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.9.0`
- Nuxt Version:     `3.0.0-27501460.04a72f8`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/callumgare/nuxt-3-hydration-issue-example

I've included 2 routes, `/with-use-async-data` and `/with-set-timeout`, both of which render the same component from the loaded array of items but one loads that array with `useAsyncData` and one loads it using a `ref()` and a `setTimeout()`. Only the `useAsyncData` route results in errors in the console client-side.

### Describe the bug

When using `useAsyncData` with template v-for loops I get hydration errors such as `[Vue warn]: Hydration children mismatch in <p>: server rendered element contains fewer child nodes than client vdom.` and `Hydration completed but contains mismatches.`. 

### Logs

<details>
<summary>Expand to show the full logs from the browser console when loading `/with-use-async-data`</summary>

```
[vite] connecting... [client.ts:16:8](http://localhost:3000/src/client/client.ts)
[vite] connected. [client.ts:53:14](http://localhost:3000/src/client/client.ts)
<Suspense> is an experimental feature and its API will likely change. [runtime-core.esm-bundler.js:1328:47](http://localhost:3000/_nuxt/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js)
Items before loading 
Proxy { <target>: (4) […], <handler>: {…} }
[DisplayItems.vue:17](http://localhost:3000/Users/callumgare/repos/template-key-error-demo/components/DisplayItems.vue)
[Vue warn]: Hydration children mismatch in <p>: server rendered element contains fewer child nodes than client vdom. 
  at <DisplayItems items= 
Array(4) [ 1, 2, 3, 4 ]
 > 
  at <WithUseAsyncData onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/with-use-async-data" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView > 
  at <NuxtPage> 
  at <Anonymous > 
  at <Anonymous > 
  at <Anonymous> 
  at <App key=1 > 
  at <NuxtRoot> [runtime-core.esm-bundler.js:38:16](http://localhost:3000/_nuxt/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js)
[Vue warn]: Hydration children mismatch in <div>: server rendered element contains more child nodes than client vdom. 
  at <DisplayItems items= 
Array(4) [ 1, 2, 3, 4 ]
 > 
  at <WithUseAsyncData onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/with-use-async-data" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView > 
  at <NuxtPage> 
  at <Anonymous > 
  at <Anonymous > 
  at <Anonymous> 
  at <App key=1 > 
  at <NuxtRoot> [runtime-core.esm-bundler.js:38:16](http://localhost:3000/_nuxt/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js)
Hydration completed but contains mismatches. [runtime-core.esm-bundler.js:4072:20](http://localhost:3000/_nuxt/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js)
    NuxtJS 5
        hydrate2
        mount
        mount
        initApp
        <anonymous>
[vite] server connection lost. polling for restart...
```
</details>

**Comment by danielroe** [comment] 2022-04-18 14:45
The issue is that you cannot nest p elements (it's invalid HTML). Hydration of invalid HTML will fail as the browser attempts to correct it by closing the first p tag before the second one.

It doesn't occur in set timeout because the browser doesn't have to parse the HTML.

**Closed by danielroe** 2022-04-18 14:45 UTC
Labels: pending triage

**Comment by callumgare** [comment] 2022-04-18 23:29
Ah interesting. Thank you! 😊
