### ISSUE TITLE
add noscript support

### ISSUE THREAD

**Issue by vis97c** [nuxt/framework#4646] opened 2022-04-27 01:06 UTC
Hi everyone. I'm opening this issue to follow on the implementation of noscript feature for nuxt. It was previously supported on v2 and i think it is a important accesibility feature for many.

Related disscusion: https://github.com/nuxt/framework/discussions/4045

Currently I'm working around the current implementation of useMeta to make it work. I'll be updating this issue as soon as i have a working version of it.

**Comment by vis97c** [comment] 2022-04-27 21:20
# Quick update.

It seems like nuxt is usign https://github.com/vueuse/head to manage metadata and not vue-meta that does support noscript.

Alternatively <Body> tag could be used from any page or the project root to apply a noscript tag.
```vue
<template>
<Html>
    <Head>
      <NoScript class="test-class">Will not work</NoScript>
    </Head>
    <Body>
      <noscript>will work, but not for clientside only projects</noscript>
    </Body>
  </Html>
</template>
```

But i think that defeats the purpose of using default meta data from files such as nuxt config, I'll try to extend the library and update everithing accordingly. Could take a bit since I do this on my spare time.

**Comment by vis97c** [comment] 2022-06-09 20:59
## Quick update 02

Just opened https://github.com/vueuse/head/pull/71 on vue-use-meta so as soon as it is approved things could star moving over here.

**Comment by kalaomer** [comment] 2022-06-22 16:55
I'm looking for this too. I tried to do gtm setup but noscript code could not be added right now.

**Comment by vis97c** [comment] 2022-07-24 20:51
## Quick update 03.

Hi everyone! The pr on @vue-use/head was merged and i just opened a pr for nuxt with the version bump. Hopefully this will be the last update on the case.

**Comment by pi0** [comment] 2022-07-25 10:09
Hi. This feature is just landed in last version of `@vueuse/head` in semver compatible range. In order to use it, use `npx nuxi@latest upgrade` or directly update lockfile. Usage:

```js
<script setup lang="ts">
useHead({
  noscript: [{ children: 'Use js pls' }]
})
</script>
```

**Comment by pi0** [comment] 2022-07-25 10:10
Improvements:

- [ ] documentation
- [ ] a meta component `<NoScript>`
- [ ] typing for `MetaObject` to allow a `noscript` key in nuxt.config
- [ ] typing for `noscript` used with `useHead`

_Originally posted by @danielroe in https://github.com/nuxt/framework/issues/6107#issuecomment-1193795924_

**Closed** 2022-07-26 15:42 UTC
Labels: enhancement

**Comment by sam-the-hai** [comment] 2022-08-22 06:13
https://github.com/nuxt/framework/issues/4646#issuecomment-1193847837

noscript seem to not working when children has a html tag inside it.
```
  app: {
    head: {
      noscript: [
        {
          children: `<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXXXX"
          height="0" width="0" style="display:none;visibility:hidden"></iframe>`,
          body: true
        },
      ],
    },
  },
```

**Comment by danielroe** [comment] 2022-08-22 10:42
It seems to be working for me. That renders:
```html
<!-- -->
<noscript data-meta-body="true"><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXXXX" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
</body>
```

Note https://github.com/vueuse/head/issues/59 if that's relevant.

If you are still encountering this issue, please feel free to open a new issue with a reproduction rather than commenting here.

**Comment by andreasvirkus** [comment] 2022-08-26 11:29
Does not seem to work, please see
https://github.com/nuxt/framework/discussions/5131#discussioncomment-3481251

**Comment by andreasvirkus** [comment] 2022-08-26 11:54
@sam-the-hai this workaround worked for me with a dynamic component
(credit to https://github.com/vuejs/vue/issues/8996#issuecomment-557926912)

```html
<component is="noscript">
  <iframe
    :src="`https://www.googletagmanager.com/ns.html?id=${GOOGLE_TM_ID}`"
    height="0"
    width="0"
    style="display: none; visibility: hidden"
  ></iframe>
</component>
```

**Comment by lowbits** [comment] 2022-08-30 08:35
For me its working with noscript, when I use useHead inside app.vue, not in nuxt config.

```vue
useHead({
  bodyAttrs: {
    class: "bg-white",
  },
 
  noscript: [
    {
      children: `<iframe src="https://www.googletagmanager.com/ns.html?id=${gtmId}"
height="0" width="0" style="display:none;visibility:hidden"></iframe>`, body: true
    }
  ]
})
</script>
```

**Comment by vis97c** [comment] 2022-08-30 21:44
@sam-the-hai @lowbits 

I'm using it like this on my project, works like charm: 

```typescript
export default defineNuxtConfig({
	meta: {
		noscript: [{ children: "This app requires javascript to work" }],
	},
}
```
