### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '...\.nuxt\app.mjs' new project

### ISSUE THREAD

**Issue by rendomnet** [nuxt/framework#5180] opened 2022-05-28 08:37 UTC
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I'm following this guide 
https://v3.nuxtjs.org/getting-started/quick-start

### Describe the bug

and here is error after few seconds after
yarn dev -o

[worker reload] [worker init] Cannot find module '...\.nuxt\app.mjs' imported from ...\.nuxt\dev\index.mjs

**Comment by qin-guan** [comment] 2022-05-29 13:14
Hey @rendomnet, are you able to create a reproduction on https://stackblitz.com or https://codesandbox.io?

**Comment by rendomnet** [comment] 2022-05-30 03:00
I'm running this 4 commands from https://v3.nuxtjs.org/getting-started/quick-start/
npx nuxi init nuxt-app
cd nuxt-app
yarn install
yarn dev -o

Also If I move my project from C:\Users\Username\dev directory to c:\dev directory there is no error.

**Comment by qin-guan** [comment] 2022-05-30 04:58
Unfortunately, I am unable to reproduce the issue. It would be helpful if you can provide an example on CodeSandbox or StackBlitz.

**Comment by rendomnet** [comment] 2022-05-30 05:26
As I said there seems to be a nuxt issue regarding paths.
`https://github.com/nuxt/framework/issues/1226`

dev server is not running from users directory `C:\Users\Username\dev\nuxt-app` but `c:\dev\nuxt-app` gives no error.

**Comment by Vincebe** [comment] 2022-06-01 06:57
> Unfortunately, I am unable to reproduce the issue. It would be helpful if you can provide an example on CodeSandbox or StackBlitz.

Not something you'll be able to reproduce on a linux based env.

Same error on my windows 11 laptop.
The project compiles perfectly fine on my windows 10 desktop.

`import { nitroApp } from '../app.mjs';` in .nuxt\dev\index.mjs, and no app.mjs file in  .nuxt/

**Comment by shba007** [comment] 2022-06-03 13:45
Same problem, I faced the issue by removing the old .nuxt file and rerunning npm dev, apparently it does not occurs when npm build is used

**Comment by mnlj** [comment] 2022-07-25 10:06
The amount of constant repeating neverending Windows issues is really disconcerting, I've spent probably weeks fiddling with this just trying to get it to work, and for a while I managed to do so. Is it just Windows related, is it node, nitropack, nuxt, is it caused using nvm for windows (https://github.com/coreybutler/nvm-windows)? Honestly I don't know, how do I even begin to debug this? How do I even provide a "reproduction code" when it's not even related to anything in my code? Wanna remote to my PC to debug it?

```
 ERROR  [worker reload] [worker init] Cannot find module 'c:\test\.nuxt\app.mjs' imported from c:\test\.nuxt\dev\index.mjs

  at new NodeError (node:internal/errors:372:5)
  at finalizeResolution (node:internal/modules/esm/resolve:437:11)
  at moduleResolve (node:internal/modules/esm/resolve:1009:10)
  at defaultResolve (node:internal/modules/esm/resolve:1218:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
  at link (node:internal/modules/esm/module_job:78:36)
```
I'm currently getting this after updating to rc.6 and reverting to rc.3 and nothing I've thrown at it works.

**Comment by shba007** [comment] 2022-07-25 10:41
Did you changed the folder name at any given time after npx nuxi init??

**Comment by danielroe** [comment] 2022-07-25 10:53
Does it make a difference if you delete your `.nuxt` folder?

**Comment by mnlj** [comment] 2022-07-25 11:02
> Did you changed the folder name at any given time after npx nuxi init??

Probably, most likely, when it's pushed in a git repo used by more people on multiple OS you can't really hope to have the same path as nuxi init after cloning the repo.

> Does it make a difference if you delete your `.nuxt` folder?

Nothing changed, the new .nuxt folder had the same issue. For now I've decided to switch to VS Code and WSL where both rc3 and rc6 work just fine.

---

(Also, I'm getting this with rc6 on windows
```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```
but i think thats issue with the not yet finished nuxt i18n so I'm not reporting it here)

**Comment by danielroe** [comment] 2022-07-25 11:24
@mnlj The most helpful thing would be if you could create a reproduction or share your code.

**Comment by danielroe** [comment] 2022-08-15 13:35
Are you still encountering this issue with RC8?

**Comment by greenn-lab** [comment] 2022-09-14 03:53
If you use to `pnpm` package manager, when have to install with `shamefully-hoist`
```
 ig. `pnpm install --shamefully-hoist`.
```

**Comment by danielroe** [comment] 2022-09-20 12:55
Closing as I cannot replicate this on windows with the latest nuxt + nitro. Please feel free to comment with a reproduction and I'll take a look.

**Closed by danielroe** 2022-09-20 12:55 UTC
Labels: windows, needs reproduction, pending triage
