### ISSUE TITLE
TS(2322) with NuxtWelcome missing lang="ts"

### ISSUE THREAD

**Issue by thepragmaticprogrammer1** [nuxt/framework#5268] opened 2022-06-02 14:24 UTC
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `typescript`, `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`

Version: 1.67.2 (user setup)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000

Volar: 0.35.2

### Reproduction

https://github.com/smartmelonsystems/nuxt3-ssg-example

### Describe the bug

VSCode problem window shows a TS 2322 issue with NuxtWelcome component. It appears to not recognise the component default values.
I'm not sure if this is Nuxt or Volar or VSCode
I created my own version of NuxtWelcome (MyNuxtWelcome) I get the same TS2322 issue.
However, if I add lang="ts" in the <script setup> of MyNuxtWelcome component.  The issue is resolved.

Am I missing something in my environment or should lang="ts" be added to Nuxt 3 NuxtWelcome?

### Additional context

![Nuxt 2322 Issue](https://user-images.githubusercontent.com/92262920/171649080-84d03b78-8e55-4c20-8db1-301acb43142a.jpg)

### Logs

```shell
[{
	"resource": "/c:/YouTubeRepos/nuxt3-ssg-example/nuxt-app/app.vue",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "2322",
	"severity": 8,
	"message": "Type '{}' is not assignable to type 'IntrinsicAttributes & Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never> & Readonly<...>'.\n  Type '{}' is missing the following properties from type 'Readonly<ExtractPropTypes<{ appName: { type: StringConstructor; default: string; }; version: { type: StringConstructor; default: string; }; title: { type: StringConstructor; default: string; }; readDocs: { ...; }; followTwitter: { ...; }; starGitHub: { ...; }; }>>': title, appName, version, readDocs, and 2 more.",
	"source": "ts",
	"startLineNumber": 3,
	"startColumn": 6,
	"endLineNumber": 3,
	"endColumn": 17
}]
```

**Comment by danielroe** [comment] 2022-06-03 11:29
I can't access your reproduction.

**Comment by dsvgl** [comment] 2022-06-03 22:09
Same here. Freshly created nuxt 3 app via `npx nuxi init myapp`.

**Comment by thepragmaticprogrammer1** [comment] 2022-06-04 13:54
> I can't access your reproduction.

@danielroe - apologies, repo is now public

**Comment by fosterdouglas** [comment] 2022-06-08 00:19
adding a +1 here if it's relevant, simple to repro

<img width="834" alt="Screen Shot 2022-06-07 at 17 16 49" src="https://user-images.githubusercontent.com/7971443/172505095-bec612fc-fe11-47ef-b345-83b7b59e50e5.png">

**Comment by danielroe** [comment] 2022-06-08 10:19
This looks like a Volar issue to me. The Vue file is generated looking like this:

```js
<script setup>
const props = defineProps({
  appName: {
    type: String,
    default: "Nuxt"
  },
})
</script>
```

I think this shouldn't complain about a required `app-name` prop as a default value is provided. (Even adding `required: false` doesn't seem to address the issue.)

Would you be able to raise an issue upstream on https://github.com/johnsoncodehk/volar

cc: @johnsoncodehk

**Comment by danielroe** [comment] 2022-06-12 21:24
Now resolved in volar! ❤️

**Closed by danielroe** 2022-06-12 21:24 UTC
Labels: upstream, upstream-bug
