### ISSUE TITLE
Cannot read properties of undefined (reading 'modules')

### ISSUE THREAD

**Issue by gurpindersinghgill** [nuxt/framework#7220] opened 2022-09-04 14:36 UTC
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.0`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. npx nuxi init nuxt-app
2. cd nuxt-app
3. npm install
4. npm run dev

Error is thrown only when running on macbook...

### Describe the bug

Unable to run dev after fresh install on Macbook. 
However, doing npm run build, and npm run preview works without issue.
Testing in stackblitz shows no issues however. 

### Additional context

Had no issues yesterday when doing fresh install of rc.9

### Logs

```shell
gurpinder@Gurpinders-MacBook-Pro bug % npx nuxi init bug-test
Need to install the following packages:
  nuxi
Ok to proceed? (y) 
Nuxi 3.0.0-rc.9                                                                                         22:28:53
ℹ cloned nuxt/starter#v3 to /Users/gurpinder/Desktop/bug/bug-test                                       22:28:54
                                                                                                        22:28:54
Nuxi 3.0.0-rc.9                                                                                                              22:29:51
Nuxt 3.0.0-rc.9 with Nitro 0.5.0                                                                                             22:29:51
                                                                                                                             22:29:54
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.0.106:3000/

ℹ Vite server warmed up in 171ms                                                                                             22:29:55
✔ Nitro built in 185 ms                                                                                                nitro 22:29:55
ℹ Vite client warmed up in 701ms                                                                                             22:29:55
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')
  at _sfc_main.setup (./node_modules/nuxt/dist/app/components/nuxt-root.vue:67:16)  
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7107:29)  
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7062:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)  
  at renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:446:26)  
  at Object.renderToString$1 [as renderToString] (./.nuxt/dev/index.mjs:472:24)  
  at Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async ./.nuxt/dev/index.mjs:521:21
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
```

**Comment by LimonJuice322** [comment] 2022-09-04 21:26
I have the same problem. With 3.0.0-rc.8 it works fine

**Comment by rustre-undefined** [comment] 2022-09-06 06:37
Same issue here.

**Comment by rustre-undefined** [comment] 2022-09-06 06:47
https://github.com/sidestream-tech/sidebase/issues/16#issuecomment-1236960305

**Comment by gurpindersinghgill** [comment] 2022-09-07 02:34
After reinstalling. Xcode, home brew and node , it worked . Don't know where the issue origins from. I had no issues running previous rc version before reinstalling . It only caused issues on rc.9

**Comment by dan-hammond** [comment] 2022-09-07 10:27
The same thing is happening for me and my colleague on Windows. I can't recreate it in a blank project, but our actual project has this issue.

I've tried:
- deleting package-lock.json and node_modules and reinstalling everything
- clearing the nuxt caches
- commenting out my module + plugin code
- running it both natively on my machine and in a Linux docker container

When the project is built for production it runs fine.

I appreciate I'm not offering much to go on, but I'm a bit stumped as to what else to try.

**Comment by danielroe** [comment] 2022-09-07 20:50
The error message here is referring to `useSSRContext().modules` It seems that `useSSRContext` is returning `null` for some reason, possibly because of a mismatch of vue versions within your `node_modules` folder. Check your dependency tree/lockfile to ensure you have only one version of `vue` installed.

**Comment by danielroe** [comment] 2022-09-08 11:26
If it is a vue dependency issue, you could either add that package to your `build.transpile` or use yarn resolutions or npm overrides to force vue version.

**Comment by Melbourneandrew** [comment] 2022-09-09 00:01
This worked for me. Downgrading to 3.0.0-rc.8
https://github.com/sidestream-tech/sidebase/issues/16#issuecomment-1236960305

**Comment by BracketJohn** [comment] 2022-09-09 08:09
As this is also happening in https://github.com/sidestream-tech/sidebase, I've checked for different vue-versions there, and it looks like they are all the same:
```sh
❯ npm list --depth=10 | grep ' vue@'
│ └── vue@3.2.38 deduped
│ │ └── vue@3.2.38 deduped
│ └── vue@3.2.38 deduped
│ └── vue@3.2.38 deduped
│ │ └── vue@3.2.38 deduped
│ │ └── vue@3.2.38 deduped
│ ├── vue@3.2.38 deduped
│ │ │ └── vue@3.2.38 deduped
│ │ └── vue@3.2.38 deduped
│ │ └── vue@3.2.38 deduped
│ │ └── vue@3.2.38 deduped
│ └── vue@3.2.38 deduped
│ └── vue@3.2.38 deduped
├─┬ vue@3.2.38
│ │ └── vue@3.2.38 deduped
```

**Comment by craigharman** [comment] 2022-09-14 11:53
I'm getting this issue also.

Strangely though, I created a new install of Nuxt 3rc9 and added my modules one by one to find the one causing the issue and they all worked. Matched the dependencies with the original project experiencing the problem and still get the 500 error.

**Comment by a1xon** [comment] 2022-09-14 20:40
clean install of rc.9 and rc.10 fails for Ubuntu 22.04.
**does not fail** on windows on same machine.
tried cleaning caches, tried npm, yarn and pnpm.
vue versions are all the same.

**Comment by productdevbook** [comment] 2022-09-15 12:01
Check the vue versions in your lock file. If you see two or more different versions like vue@3.2.39 vue@3.2.37, make the same vue versions in your project.

Get all your vue versions to the latest version.

This is not a problem on the nuxt side.

**Comment by manniL** [comment] 2022-09-15 12:19
@productdevbook The problem is for some people, even the starter project fails where Vue versions should be fine.

**Comment by productdevbook** [comment] 2022-09-15 12:37
> clean install of rc.9 and rc.10 fails for Ubuntu 22.04. **does not fail** on windows on same machine. tried cleaning caches, tried npm, yarn and pnpm. vue versions are all the same.

@a1xon How many different vue versions do you see in the lock file?

**Comment by brightjune** [comment] 2022-09-15 14:34
Same error on MacBook Pro , Ubuntu 18.04.6. But it's ok on windows 11.

Node Version: v16.17.0
Nuxt Version: 3.0.0-rc.9 / 3.0.0-rc.10

**Comment by productdevbook** [comment] 2022-09-15 14:58
![image](https://user-images.githubusercontent.com/38668796/190437671-540546a1-1625-4d0b-8f05-257da567c4a4.png)


Take a look at vue and its subversions.

**Comment by a1xon** [comment] 2022-09-16 05:32
> > Same error on MacBook Pro , Ubuntu 18.04.6. But it's ok on windows 11.
> > Node Version: v16.17.0 Nuxt Version: 3.0.0-rc.9 / 3.0.0-rc.10
> 
> @brightjune How many different vue versions do you see in the lock file?
> 
> search please `@vue/runtime-core/`

One. "version": "3.2.39". It's a fresh install.

**Comment by productdevbook** [comment] 2022-09-16 05:36
> > > Same error on MacBook Pro , Ubuntu 18.04.6. But it's ok on windows 11.
> > > Node Version: v16.17.0 Nuxt Version: 3.0.0-rc.9 / 3.0.0-rc.10
> > 
> > 
> > @brightjune How many different vue versions do you see in the lock file?
> > search please `@vue/runtime-core/`
> 
> One. "version": "3.2.39". It's a fresh install.

very interesting, can you send me a lock file so I can review it ? Thank you

**Comment by niko577** [comment] 2022-09-16 08:43
I have the same problem, I install a purely new Nuxt RC10 or RC9 project and get this error.
Node 16.14.2 and Windows 11 21H2 22000.978

![image](https://user-images.githubusercontent.com/54767664/190592392-01aac8d1-1b31-4797-be6d-7ed82342f8ee.png)

Also, I only have one `@vue/runtime-core` version in package-lock.json is `3.2.39`

![image](https://user-images.githubusercontent.com/54767664/190593890-23dbf92d-63ac-4256-94b1-81609c693595.png)

Here is my package-lock.json: https://www.transfernow.net/dl/20220916abOwN9Oc

**Comment by brightjune** [comment] 2022-09-16 15:02
> > > > Same error on MacBook Pro , Ubuntu 18.04.6. But it's ok on windows 11.
> > > > Node Version: v16.17.0 Nuxt Version: 3.0.0-rc.9 / 3.0.0-rc.10
> > > 
> > > 
> > > @brightjune How many different vue versions do you see in the lock file?
> > > search please `@vue/runtime-core/`
> > 
> > 
> > One. "version": "3.2.39". It's a fresh install.
> 
> very interesting, can you send me a lock file so I can review it ? Thank you

@vue/runtime-core  3.2.39

Here is the yarn lock file, Thank you!  


[yarn.lock.txt](https://github.com/nuxt/framework/files/9585178/yarn.lock.txt)

**Comment by pi0** [comment] 2022-09-16 20:55
Moving to https://github.com/nuxt/framework/issues/7609

**Closed by pi0** 2022-09-16 20:55 UTC
Labels: bug, vite
