### ISSUE TITLE
Error occurred when using "ssr:false" 

### ISSUE THREAD

**Issue by iqraaswad** [nuxt/framework#1763] opened 2021-11-07 02:06 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.16.0-27269293.ab1c6cb4`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Webpack`
- User Config:      `target`, `ssr`, `router`, `loadingIndicator`, `loading`, `publicRuntimeConfig`, `pwa`, `googleAnalytics`, `head`, `css`, `plugins`, `components`, `buildModules`, `tailwindcss`, `lazySizes`, `modules`, `axios`, `build`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`
- Build Modules:    `@nuxtjs/tailwindcss@4.2.1`, `nuxt-lazysizes@1.4.0`, `@nuxtjs/google-analytics@2.4.0`, `@nuxtjs/pwa@3.3.5`, `@nuxt/bridge@3.0.0-27268729.5b8e10f`

### Describe the bug

error when trying to run "**npm run generate**" using config  ssr: false and target:static.. 

note: if i didnt use ssr:false, everything is works.. BUT loadingIndicator not show up

### Reproduction

i got this error when adding **ssr: false** to nuxt.config file

example :
export default defineNuxtConfig({
  ssr: false,
  target: "static"
});

### Logs

```shell
> nuxt-starter-bridge-codesandbox@1.0.0 generate /sandbox
> nuxt generate

✔ Skipping webpack build as no changes detected                                                              02:01:33
ℹ Nitro preset is server                                                                                     02:01:33
ℹ Cleaning up .output                                                                                        02:01:33
ℹ Generating output directory: public/                                                                       02:01:33
start Building server...                                                                                     02:01:33

 ERROR  Rollup error: Could not load /sandbox/node_modules/.cache/nuxt/dist/server/server.mjs (imported by node_modules/@nuxt/nitro/dist/runtime/app/render.mjs): ENOENT: no such file or directory, open '/sandbox/node_modules/.cache/nuxt/dist/server/server.mjs'


 FATAL  Could not load /sandbox/node_modules/.cache/nuxt/dist/server/server.mjs (imported by node_modules/@nuxt/nitro/dist/runtime/app/render.mjs): ENOENT: no such file or directory, open '/sandbox/node_modules/.cache/nuxt/dist/server/server.mjs'




   ╭────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                    │
   │   ✖ Nuxt Fatal Error                                                                               │
   │                                                                                                    │
   │   Error: Could not load /sandbox/node_modules/.cache/nuxt/dist/server/server.mjs (imported by      │
   │   node_modules/@nuxt/nitro/dist/runtime/app/render.mjs): ENOENT: no such file or directory, open   │
   │   '/sandbox/node_modules/.cache/nuxt/dist/server/server.mjs'                                       │
   │                                                                                                    │
   ╰────────────────────────────────────────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxt-starter-bridge-codesandbox@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuxt-starter-bridge-codesandbox@1.0.0 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sandbox/.npm/_logs/2021-11-07T02_01_34_726Z-debug.log
```

**Comment by Bearfinn** [comment] 2021-11-07 03:46
Duplicate of #886 

I hope they will fix this soon too :(

**Closed** 2021-11-07 09:13 UTC
Labels: bug, bridge
