### ISSUE TITLE
[Vue Router warn]: No match found for location with path "/_nuxt/__vite_ping"

### ISSUE THREAD

**Issue by chaule97** [nuxt/framework#4657] opened 2022-04-27 08:55 UTC
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `latest`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Can't run after build project

### Describe the bug

After I run `npm run build` and `npm run start` then I have a trouble
```
> start
> node .output/server/index.mjs

Listening on http://0.0.0.0:3000/
[Vue Router warn]: No match found for location with path "/_nuxt/__vite_ping"
[Vue Router warn]: No match found for location with path "/_nuxt/__vite_ping"
[Vue Router warn]: No match found for location with path "/_nuxt/__vite_ping"
```

I don't know reason, it's my package.json

```
{
  "private": true,
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "generate": "nuxi generate",
    "start": "node .output/server/index.mjs"
  },
  "devDependencies": {
    "@intlify/nuxt3": "^0.1.10",
    "@nuxt/types": "^2.13.2",
    "@nuxt/typescript-build": "^2.1.0",
    "@types/jquery": "^3.5.14",
    "@vue/cli-plugin-typescript": "~5.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^10.0.0",
    "eslint": "^8.14.0",
    "eslint-plugin-vue": "^8.7.1",
    "nuxt3": "latest",
    "sass": "^1.50.0",
    "sass-loader": "^12.6.0"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/free-brands-svg-icons": "^6.1.1",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@fortawesome/vue-fontawesome": "^3.0.0-5",
    "@pinia/nuxt": "^0.1.8",
    "@popperjs/core": "^2.11.5",
    "@vueuse/core": "^8.3.1",
    "bootstrap": "^5.1.3",
    "express": "^4.18.0",
    "gsap": "^3.10.4",
    "jquery": "^3.6.0",
    "nuxt-start": "^2.15.8",
    "pinia": "^2.0.13",
    "vue": "3.2.33",
    "vue-router": "^4.0.14"
  }
}

```

**Comment by danielroe** [comment] 2022-04-27 10:07
That's your browser still requesting a URL which is accessible only in development. Try closing all tabs in the browser first.

**Closed by danielroe** 2022-04-27 10:07 UTC
Labels: pending triage

**Comment by abarke** [comment] 2022-07-27 16:28
I'm also getting the following in dev mode (no production) and it seems to be slowing down the serverHandler

[Vue Router warn]: No match found for location with path "/sw.js"

Seems the browser is sending these requests... any way to mute this warning as it slows the response time down and clutters the logs.

**Comment by abarke** [comment] 2022-07-27 16:34
Seems also that the server middleware is running twice in dev mode... why would that be?

√ Vite server built in 1542ms                                                                                                                                                                                                 18:32:43
State: connecting
State: ready
Middleware Connected 🔌
√ Nitro built in 1459 ms                                                                                                                                                                                                nitro 18:32:44
State: connecting
State: ready
Middleware Connected 🔌

**Comment by danielroe** [comment] 2022-08-18 19:56
This should not occur on Nuxt rc8. If it does, please open a new issue with a reproduction.

Note also that it was a purely visual issue and not an issue with the production server.

**Comment by jamiecarter7** [comment] 2022-08-18 21:07
It was not occuring on rc4, but having updated to rc8 it shows as above

**Comment by danielroe** [comment] 2022-08-18 21:29
Oops, sorry - misread your comment. It's just a tab in your browser still with a Vite 2 client that's desperately trying to phone home. Just restart your browser or close the tab that's doing it. It's not a bug.

**Comment by Rentalmed** [comment] 2022-08-19 19:08
try remove vue chrome extension

**Comment by Arkadipta1998** [comment] 2022-08-24 15:17
@danielroe Same issue for me but with bootstrap. On the server side it says - 

[Vue Router warn]: No match found for location with path "/bootstrap.css.map"

And on client side - 

DevTools failed to load source map: Could not load content for http://localhost:3002/bootstrap.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

My package.json - 
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "node-sass": "^7.0.1",
    "nuxt": "3.0.0-rc.8",
    "sass-loader": "^12.6.0"
  },
  "dependencies": {
    "@fontsource/open-sans": "^4.5.5",
    "@popperjs/core": "^2.11.6",
    "@types/chart.js": "^2.9.37",
    "bootstrap": "git://github.com/xvaara/bootstrap.git",
    "bootstrap-vue-3": "^0.2.10",
    "chart.js": "^2.7.1",
    "sass": "^1.54.5",
    "vue-chartjs": "^3.5.1"
  }
}

**Comment by danielroe** [comment] 2022-08-24 15:50
@Arkadipta1998 I don't believe that is the same issue. Would you open a new one with a reproduction?

**Comment by Arkadipta1998** [comment] 2022-08-25 07:56
sure

**Comment by jamiecarter7** [comment] 2022-08-25 08:18
> Oops, sorry - misread your comment. It's just a tab in your browser still with a Vite 2 client that's desperately trying to phone home. Just restart your browser or close the tab that's doing it. It's not a bug.

This did indeed fix my error. I had a rogue tan left open after updating from rc4 to rc8. After closing this the error went away

**Comment by elzodxon** [comment] 2022-10-11 06:56
![image](https://user-images.githubusercontent.com/52325239/195017500-79634c19-3f27-4675-84f5-879c2d18a015.png)
I am also facing this issue. Nuxt RC11

**Comment by jamiecarter7** [comment] 2022-10-11 08:43
Close all your open localhost browser tabs. One is trying to connect to the nuxt server but is unable.

**Comment by Chuiantw1212** [comment] 2022-10-29 00:28
Same issue.
`"devDependencies": {
    "nuxt": "^3.0.0-rc.12"
  },`

> Close all your open localhost browser tabs. One is trying to connect to the nuxt server but is unable.

Not gonna happen, the only one tab that is trying to connect to the nuxt server is the one i'm developing.

**Comment by bitkarrot** [comment] 2022-11-01 00:34
> Same issue. `"devDependencies": { "nuxt": "^3.0.0-rc.12" },`

Same issue also happens on Firefox for same version of nuxt above.  Error appears to go away when using Chrome

`[Vue Router warn]: No match found for location with path "/sw.js"`

**Comment by danielroe** [comment] 2022-11-01 08:03
@bitkarrot You can uninstall the service worker registered to that host. This is not a Nuxt bug, just your browser requesting a resource that your Nuxt server is not serving.
