### ISSUE TITLE
Composables autoimports typescript warning - not found

### ISSUE THREAD

**Issue by mihail727** [nuxt/framework#3771] opened 2022-03-18 10:31 UTC
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.7.1`
- Nuxt Version:     `3.0.0-27459267.f69126e`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `privateRuntimeConfig`, `app`, `nitro`, `srcDir`, `build`, `buildModules`, `modern`, `tailwindcss`, `meta`, `modules`, `colorMode`
- Runtime Modules:  `@nuxtjs/color-mode@3.0.2`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.2`
------------------------------

### Reproduction

no need

### Describe the bug

typescript gives a warning when I try to use composables in any other folder, for example:
i have `@/composables/useTheme.ts`
and inside `@/composables/useRequest.ts` typescript doesn't know about `useTheme.ts`
also for example inside `@/controllers/itemController.ts` typescript doesn't know about `useTheme.ts` or `useRequest.ts`
but all works....

**Comment by danielroe** [comment] 2022-03-18 12:47
Do you have a reproduction? This kind of thing should be resolved by using the default `tsconfig.json` shipped with nuxt/starter: https://github.com/nuxt/starter/blob/v3/tsconfig.json.

**Comment by mihail727** [comment] 2022-03-18 14:57
> Do you have a reproduction? This kind of thing should be resolved by using the default `tsconfig.json` shipped with nuxt/starter: https://github.com/nuxt/starter/blob/v3/tsconfig.json.

https://stackblitz.com/edit/github-zvowq4-cdsns3?file=controllers/example-controller.ts

**Comment by danielroe** [comment] 2022-03-18 21:55
It works for me. Likely an issue with your IDE. You can follow https://github.com/nuxt/framework/issues/2320 if you are using Webstorm.

<img width="1680" alt="CleanShot 2022-03-18 at 21 53 20@2x" src="https://user-images.githubusercontent.com/28706372/159088885-a261cfdb-f119-497f-817d-2e73c4c34c03.png">

**Closed by danielroe** 2022-03-18 21:55 UTC
Labels: nuxt3, needs reproduction, pending triage

**Comment by mihail727** [comment] 2022-03-18 22:07
@danielroe what plugins do you use for nuxt in vscode
