### ISSUE TITLE
Nuxt 3 prefetch all assets from every pages and every layouts.

### ISSUE THREAD

**Issue by kstraszewski** [nuxt/framework#4475] opened 2022-04-20 19:32 UTC
### Environment

Nuxt CLI v3.0.0-rc.0
Nuxt project info:

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.0`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/kstraszewski/nuxt3-playground/tree/prefetching-all-assets

Also we have qa version of our project here:
https://b2c.qa2.lendi.pl/design

### Describe the bug

Nuxt after build prefetch all the assets like CSS, fonts, media, imgs from all the pages and all the layouts. As you can see in the repo example you have `/pageA` which implement `layout-a`, with some video in the pageA.vue. Also, you have `/pageB` which implements `layout-b` which loads popular [@mdi/font](https://www.npmjs.com/package/@mdi/font). 

The problem I have is it doesn't matter on which page you go nuxt always loads all the assets. When you go to `/pageA` you will see the mdi fonts from pageB and layoutB also are prefetching by the nuxt:

PageA:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10195995/164307955-94b3b43f-61a0-424f-a60c-b2041eb642bf.png">

PageB:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10195995/164308103-7a653d1b-6ba9-432a-88cd-d19e07db14f4.png">

Both pages Loads a lot.

My guess is that vite builder prefetch every URL that he find in CSS or template.

### Additional context

It makes nuxt unusable in production mode because It hurts LCP very badly:

As you can see on the example below we have huge LCP (I've made some tricks witch mdi/fonts, but this is very ugly solution) with fully loaded mdi/fonts I've received 27 sec of LCP.

https://pagespeed.web.dev/report?url=https%3A%2F%2Fb2c.qa2.lendi.pl%2Fdesign

**Comment by Foddy** [comment] 2022-04-21 07:08
I am facing the same issue. Also not sure what causes this… :S

**Comment by kkauper** [comment] 2022-04-22 08:50
I can also report the same issue. Would be nice to have a solution for production soon!

**Comment by tomekhub** [comment] 2022-04-22 10:56
I'm facing the same issue :/

**Comment by AleksanderWojtkowski** [comment] 2022-04-22 11:13
Same here ...

**Comment by engvie** [comment] 2022-05-12 07:13
I have a reproduce here:

https://stackblitz.com/edit/github-krh2ru?file=layouts%2Fadmin-layout.vue

I don't really understand why this is a minor bug when it's almost impossible to use the layouts and components are sharing styles.

**Comment by danielroe** [comment] 2022-05-12 11:58
@engvie I would advise against using global styles in any case, particularly ones targeted at elements like `html` and `body`. Even when this issue is resolved, you will continue to experience problems with CSS specificity and styles conflicting with each other. Instead, you should be using scoped styles, deliberate global class names, or CSS modules.

**Comment by engvie** [comment] 2022-05-12 12:04
@danielroe I agree they should be scoped.

Maybe there is a better solution for what I am trying to do.
In my case I want to separate my styles for the administration and the "frontend". 

In my admin layout I want to import `admin.scss`. In my frontend layout I want to import `app.scss`.

**Comment by kstraszewski** [comment] 2022-05-12 12:25
I think this is not the same problem @engvie. My point is that app after building and deploying prefetch for example all the images from all the pages and all the layouts. So when I deploy my Landing Page with 0 images it prefetches all the images from the rest of the pages. And it critically lengthens the LCP metric. But I agree it is not minor because it makes deploying an app with lots of pages and lots of images pointless :) I've got like 20 sec of LCP on my page when the other metrics are great.

Finally we workaround it by temporarily removing videos on the page and we are waiting for the fix to come.

**Comment by engvie** [comment] 2022-05-13 07:31
@kstraszewski
Maybe it's not the same issue or maybe a part of it.

I have 2 layout files:

- Default.vue <-- import '~/assets/scss/app.scss'
- AdminLayout.vue <-- import '~/assets/scss/admin.scss'

Both styles are included at both layouts. The admin style are destroying the default layout style.

I don't know if there is another way to separate the styles? I think this is an issue?

**Comment by kstraszewski** [comment] 2022-05-13 08:58
Ok so I think this is part of this issue. It would be great to have layout css scoped to all the pages that are child of that layout, but I didn't test adding `scoped` to layout css. 

This style part of that bug is not bothering me much, coz css doesn't weight lots of kb, but imgs and videos are.

**Comment by juliendargelos** [comment] 2022-05-28 10:48
Has someone already identified what causes this problem ?

**Comment by dungonfq** [comment] 2022-06-03 03:17
We're facing the same issue https://github.com/nuxt/framework/issues/5260. On production, it mets our server's rate limit so some last assets couldn't be loaded (403 Forbidden)

**Comment by leosin** [comment] 2022-06-09 02:22
![code](https://user-images.githubusercontent.com/3676670/172750299-9e48382b-6d4a-4d59-8f5e-191ddc6c5dd4.png)

so,should i put the fonts in public directory?

**Comment by Renhor** [comment] 2022-06-10 09:27
@danielroe the idea of writing styles in scoped / css modules is great. However, the problem affects all the Assets, which makes it problematic to deploy large applications. For example, the size of downloaded assets on one of my pages in Nuxt2 is ~700kb, when in Nuxt Bridge it reaches ~3mb on the same page.

P.S. The bug is also reproduced in Nuxt Bridge + webpack.

**Comment by kstraszewski** [comment] 2022-06-19 12:27
@danielroe is there any workaround for this bug? I'm migrating my projects to Nuxt 3. Size of every pages are great, we are getting 2x smaller bundler compare with nuxt2. But this bug is killing FCP and LCP on the larger project.

I found workaround for images, you can put images to public and then Nuxt doesn't loads them at all, but I can't found workaround for rest of the pages (js + CSS) and unfortunately nuxt loads all of them. 

Using new Performance Insight devtool tool for chrome it shows that when I go to PageA (for example: [https://b2c.qa2.lendi.pl/](https://b2c.qa2.lendi.pl/) for debug) to FCP is loaded after nuxt prefetch all of js and CSS from the other pages (for example, prefetch js and CSS from this page https://b2c.qa2.lendi.pl/kredyty-hipoteczne which is under development, but unfortunately burdens rest of the production pages :/ )

For my opinion (correct me if I'm wrong) Nuxt3 lacks Smart prefetching from Nuxt2 is this feature planned for stable release or rather its matter of 3.1 version?

**Comment by danielroe** [comment] 2022-06-22 08:39
Thanks for the helpful summary @mmis1000.

There is a PR open that does not prefetch prefetches of dynamic dependencies: https://github.com/nuxt-contrib/vue-bundle-renderer/pull/30.

You are also right that the manifest is incorrect; this seems to be an issue with vite or the vite config within nuxt that we'll need to resolve as well.

**Comment by mmis1000** [comment] 2022-06-22 09:25
> Thanks for the helpful summary @mmis1000.
> 
> There is a PR open that does not prefetch prefetches of dynamic dependencies: [nuxt-contrib/vue-bundle-renderer#30](https://github.com/nuxt-contrib/vue-bundle-renderer/pull/30).
> 
> You are also right that the manifest is incorrect; this seems to be an issue with vite or the vite config within nuxt that we'll need to resolve as well.


https://github.com/vitejs/vite/blob/0cbb33bade1b10c1503f47f8f8ed6e3b39818066/packages/plugin-vue/src/main.ts#L255-L261

I guess it could be this?

1. @vite-js/plugin-vue decides to inline template to entrypoint to reduce request (they are small anyway)
2. image is in the template
3. image is in the entrypoint (oh no)
4. image is in the manifest of entrypoint <- we are here

**Comment by mmis1000** [comment] 2022-06-22 12:01
> Thanks for the helpful summary @mmis1000.
> 
> There is a PR open that does not prefetch prefetches of dynamic dependencies: [nuxt-contrib/vue-bundle-renderer#30](https://github.com/nuxt-contrib/vue-bundle-renderer/pull/30).
> 
> You are also right that the manifest is incorrect; this seems to be an issue with vite or the vite config within nuxt that we'll need to resolve as well.

After a bot of inspection, the image module are actually bundled alongside the entry point. So the manifest is technically correct. 

So the actual question is: 
  Why are the asset modules bundled with entrypoint?

**Comment by mmis1000** [comment] 2022-06-23 01:36
@danielroe 

I think I located the reason that cause urls to be bundled into entry chunk. It's caused by `nuxt:dynamic-base-path`.
The rewritten asset chunk emitted by that plugin has direct dependency against entry chunk. And cause vite to decide to merge assets chunk into it instead.

Insert a return under this line https://github.com/nuxt/framework/blob/e38de4af4dd98705a226b551fa9d6729d7b1a130/packages/vite/src/plugins/dynamic-base.ts#L69 makes nuxt generate proper manifest instead of a broken one.

**Comment by mmis1000** [comment] 2022-06-24 08:25
Made a patch set to experiment idea above, and it do work _(on my machine)_.
The built server output prefetch with exactly what is used now.

https://gist.github.com/mmis1000/3a5882636a340df8e67b84099a9364ad

Paste here for who interested.

**Comment by kstraszewski** [comment] 2022-06-24 09:27
> 

Ok I think it works after I locally patched node_modules and running `npm run build`. App doesn't loads additional mjs and CSS files, It saves me +-100kbs. But it still doesn't do huge change in LCP and FCP for me :/ 

Without patch:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10195995/175506609-6bd28738-31e1-4dd7-a23c-8e200a9db951.png">


With patch:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10195995/175506667-4ba32423-c64c-4b4d-bb0c-e73cd0bffb8b.png">

**Comment by Aleksandr-om** [comment] 2022-07-04 13:38
I see that this problem has been known for several months. 
I have a few questions:
* Is there any solution to make preloading work properly? It is advisable not to disable it, as @mmis1000 suggested.
* Is this issue planned to be resolved in the coming months?

**Comment by kosmeln** [comment] 2022-07-25 19:27
We can't wait to see this fixed sooner! Fingers crossed!

**Closed** 2022-08-07 09:52 UTC
Labels: bug, 🔨 p3-minor-bug

**Comment by HochinChan** [comment] 2022-08-18 09:26
Has the problem been solved? I had the same problem

**Comment by kstraszewski** [comment] 2022-08-18 09:37
Yea I still has this issue also, but it will be allowed in the future:
https://github.com/nuxt/framework/pull/6210#issuecomment-1207823041
