### ISSUE TITLE
externalVue : does not send vue/server-renderer/index.js to .output

### ISSUE THREAD

**Issue by huang-julien** [nuxt/framework#7259] opened 2022-09-05 20:32 UTC
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-rc.9`
- Package Manager:  `yarn@3.2.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/nuxt/framework/pull/4762 https://github.com/nuxt/framework/pull/4762/commits/45eac5f165b4c0e3b2dd3a766d1152d4ea6de370

### Describe the bug

Hi 👋 this is a VERY strange issue that happens when having externalVue set to `true`. Vue use `require()` to require `vue/server-renderer` but the index.js file is missing in `.output\server\node_modules\vue\server-renderer` , the mjs version is present .
 
![image](https://user-images.githubusercontent.com/63512348/188510046-c8626fc8-01f9-42e4-b74d-fbb05bef0fb9.png)

However, nuxt does not crash and still manage to render the page with the dynamic template (when it should crash since it cannot import `vue/server-renderer` ) as if it successfully imported `vue/server-renderer`. There's even a log in console due to https://github.com/unjs/nitro/blob/2a05d1e414deb6afbb8d11f376d5cd1403fae886/src/runtime/entries/node-server.ts#L30 (the if statement is duplicated ?) --> `[nitro] [dev] [unhandledRejection] Error: Cannot find module 'D:\GIT\nuxt-3\playground\.output\server\node_modules\vue\server-renderer\index.js'`

### Additional context

Thank you for this amazing framework ❤️

**Comment by danielroe** [comment] 2022-09-06 09:12
Would you provide a minimal reproduction? 🙏 It doesn't seem to reproduce out-of-the-box.

**Comment by huang-julien** [comment] 2022-09-06 11:00
https://github.com/huang-julien/nuxt-3/tree/issue-nuxt-externalVue-server-renderer

run yarn dev:build  and start the server
then go to localhost:3000
it will work since externalVue is disabled

Set experimental.externalVue to true, build  and start the server
then go to localhost:3000
it won't work

Also in the example with experimental.externalVue set to true, nuxt crash due to the missing require of `D:\GIT\nuxt-3\playground\.output\server\node_modules\vue\server-renderer\index.js`

**Comment by danielroe** [comment] 2022-09-06 11:08
`experimental.externalVue` is true by default now. I mean, can you reproduce this issue outside of the PR? (Because if not then it is more likely an issue to be resolved in the PR rather than tracked separately.)

**Comment by huang-julien** [comment] 2022-09-06 11:26
https://stackblitz.com/edit/nuxt-starter-ejmipr?file=app.vue,nuxt.config.ts
does this count as outside of the PR ?

**Comment by danielroe** [comment] 2022-09-06 12:17
The issue is that the vue runtime compiler is _generating_ code:

https://github.com/vuejs/vue-next/blob/cd395559ce34bdcc77cf3cff6e5c062fc6d89d90/packages/compiler-core/src/codegen.ts#L361-L368

That code is referring to `vue/server-renderer` which is only really an alias for `@vue/server-renderer`. Because it's never used (in a CJS context) in the build we can't trace it properly. You can force include it via `nitro.externals.traceInclude`, but note that I have opened a PR to nitro which will have to be merged first (https://github.com/unjs/nitro/pull/475).

Let's keep chatting in your PR 😊

**Closed by danielroe** 2022-09-06 12:17 UTC
Labels: pending triage
