### ISSUE TITLE
Pnpm workspace - Error 500: Unexpected token '||='

### ISSUE THREAD

**Issue by bgrand-ch** [nuxt/framework#8620] opened 2022-11-02 12:40 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.20.1`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `pnpm@7.14.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

ℹ️ All works fine with `nuxt@3.0.0-rc.11`, error occur only with `nuxt@3.0.0-rc.12`.

1. Create a new monorepo project.
2. Add a single name in the `package.json` file of each Nuxt projects.
3. Add `pnpm-workspace.yaml` to the root folder.
4. Follow all `pnpm` steps on the [Nuxt installation](https://v3.nuxtjs.org/getting-started/installation/) page, for each projects.
5. Run `pnpm --filter my-project-name dev -o` to the root folder.
6. Error 500: `Unexpected token '||='`.

### Describe the bug

After "Nitro built" terminal message, there is an error 500 with the message: `Unexpected token '||='`.

```
500
Unexpected token '||='

at new Script (vm.js:102:7)
at createScript (vm.js:262:10)
at Object.runInThisContext (vm.js:310:10)
at ViteNodeRunner.directRequest (/Users/bgd/Documents/Projects/scores-plus/node_modules/.pnpm/vite-node@0.24.5/node_modules/vite-node/dist/client.mjs:245:19)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async ViteNodeRunner.cachedRequest (/Users/bgd/Documents/Projects/scores-plus/node_modules/.pnpm/vite-node@0.24.5/node_modules/vite-node/dist/client.mjs:129:12)
at async request (/Users/bgd/Documents/Projects/scores-plus/node_modules/.pnpm/vite-node@0.24.5/node_modules/vite-node/dist/client.mjs:152:16)
at async /Users/bgd/Documents/Projects/scores-plus/node_modules/.pnpm/nuxt@3.0.0-rc.12/node_modules/nuxt/dist/app/composables/index.mjs:46:31
at async ViteNodeRunner.directRequest (/Users/bgd/Documents/Projects/scores-plus/node_modules/.pnpm/vite-node@0.24.5/node_modules/vite-node/dist/client.mjs:250:5)
at async ViteNodeRunner.cachedRequest (/Users/bgd/Documents/Projects/scores-plus/node_modules/.pnpm/vite-node@0.24.5/node_modules/vite-node/dist/client.mjs:129:12)
```

### Logs

```shell
at new Script (vm.js:102:7)
at createScript (vm.js:262:10)
at Object.runInThisContext (vm.js:310:10)
at ViteNodeRunner.directRequest (/Users/bgd/Documents/Projects/scores-plus/node_modules/.pnpm/vite-node@0.24.5/node_modules/vite-node/dist/client.mjs:245:19)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async ViteNodeRunner.cachedRequest (/Users/bgd/Documents/Projects/scores-plus/node_modules/.pnpm/vite-node@0.24.5/node_modules/vite-node/dist/client.mjs:129:12)
at async request (/Users/bgd/Documents/Projects/scores-plus/node_modules/.pnpm/vite-node@0.24.5/node_modules/vite-node/dist/client.mjs:152:16)
at async /Users/bgd/Documents/Projects/scores-plus/node_modules/.pnpm/nuxt@3.0.0-rc.12/node_modules/nuxt/dist/app/composables/index.mjs:46:31
at async ViteNodeRunner.directRequest (/Users/bgd/Documents/Projects/scores-plus/node_modules/.pnpm/vite-node@0.24.5/node_modules/vite-node/dist/client.mjs:250:5)
at async ViteNodeRunner.cachedRequest (/Users/bgd/Documents/Projects/scores-plus/node_modules/.pnpm/vite-node@0.24.5/node_modules/vite-node/dist/client.mjs:129:12)
```

**Comment by manniL** [comment] 2022-11-02 12:45
Hey! This should be resolved when using [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the upcoming RC.

Duplicate of https://github.com/nuxt/framework/issues/8407

**Closed by manniL** 2022-11-02 12:45 UTC
Labels: pending triage
