### ISSUE TITLE
bug(nuxt): `Catch All Route` doesn't work with `404.vue` defined.

### ISSUE THREAD

**Issue by cpreston321** [nuxt/framework#7974] opened 2022-10-03 20:48 UTC
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-vzsju5?file=package.json

### Describe the bug

When `404.vue` is defined, `[...slug].vue` is ignored. I created a reproduction all you have to do is delete the `404.vue` and everything works as expected.

### Additional context

I was working on a project with a custom 404 page and a catch all route and this bug presented itself then when I deleted the custom `404.vue` page everything worked as expected.

**Comment by manniL** [comment] 2022-10-03 20:50
Duplicate of https://github.com/nuxt/framework/issues/6895 ☺️

**Comment by cpreston321** [comment] 2022-10-03 20:51
@manniL Want me to close issue since a duplicate ?

**Closed** 2022-10-03 20:52 UTC
Labels: pending triage
