### ISSUE TITLE
RC12: `vite.server.proxy` ignored in nuxt.config.ts

### ISSUE THREAD

**Issue by bcspragu** [nuxt/framework#8303] opened 2022-10-19 02:39 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.11` (note: I downgraded after rc12 broke things)
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I can try to make a fresh reproduction if needed, but the issue is pretty straightforward: updating to RC12 makes Vite dev server proxying stop working. For example, we have a config like the following:

```ts
  vite: {
    server: {
      proxy: {
        '/api': {
          target: 'http://localhost:8080',
        },
      },
    },
  },
```

We route any traffic at `http://localhost:3000/api/...` to our backend, running on 8080. This has worked well in all Nuxt 3 versions up til now, and as far as I can tell, is still a [valid and supported Vite option](https://vitejs.dev/config/server-options.html#server-proxy).

### Describe the bug

As of RC12, our proxy config is no longer respected. Building on the example above, a request to `http://localhost:3000/api/graphql` used to return a response from our backend server on `http://localhost:8080`, but now hits our Nuxt catchall route and gives us a 404 page.

SSR requests succeed as usual (because they don't use the proxy for backend requests), but any subsequent requests from the clients fail, because they're getting an HTML response when they were expecting JSON.

**Comment by KurumiRin** [comment] 2022-10-19 02:48
I also had this problem, because I configured `server: false` in useFetch and used vite proxy, so all my requests returned a 404 page.

**Comment by slarrasoain** [comment] 2022-10-19 15:45
I also had this problem. Just try with fresh install and the issue is still here.

**Comment by danielroe** [comment] 2022-10-19 15:48
Please do not use vite proxy. The vite dev server is _not the same thing_ as the nitro dev server and they are not compatible. See https://github.com/nuxt/framework/issues/7537#issuecomment-1247753895.

**Comment by P4sca1** [comment] 2022-10-19 22:11
We are using a proxy configured with nginx in production and I used the vite dev server proxy in development to get the same result. So there are legitimate reasons to use the vite proxy.

**Comment by bcspragu** [comment] 2022-10-19 22:20
Similar deal on our end: In production we use [rewrites in Firebase Hosting](https://firebase.google.com/docs/hosting/full-config#rewrites) to send traffic to the backend, so the proxying is only needed locally. We could use something like NGINX to do the proxying, but that's another service to run when developing.

**Comment by ironytr** [comment] 2022-10-26 16:40
this issue continues since 3.0.0-rc.11-27720657.a18f177 version.

**Comment by silencerspirit** [comment] 2022-10-27 09:55
@danielroe Can you advise some additional solution of proxying locally?

**Comment by bcspragu** [comment] 2022-10-27 15:45
It turns out that our deployed app was broken (broken SCSS styling, didn't root cause it) on RC11, so I bit the bullet and updated to RC12 (which fixed the issue).

My solution was an [NGINX](http://nginx.org/) proxy in a Docker container, that I start up alongside my backend service (though it could be done independently or with the frontend).

Here's how I did it, using the same example config as above:

```
  vite: {
    server: {
      proxy: {
        '/api': {
          target: 'http://localhost:8080',
        },
      },
    },
  },
```

The NGINX config looks like:

```
# nginx.conf, mostly copied from the nginx:1.23 container image's default nginx.conf file
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

http {
    server {
        listen       3000 default_server;
        listen       [::]:3000 default_server;

        location / {
            proxy_pass http://127.0.0.1:3002;
        }

        location /api/ {
            proxy_pass http://127.0.0.1:8080;
        }
    }
}

```

This config says "Run NGINX on port 3000, route traffic to anything at `/api/...` to port 8080 and everything else to port 3002". We use 3002 instead of 3001 because we've already co-opted 3001 for some WebSocket shenanigans.

And then we run NGINX in Docker with:

```
docker run \
  --net=host \
  --volume path/to/nginx.conf:/etc/nginx/nginx.conf:ro \
  nginx:1.23
```

The `--net=host` is important if you want it to proxy things that aren't also in Docker containers on the same Docker network. You might also want the usual Docker flags (`--rm` to delete after use, `--name` to reference it easily, `--detach` to run in the background, etc).

We then run (using `"scripts"` in package.json) our Nuxt dev server with:

`HOST=0.0.0.0 PORT=3002 nuxi dev`

and run it in preview mode with:

`nuxi build`
`HOST=0.0.0.0 PORT=3002 nuxi preview`

I also had to turn off `writeEarlyHints`, introduced in RC12, because NGINX was deeply unhappy with it, regardless of proxy buffering/not buffering/size/etc:

```
// in nuxt.config.ts
  experimental: {
    // This was breaking our local preview mode (e.g. `npm run preview`), see https://github.com/nuxt/framework/issues/8450
    writeEarlyHints: false,
  },
```

As far as I can tell, this works flawlessly, including HMR in dev mode.

**Comment by silencerspirit** [comment] 2022-10-27 20:39
@bcspragu thx so much for detailed answer.

**Comment by Binaryify** [comment] 2022-11-08 07:24
same

**Comment by manniL** [comment] 2022-11-08 07:40
With RC13, you can use Nitro's [`devProxy`](https://nitro.unjs.io/config#devproxy). Be aware of current [possible issues](https://github.com/unjs/nitro/issues/641) though.

**Comment by danielroe** [comment] 2022-11-08 13:46
Closing as we now have `devProxy` support, which is what you should use rather than the `vite.server.proxy` option. If you have any issues with it, please feel free to open a new issue with a reproduction and we can resolve there.

**Closed by danielroe** 2022-11-08 13:46 UTC
Labels: bug, vite, 🔨 p3-minor-bug
