### ISSUE TITLE
error: nuxt instance unavailable at Module.useAsyncData

### ISSUE THREAD

**Issue by Maxp777** [nuxt/framework#8826] opened 2022-11-08 18:20 UTC
### Environment

Nuxi 3.0.0-rc.14-27796957.b60f136                                                                                                                                                    
Nuxt 3.0.0-rc.14-27796957.b60f136 with Nitro 0.6.1-27791756.086802d 

### Reproduction

https://github.com/Maxp777/nuxt4

### Describe the bug

error: nuxt instance unavailable at Module.useNuxtApp

don't know what i do when try to make a reproduction to https://github.com/nuxt/framework/issues/8738?notification_referrer_id=NT_kwDOBvheOLQ0NzY3MzM1MjMxOjExNjk0MDM0NA&notifications_query=is%3Adone#event-7764608394, but all not work again

### Additional context
```
[log error] Error: nuxt instance unavailable
    at Module.useNuxtApp (/home/user/Downloads/nuxt-error-7-main/node_modules/nuxt/dist/app/nuxt.mjs:162:13)
    at Module.useAsyncData (/home/user/Downloads/nuxt-error-7-main/node_modules/nuxt/dist/app/composables/asyncData.mjs:28:38)
    at Module.useFetch (/home/user/Downloads/nuxt-error-7-main/node_modules/nuxt/dist/app/composables/fetch.mjs:52:43)
    at Proxy.updateList (/home/user/Downloads/nuxt-error-7-main/store/list.store.ts:25:27)
    at Proxy.<anonymous> (file:///home/user/Downloads/nuxt-error-7-main/node_modules/pinia/dist/pinia.mjs:1365:30)
    at update (/home/user/Downloads/nuxt-error-7-main/pages/index.vue:43:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async setup (/home/user/Downloads/nuxt-error-7-main/pages/index.vue:55:83) {} setup function
[Vue Router warn]: No match found for location with path "/api/test"

```
_No response_

**Comment by dargmuesli** [comment] 2022-11-09 05:14
Having 26 dependencies in a project might not be a minimal reproduction for a potential dependency related issue :thinking: 
Maybe try to use [https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz](stackblitz) instead 💪

**Comment by Maxp777** [comment] 2022-11-09 07:22
@dargmuesli having only nuxt related dependencies not change situation

```
  "dependencies": {
    "@nuxtjs-alt/auth": "^2.0.30",
    "@nuxtjs-alt/http": "^1.4.2",
    "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge",
    "@pinia/nuxt": "^0.4.3",
    "pinia": "^2.0.23"
  },
  "devDependencies": {
    "@nuxt/image-edge": "^1.0.0-27769790.4b27db3",
    "@nuxt/types": "^2.15.8",
    "@types/express": "^4.17.14",
    "@types/node": "^18.11.9",
    "nuxt": "npm:nuxt3@latest"
  }
}
```

**Comment by Maxp777** [comment] 2022-11-09 07:50
and why vue router is looking for such path 'api/test'
[Vue Router warn]: No match found for location with path "/api/test"

**Comment by Maxp777** [comment] 2022-11-09 07:56
it work when i enable `"@nuxtjs/i18n"`, but i remove from demo all ussage of i18n i think!!!??

**Comment by Maxp777** [comment] 2022-11-09 08:17
whom what I start [Error nuxt instance unavailable]( https://github.com/nuxt/framework/issues/6300) to that I returned

**Comment by danielroe** [comment] 2022-11-09 08:42
If you are getting this only with these modules, then almost certainly this is an issue with one of them.

Please remove them one by one until you find the issue, then raise an issue there and feel free to tag me; I'd be delighted to help resolve it. But I'm going to close this here as it's not an issue with Nuxt.

**Closed by danielroe** 2022-11-09 08:42 UTC
Labels: pending triage

**Comment by Maxp777** [comment] 2022-11-09 09:18
@danielroe I removed all, but it not work without it, and wok with it

```
modules: [
    // "@nuxtjs/i18n",
    // '@nuxtjs-alt/auth',
    // '@nuxtjs-alt/http',
    '@pinia/nuxt'
  ],
  ```

**Comment by Maxp777** [comment] 2022-11-09 09:28
@danielroe not understan, i leave only these and also not work

```
{
  "private": true,
  "scripts": {
    "analyze": "nuxi build --analyze",
    "build": "nuxi build",
    "clean": "npx nuxi clean",
    "dev": "nuxi dev",
    "generate": "nuxi generate",
    "preview": "nuxi preview",
    "start": "nuxi start"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.3",
    "pinia": "^2.0.23"
  },
  "devDependencies": {
    "@nuxt/types": "^2.15.8",
    "@types/express": "^4.17.14",
    "@types/node": "^18.11.9",
    "nuxt": "npm:nuxt3@latest"
  }
}

```

**Comment by danielroe** [comment] 2022-11-09 09:34
Please remove `@nuxt/types` - that's Nuxt 2. And try without pinia as well.

**Comment by Maxp777** [comment] 2022-11-09 09:35
@danielroe i don't need nuxt without pinia

**Comment by danielroe** [comment] 2022-11-09 09:35
It's not about asking you not to _use_ pinia. It's about figuring out whether the issue is within the pinia library or not.

**Comment by danielroe** [comment] 2022-11-09 09:39
Checking your code, the issue is with how you are calling the pinia actions, not with pinia itself: https://github.com/nuxt/framework/issues/8844#issuecomment-1308475169.

**Comment by Maxp777** [comment] 2022-11-09 09:42
@danielroe but the same code work with @nuxt-i18n enabled?

**Comment by Maxp777** [comment] 2022-11-09 09:43
but make difference.

**Comment by Maxp777** [comment] 2022-11-09 09:49
yes it work when i enable i18n module

**Comment by Maxp777** [comment] 2022-11-09 09:55
but in full code project api call sare made and all is ok, except warning

**Comment by danielroe** [comment] 2022-11-09 10:03
I suspect the issue is that some other problem is hiding it when you enable i18n.

**Comment by Maxp777** [comment] 2022-11-09 10:05
> I suspect the issue is that some other problem is hiding it when you enable i18n.

but whe i usea lla modules (i18n, nuxtjsalt-http, nuxtjsalt-auth) api call are made and page a generated well.

**Comment by Maxp777** [comment] 2022-11-09 10:17
and in vue devtool  `fullPath:undefined (Computed)`

_route:Reactive
fullPath:undefined (Computed)
path:"/" (Computed)
