### ISSUE TITLE
Identifier 'xxx' has already been declared

### ISSUE THREAD

**Issue by riderx** [nuxt/framework#5450] opened 2022-06-13 19:30 UTC
### Environment

```
Nuxt CLI v3.0.0-rc.4                                                                                                                  20:29:45
RootDir: /Users/martindonadieu/Documents/Projects.nosync/Capacitor/nuxt-app                                                           20:29:48
Nuxt project info:                                                                                                                    20:29:48

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `pnpm@7.2.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                      20:29:48

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org
```

### Reproduction

```
pnpm dlx nuxi init nuxt-app
cd nuxt-app
pnpm i
pnpm build
```

### Describe the bug

When building, some dependencies are failing

### Additional context
<img width="1253" alt="Screenshot 2022-06-13 at 20 29 16" src="https://user-images.githubusercontent.com/4084527/173430351-d8bd0f86-1534-4300-bae1-7fe9ea0b0d78.png">
 and in old project i get 
<img width="1209" alt="Screenshot 2022-06-13 at 20 39 46" src="https://user-images.githubusercontent.com/4084527/173431894-5fcaf80b-3b18-43fa-89cf-e876967093f1.png">

_No response_

**Comment by DamianGlowala** [comment] 2022-06-13 20:32
As much as nothing broke on my side, I had to rollback to RC3 as with RC4 the last terminal log was `Vite server warmed up in (...)` and then my machine resources' usage went up. Something is not right with Vite since last RC? The `Vite server built in (...)` never appears.

My Nuxt project is large already and it would be difficult to find what breaks the dev build. I checked it with a fresh RC4 project and it runs fine though.

**Comment by MaximKing1** [comment] 2022-06-13 20:55
I’m getting a similar issue, but when I upgraded I had the build error:
`ERROR  Identifier 'createError' has already been declared (Note that you need plugins to import files that are not JavaScript)`.

Tested using Darwin and Ubuntu 20.04 and both have this error using the new RC 4, when reverting to RC 3 it works fine. 
```
Nuxi CLI v3.0.0-rc.4                                                                                                                 
Nuxt project info:                                                                                                                   

------------------------------
- Operating System: `Darwin` & `Ubuntu`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarnpkg`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

**Comment by DamianGlowala** [comment] 2022-06-13 21:01
Have you tried deleting `node_modules` and installing dependencies again? Might or might not help, give it a go. I did it anyway when switching to RC4 so cannot tell whether the behavior would have been the same for me.

**Comment by zknicker** [comment] 2022-06-13 21:07
> As much as nothing broke on my side, I had to rollback to RC3 as with RC4 the last terminal log was `Vite server warmed up in (...)` and then my machine resources' usage went up. Something is not right with Vite since last RC? The `Vite server built in (...)` never appears.
> 
> My Nuxt project is large already and it would be difficult to find what breaks the dev build. I checked it with a fresh RC4 project and it runs fine though.

Had this experience as well. About a week ago my large Nuxt 3 rc3 app stopped building on Vercel, with the same symptoms of hanging on "Vite server warmed up in (...)" and never posting "Vite server built in (...)" until eventually Vercel just timed my build out (45min). My builds typically take 2min. I downgraded top rc2 and that fixed the issue for a while, until today when this "useCookie" referenced in the original post started occurring (even on rc2). Upgrading to rc4 does not fix the issue. So maybe it's a downstream issue from a Nuxt dependency?

**Comment by danielroe** [comment] 2022-06-13 22:08
Sounds like this might possibly be related to unplugin. cc: @antfu

**Comment by yezipi** [comment] 2022-06-14 07:20
same issue，how long will it take to solve this problem

**Comment by KahrLu** [comment] 2022-06-14 08:26
today I met the same error, What's more strange is that I have been using the RC1 version so far without any change, but this error occurred suddenly today.
![image](https://user-images.githubusercontent.com/76502123/173530864-ae61d7bb-19ba-4a24-86f3-7bab20849c2b.png)

**Comment by misaon** [comment] 2022-06-14 08:58
![image](https://user-images.githubusercontent.com/15806356/173537754-60139840-8f5b-47e1-b98c-2484a68860cc.png)

**Comment by joshwcorbett** [comment] 2022-06-14 13:39
Feel like I can contribute here...

<img width="1002" alt="Screen Shot 2022-06-14 at 7 38 41 AM" src="https://user-images.githubusercontent.com/23065423/173590993-bf8b8dd9-ef76-4a9d-aa04-b401efb1730e.png">

**Comment by antfu** [comment] 2022-06-14 15:24
I can't reproduce it in a clean init. Can anyone share a minimal reproduction repo with lock file? Thanks.

**Comment by joshwcorbett** [comment] 2022-06-14 16:31
Here's a quick repro I made: https://stackblitz.com/edit/nuxt-starter-tgbfaq?file=nuxt.config.ts

**Comment by amiria703** [comment] 2022-06-14 21:10
As the [documentation](https://v3.nuxtjs.org/getting-started/quick-start) states, we should use this command to install dependencies when we're using pnpm:
```sh
pnpm i --shamefully-hoist
```

Tried with simple `pnpm i`:
```
amiria703@amiria703:/tmp/nuxt-app$ pnpm i
 WARN  deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
Packages: +604
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /tmp/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 616, reused 1, downloaded 595, added 604, done
node_modules/.pnpm/esbuild@0.14.43/node_modules/esbuild: Running postinstall script, done in 1.6s

devDependencies:
+ nuxt 3.0.0-rc.4
amiria703@amiria703:/tmp/nuxt-app$ pnpm build

> @ build /tmp/nuxt-app
> nuxt build

Nuxt CLI v3.0.0-rc.4                                                                                                                                01:15:49

 ERROR  Failed to resolve force included dependency: vue                                                                                            01:16:09


 ERROR  Failed to resolve import "ufo" from "virtual:nuxt:/tmp/nuxt-app/.nuxt/paths.mjs". Does the file exist?                                      01:16:09


 ERROR  Failed to resolve import "vue" from "virtual:nuxt:/tmp/nuxt-app/.nuxt/components.plugin.mjs". Does the file exist?                          01:16:09


 ERROR  [vite]: Rollup failed to resolve import "ufo" from "virtual:nuxt:/tmp/nuxt-app/.nuxt/paths.mjs".                                            01:16:09
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`


 ERROR  [vite]: Rollup failed to resolve import "ufo" from "virtual:nuxt:/tmp/nuxt-app/.nuxt/paths.mjs".                                            01:16:09
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
  at onRollupWarning (node_modules/.pnpm/vite@2.9.12/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41772:19)
  at onwarn (node_modules/.pnpm/vite@2.9.12/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41588:13)
  at Object.onwarn (node_modules/.pnpm/rollup@2.75.6/node_modules/rollup/dist/shared/rollup.js:23224:13)
  at ModuleLoader.handleResolveId (node_modules/.pnpm/rollup@2.75.6/node_modules/rollup/dist/shared/rollup.js:22508:26)
  at node_modules/.pnpm/rollup@2.75.6/node_modules/rollup/dist/shared/rollup.js:22469:26

 ELIFECYCLE  Command failed with exit code 1.
```
But with `pnpm i --shamefully-hoist`:
```
amiria703@amiria703:/tmp/nuxtest$ pnpm i --shamefully-hoist
 WARN  deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
 WARN  GET https://registry.npmjs.org/@babel%2Fhelper-annotate-as-pure error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
Packages: +604
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /tmp/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 616, reused 596, downloaded 0, added 604, done

devDependencies:
+ nuxt 3.0.0-rc.4
amiria703@amiria703:/tmp/nuxtest$ pnpm build

> @ build /tmp/nuxtest
> nuxt build

Nuxt CLI v3.0.0-rc.4                                                                                                                                01:35:05
ℹ Vite client warmed up in 10698ms                                                                                                                  01:35:30
ℹ Client built in 10839ms                                                                                                                           01:35:30
ℹ Building server...                                                                                                                                01:35:30
✔ Server built in 3189ms                                                                                                                            01:35:33
✔ Generated public .output/public                                                                                                             nitro 01:35:33
start Building server...                                                                                                                      nitro 01:35:33
start Writing server bundle...                                                                                                                nitro 01:35:50
✔ Server built                                                                                                                                nitro 01:35:57
  ├─ .output/server/package.json (307 B) (182 B gzip)
  ├─ .output/server/index.mjs (458 B) (254 B gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs.map (57.4 kB) (4.4 kB gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs (15.9 kB) (5.13 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs.map (1.92 MB) (91.4 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs (431 kB) (98.6 kB gzip)
  ├─ .output/server/chunks/app/server.mjs.map (163 kB) (23.5 kB gzip)
  ├─ .output/server/chunks/app/server.mjs (152 kB) (39.4 kB gzip)
  ├─ .output/server/chunks/app/client.manifest.mjs.map (336 B) (220 B gzip)
  └─ .output/server/chunks/app/client.manifest.mjs (384 B) (230 B gzip)
Σ Total size: 3.28 MB (394 kB gzip)
✔ You can preview this build using node .output/server/index.mjs                                                                              nitro 01:36:01
```

**Comment by HomeGridMx** [comment] 2022-06-14 21:16
Hi guys, when I delete de "pages"  folder I run "npm run build" with no issues, and if a create/put the "pages" folder back and run again "npm run build" the error occur. Even if "pages" is empty, the error shows up.

**Comment by joshwcorbett** [comment] 2022-06-14 21:18
> As the [documentation](https://v3.nuxtjs.org/getting-started/quick-start) states, we should use this command to install dependencies when we're using pnpm:
> 
> ```sh
> 
> pnpm i --shamefully-hoist
> 
> ```
> 
> 
> 
> Tried with simple `pnpm i`:
> 
> ```
> 
> amiria703@amiria703:/tmp/nuxt-app$ pnpm i
> 
>  WARN  deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
> 
> Packages: +604
> 
> ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> 
> Packages are hard linked from the content-addressable store to the virtual store.
> 
>   Content-addressable store is at: /tmp/.pnpm-store/v3
> 
>   Virtual store is at:             node_modules/.pnpm
> 
> Progress: resolved 616, reused 1, downloaded 595, added 604, done
> 
> node_modules/.pnpm/esbuild@0.14.43/node_modules/esbuild: Running postinstall script, done in 1.6s
> 
> 
> 
> devDependencies:
> 
> + nuxt 3.0.0-rc.4
> 
> amiria703@amiria703:/tmp/nuxt-app$ pnpm build
> 
> 
> 
> > @ build /tmp/nuxt-app
> 
> > nuxt build
> 
> 
> 
> Nuxt CLI v3.0.0-rc.4                                                                                                                                01:15:49
> 
> 
> 
>  ERROR  Failed to resolve force included dependency: vue                                                                                            01:16:09
> 
> 
> 
> 
> 
>  ERROR  Failed to resolve import "ufo" from "virtual:nuxt:/tmp/nuxt-app/.nuxt/paths.mjs". Does the file exist?                                      01:16:09
> 
> 
> 
> 
> 
>  ERROR  Failed to resolve import "vue" from "virtual:nuxt:/tmp/nuxt-app/.nuxt/components.plugin.mjs". Does the file exist?                          01:16:09
> 
> 
> 
> 
> 
>  ERROR  [vite]: Rollup failed to resolve import "ufo" from "virtual:nuxt:/tmp/nuxt-app/.nuxt/paths.mjs".                                            01:16:09
> 
> This is most likely unintended because it can break your application at runtime.
> 
> If you do want to externalize this module explicitly add it to
> 
> `build.rollupOptions.external`
> 
> 
> 
> 
> 
>  ERROR  [vite]: Rollup failed to resolve import "ufo" from "virtual:nuxt:/tmp/nuxt-app/.nuxt/paths.mjs".                                            01:16:09
> 
> This is most likely unintended because it can break your application at runtime.
> 
> If you do want to externalize this module explicitly add it to
> 
> `build.rollupOptions.external`
> 
> 
> 
>   This is most likely unintended because it can break your application at runtime.
> 
>   If you do want to externalize this module explicitly add it to
> 
>   `build.rollupOptions.external`
> 
>   at onRollupWarning (node_modules/.pnpm/vite@2.9.12/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41772:19)
> 
>   at onwarn (node_modules/.pnpm/vite@2.9.12/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41588:13)
> 
>   at Object.onwarn (node_modules/.pnpm/rollup@2.75.6/node_modules/rollup/dist/shared/rollup.js:23224:13)
> 
>   at ModuleLoader.handleResolveId (node_modules/.pnpm/rollup@2.75.6/node_modules/rollup/dist/shared/rollup.js:22508:26)
> 
>   at node_modules/.pnpm/rollup@2.75.6/node_modules/rollup/dist/shared/rollup.js:22469:26
> 
> 
> 
>  ELIFECYCLE  Command failed with exit code 1.
> 
> ```
> 
> But with `pnpm i --shamefully-hoist`:
> 
> ```
> 
> amiria703@amiria703:/tmp/nuxtest$ pnpm i --shamefully-hoist
> 
>  WARN  deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
> 
>  WARN  GET https://registry.npmjs.org/@babel%2Fhelper-annotate-as-pure error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
> 
> Packages: +604
> 
> ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> 
> Packages are hard linked from the content-addressable store to the virtual store.
> 
>   Content-addressable store is at: /tmp/.pnpm-store/v3
> 
>   Virtual store is at:             node_modules/.pnpm
> 
> Progress: resolved 616, reused 596, downloaded 0, added 604, done
> 
> 
> 
> devDependencies:
> 
> + nuxt 3.0.0-rc.4
> 
> amiria703@amiria703:/tmp/nuxtest$ pnpm build
> 
> 
> 
> > @ build /tmp/nuxtest
> 
> > nuxt build
> 
> 
> 
> Nuxt CLI v3.0.0-rc.4                                                                                                                                01:35:05
> 
> ℹ Vite client warmed up in 10698ms                                                                                                                  01:35:30
> 
> ℹ Client built in 10839ms                                                                                                                           01:35:30
> 
> ℹ Building server...                                                                                                                                01:35:30
> 
> ✔ Server built in 3189ms                                                                                                                            01:35:33
> 
> ✔ Generated public .output/public                                                                                                             nitro 01:35:33
> 
> start Building server...                                                                                                                      nitro 01:35:33
> 
> start Writing server bundle...                                                                                                                nitro 01:35:50
> 
> ✔ Server built                                                                                                                                nitro 01:35:57
> 
>   ├─ .output/server/package.json (307 B) (182 B gzip)
> 
>   ├─ .output/server/index.mjs (458 B) (254 B gzip)
> 
>   ├─ .output/server/chunks/nitro/node-server.mjs.map (57.4 kB) (4.4 kB gzip)
> 
>   ├─ .output/server/chunks/nitro/node-server.mjs (15.9 kB) (5.13 kB gzip)
> 
>   ├─ .output/server/chunks/handlers/renderer.mjs.map (1.92 MB) (91.4 kB gzip)
> 
>   ├─ .output/server/chunks/handlers/renderer.mjs (431 kB) (98.6 kB gzip)
> 
>   ├─ .output/server/chunks/app/server.mjs.map (163 kB) (23.5 kB gzip)
> 
>   ├─ .output/server/chunks/app/server.mjs (152 kB) (39.4 kB gzip)
> 
>   ├─ .output/server/chunks/app/client.manifest.mjs.map (336 B) (220 B gzip)
> 
>   └─ .output/server/chunks/app/client.manifest.mjs (384 B) (230 B gzip)
> 
> Σ Total size: 3.28 MB (394 kB gzip)
> 
> ✔ You can preview this build using node .output/server/index.mjs                                                                              nitro 01:36:01
> 
> ```

Not everybody here uses pnpm, my project uses yarn and got the same issues.

**Comment by amiria703** [comment] 2022-06-14 21:20
@joshwcorbett Anyway OP used pnpm and got same error as me.

**Comment by HomeGridMx** [comment] 2022-06-14 22:01
This line:  const config = useRuntimeConfig();

is causing this error:

<img width="1227" alt="Screen Shot 2022-06-14 at 17 00 48" src="https://user-images.githubusercontent.com/87785533/173696576-192acfc7-77cb-4dba-b568-42f4cf5915f1.png">

**Comment by jamaluddinrumi** [comment] 2022-06-14 22:30
> I can't reproduce it in a clean init. Can anyone share a minimal reproduction repo with lock file? Thanks.

you are welcome to use my repo https://github.com/jamaluddinrumi/getanah.v3 

i'm facing the same issue here https://github.com/nuxt/framework/issues/5458

**Comment by danielroe** [comment] 2022-06-14 22:43
@jamaluddinrumi I still can't reproduce it, either [in stackblitz](https://stackblitz.com/edit/github-pm6pa9) or in a fresh `yarn install` locally. If you delete `.nuxt` and `node_modules`, then reinstall, does that make a difference?

**Comment by jamaluddinrumi** [comment] 2022-06-14 23:02
> @jamaluddinrumi I still can't reproduce it, either [in stackblitz](https://stackblitz.com/edit/github-pm6pa9) or in a fresh `yarn install` locally. If you delete `.nuxt` and `node_modules`, then reinstall, does that make a difference?

ya, everything is fine with `yarn dev` 

but not with `yarn build`

**Comment by itzaks** [comment] 2022-06-14 23:20
Getting this too, when deploying on netlify with yarn build. Seems to happen even on `rc.3-27585445.4fdea30`

`1:16:39 AM: [error] [nitro] Rollup error: Identifier 'useRuntimeConfig' has already been declared (Note that you need plugins to import files that are not JavaScript)
1:16:39 AM: [error] Identifier 'useRuntimeConfig' has already been declared (Note that you need plugins to import files that are not JavaScript)
1:16:39 AM:   at error (node_modules/rollup/dist/es/shared/rollup.js:1858:30)
1:16:39 AM:   at Module.error (node_modules/rollup/dist/es/shared/rollup.js:12422:16)
1:16:39 AM:   at Module.tryParse (node_modules/rollup/dist/es/shared/rollup.js:12799:25)
1:16:39 AM:   at Module.setSource (node_modules/rollup/dist/es/shared/rollup.js:12704:24)
1:16:39 AM:   at ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/rollup.js:22178:20)
`

**Comment by mahapo** [comment] 2022-06-14 23:56
Same issue here on netlify. Downgrading to rc.3 loads rc.4 in yarn.lock. With rc.2 too
![image](https://user-images.githubusercontent.com/28730855/173708274-1ee30fb1-0bc4-4093-9601-25563b1fec8b.png)

**Comment by KahrLu** [comment] 2022-06-15 01:49
Hi @danielroe ,your repo can reproduce the bug
![image](https://user-images.githubusercontent.com/76502123/173719024-fc2f6784-d95e-49d6-b1c5-793e52a6e447.png)
cc: @antfu

**Comment by phlqp** [comment] 2022-06-15 02:19
Here a simply example to reproduce this bug: https://stackblitz.com/edit/github-49tvxk-ugx2wx

**Comment by antfu** [comment] 2022-06-15 03:18
> Here a simply example to reproduce this bug: [stackblitz.com/edit/github-49tvxk-ugx2wx](https://stackblitz.com/edit/github-49tvxk-ugx2wx) **yarn build**

Thanks! I can reproduce with this. Investigating now.

**Comment by antfu** [comment] 2022-06-15 03:45
Fix upstream: https://github.com/unjs/nitro/pull/291

**Comment by misaon** [comment] 2022-06-15 06:43
@danielroe Will RC-5 be released after this fix?

**Comment by danielroe** [comment] 2022-06-15 06:55
No, once it is released you will simply be able to run `yarn upgrade` or `npm upgrade` to pull in the updated nitropack version.

**Comment by itzaks** [comment] 2022-06-15 08:10
Thanks for the quick fix, is there any workaround to get this running until nitro is updated?

**Comment by lyykfi** [comment] 2022-06-15 09:21
> Thanks for the quick fix, seems like downgrading nitropack to 0.4.4 by adding it to resolutions fixes this for yarn – until it's officially updated.
> 
> ```
>   "resolutions": {
>     "nitropack": "0.4.4"
>   }
> ```

Seems like this way doesn't work for npm.

**Comment by sewalsh** [comment] 2022-06-15 10:28
> 



> > Thanks for the quick fix, seems like downgrading nitropack to 0.4.4 by adding it to resolutions fixes this for yarn – until it's officially updated.
> > ```
> >   "resolutions": {
> >     "nitropack": "0.4.4"
> >   }
> > ```
> 
> Seems like this way doesn't work for npm.

For npm, use `overrides` : 

```
{
  "overrides": {
    "nitropack": "0.4.4"
  }
}
```

**Comment by pi0** [comment] 2022-06-15 11:50
Sorry for the regression 🙏🏼 Hotfix is released as `nitropack@0.4.8`. Please remove `resolutions`, and update the lock file either manually or using `npx nuxi upgrade` to receive the hotfix.

**Closed by pi0** 2022-06-15 11:50 UTC
Labels: bug, upstream, ❗ p4-important

**Comment by riderx** [comment] 2022-06-15 16:05
@pi0 the main build system is fixed with `nitropack@0.4.8` but not the other nitro option:
`NITRO_PRESET=netlify-edge npx pnpm build` on a new repo do that:
<img width="1278" alt="Screenshot 2022-06-15 at 17 05 16" src="https://user-images.githubusercontent.com/4084527/173873882-80414c0f-f041-400d-a065-065dd61f8b2d.png">

**Comment by danielroe** [comment] 2022-06-15 16:07
@riderx You need to shamefully hoist your dependencies.

**Comment by danielroe** [comment] 2022-06-15 20:19
@riderx That looks like a different issue. Would you raise a new issue please so we can track it separately? 🙏

**Comment by riderx** [comment] 2022-06-15 20:59
@danielroe that why i have open the issue just my reproduction demo lead us to another bug ^^, but i made one https://github.com/nuxt/framework/issues/5482

**Comment by mklueh** [comment] 2022-06-30 19:09
I had this issue after copying files from one old project into a new one, including the compiled .js files from TypeScript. After deleting those .js files the error is gone

**Comment by together-mcar** [comment] 2022-09-05 08:14
ERROR  [vite]: Rollup failed to resolve import "vue" from "node_modules/.pnpm/nuxt@3.0.0-rc.9/node_modules/nuxt/dist/app/entry.mjs".                                                                                                  16:13:43
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

**Comment by danielroe** [comment] 2022-09-05 08:23
Please ensure you are installing with `--shamefully-hoist`.

**Comment by together-mcar** [comment] 2022-09-05 08:38
ok，use yarn

**Comment by richgcook** [comment] 2022-09-07 08:05
I am getting a similar error `Identifier '_unref' has already been declared (Note that you need plugins to import files that are not JavaScript)` when using `Nuxt 3.0.0-rc.9 with Nitro 0.5.1`

**Comment by Ischafak** [comment] 2022-10-17 15:09
<img width="806" alt="image" src="https://user-images.githubusercontent.com/13226879/196214074-bf45b30e-e68b-4511-8caa-76be36a1e059.png">

I have this error

I am using nuxt 3.0.0-rc.11 and trying to add vue-number-animation plugin 
there is not problem with yarn dev but when i try to generate it gives me this error how can i fix can someone help me?

**Comment by danielroe** [comment] 2022-10-17 15:20
@Ischafak I doubt that is the same issue. Would you create a new issue with a reproduction please?

**Comment by terwer** [comment] 2022-11-16 05:15
I face this issue with github action, and solved by using

```bash
pnpm i --shamefully-hoist && pnpm run build
```

insteadof  

```bash
pnpm i && pnpm run build
```
