### ISSUE TITLE
Keep-alive duplicate page

### ISSUE THREAD

**Issue by bot08** [nuxt/framework#3736] opened 2022-03-17 12:45 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-27458584.91fd16a`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Stackblitz: https://stackblitz.com/edit/github-rqgdjo?file=app.vue
first page => second page => third page => first page => .....

### Describe the bug

Page duplicates after route on client side

**Comment by wehappyhr** [comment] 2022-06-13 20:17
Is this really a minor bug? To me it looks like keep-alive is not working at all, try adding some inputs to each page

**Comment by Javierieh** [comment] 2022-06-13 20:18
Is this really a minor bug? To me it looks like keep-alive is not working at all, try adding some inputs to each page

**Comment by danielroe** [comment] 2022-09-15 23:10
This is no longer reproducible for me in that reproduction, so I'm closing the issue. Let me know if it's still occuring for you and I'll reopen.

---

Note that it is now possible to configure keepalive directly via props to `<NuxtPage>`: https://github.com/nuxt/framework/pull/7492.

For what it's worth, `keepalive` is meant to fully disable the parent `<keepalive>` component. If you want to configure what is included, you can pass an object with options:

```js
definePageMeta({
  keepalive: {
    include: [/* */]
  }
})
```

**Closed by danielroe** 2022-09-15 23:10 UTC
Labels: bug, nuxt3, 🔨 p3-minor-bug

**Comment by Javierieh** [comment] 2022-10-03 19:53
Yes this was fixed, passing keepalive to NuxtPage directly seems to be the straightforward way to accomplish this.

Thanks for the PR!
