### ISSUE TITLE
Nuxt3 dev server often fail on GC error.

### ISSUE THREAD

**Issue by xieyuheng** [nuxt/framework#6286] opened 2022-08-01 23:47 UTC
### Environment

❯ npx nuxi info
Nuxt CLI v3.0.0-rc.6                                                                                              07:46:06
RootDir: /home/xyh/pomodoro                                                                                       07:46:08
Nuxt project info:                                                                                                07:46:08

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `transpile`, `srcDir`, `modules`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.1`
- Build Modules:    `-`
------------------------------

### Reproduction

Can not reproduce, but it happens very often.

### Describe the bug

```
<--- Last few GCs --->

[501450:0x570d000]  2533647 ms: Mark-sweep (reduce) 1966.5 (2087.1) -> 1958.9 (2079.5) MB, 3746.7 / 0.1 ms  (average mu = 0.307, current mu = 0.029) allocation failure scavenge might not succeed
[501450:0x570d000]  2538290 ms: Mark-sweep (reduce) 1970.0 (2089.4) -> 1964.7 (2085.2) MB, 4628.6 / 0.0 ms  (average mu = 0.168, current mu = 0.003) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb00e10 node::Abort() [node]
 2: 0xa1823b node::FatalError(char const*, char const*) [node]
 3: 0xcee09e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcee417 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xea65d5  [node]
 6: 0xeb5cad v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xeb89ae v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xe79dda v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
 9: 0x11f33d6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x15e7cf9  [node]
```

**Comment by danielroe** [comment] 2022-08-02 08:39
This is likely due to a memory leak in your code or in a library used in your project. It will be almost impossible to find unless a reproduction is provided, so I'll need to close it.

Feel free to add a reproduction (even if it's sporadic) and I'll happily reopen :pray:

**Closed** 2022-08-02 08:39 UTC
Labels: pending triage
