### ISSUE TITLE
"nuxi build" on github action lost public's files

### ISSUE THREAD

**Issue by liuqian1996** [nuxt/framework#2298] opened 2021-12-06 04:57 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27304790.cad09fe`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `alias`, `meta`, `css`, `vite`, `publicRuntimeConfig`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/core/nuxt@7.1.2`

### Reproduction

None

### Describe the bug

```yml
  - name: ls web
  run: |
    cd packages/web
    yarn --immutable
    yarn build
    ls -l .output/public/_nuxt
```

Public folder

![image](https://user-images.githubusercontent.com/11707934/144789528-c244be27-94b1-451f-8471-ae85e1c5134d.png)

Github Action

![image](https://user-images.githubusercontent.com/11707934/144788919-5b6bc26a-d064-4728-a1cd-c09fa4c55145.png)

Windows

![image](https://user-images.githubusercontent.com/11707934/144789041-6ddd2b13-d2af-4505-b091-d20b8db41766.png)

**Comment by danielroe** [comment] 2021-12-06 10:24
Is this the same issue as https://github.com/nuxt/framework/issues/2261? If not, could you provide a reproduction?

**Comment by Jos-de-Boss** [comment] 2021-12-06 13:00
Hey liuqian. Ever since #2135 public files aren't copied to `.output/public/_nuxt` anymore. They are only located in `.output/public` now if you're looking for the files.

As a result `example.com/_nuxt/myfile.json` will no longer work and you'll need to use `example.com/myfile.json`. As described in #2261 images are still incorrectly prefixed with `/_nuxt` on build. (Not sure if that's the bug you're describing)

Hope this helps.

**Comment by liuqian1996** [comment] 2021-12-06 17:49
@danielroe I'm sorry, I just saw that they have different version, I think it's the same issue, Thank you 
@Jos-de-Boss yeah, I found `example.com/_nuxt/myfile.json` got 404, and I'm sorry for ignored nuxt3 different version, Thank you

**Comment by dergunovs** [comment] 2021-12-06 19:50
> Hey liuqian. Ever since #2135 public files aren't copied to `.output/public/_nuxt` anymore. They are only located in `.output/public` now if you're looking for the files.
> 
> As a result `example.com/_nuxt/myfile.json` will no longer work and you'll need to use `example.com/myfile.json`. As described in #2261 images are still incorrectly prefixed with `/_nuxt` on build. (Not sure if that's the bug you're describing)
> 
> Hope this helps.

I'm trying to import font in css with:
@font-face { font-family: "font"; src: url("/assets/fonts/400.woff2") format("woff2"); font-weight: 400;  font-display: swap }

In production build nuxt puts font in /_nuxt/assets/fonts/400.woff2
But this file in /public/assets/fonts/400.woff2. This breaks correct link preload meta with static path to font in public folder.

**Comment by Jos-de-Boss** [comment] 2021-12-08 13:16
> I'm trying to import font in css with:
> @font-face { font-family: "font"; src: url("/assets/fonts/400.woff2") format("woff2"); font-weight: 400; font-display: swap }
> 
> In production build nuxt puts font in /_nuxt/assets/fonts/400.woff2
> But this file in /public/assets/fonts/400.woff2. This breaks correct link preload meta with static path to font in public folder.
> 
> I'm using the lastest version.

Sounds like #2261. Though in your case it's a font-url being parsed incorrectly during the `build` process rather then an image url.

**Comment by dergunovs** [comment] 2021-12-08 13:18
> 

Yes, problem with font url.

**Comment by danielroe** [comment] 2021-12-08 14:49
(Closing to follow this in https://github.com/nuxt/framework/issues/2261.)

**Closed by danielroe** 2021-12-08 14:49 UTC
Labels: nuxt3, needs reproduction, pending triage

**Comment by mrsai** [comment] 2022-04-09 14:38
The Same problem.

When I exec "nuxi build" on my computer, the static files in the static-folder will be copied to the  ".output/public" directory, but when I run "nuxt build"  on my centos server, it did not copy the files to ".output/public" directory, can anyone help me? Thanks!

**Comment by danielroe** [comment] 2022-04-11 08:57
Would you create a new issue with a reproduction? Your issue doesn't sound related to this one.
