### ISSUE TITLE
nitroApp.h3App.use() isn't working

### ISSUE THREAD

**Issue by modelair** [nuxt/framework#6498] opened 2022-08-11 00:14 UTC
### Environment

Nuxt project info:                                                                                                                                                                                        11:41:02

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
------------------------------

### Reproduction

1. Create a nuxt3 app
2. Create a nitro plugin 
3. Import it in nuxt.config.ts

```ts
// ~/server/nitro/plug.ts
export default (nitroApp) => {
    nitroApp.h3App.use((event) => console.log('hello nitro')) // logs nothing
   
}
```
```ts
// nuxt.config.ts
export default defineNuxtConfig({
    nitro: {
        plugins: ['~/server/nitro/plug.ts']
    }
})
```

### Describe the bug

Nitro plugin h3App.use() isn't works

### Additional context

But simple h3app works!

```ts
import { createApp } from 'h3'
import { createServer } from 'http'

const app = createApp()
createServer(app).listen(process.env.PORT || 3000)

app.use((event) => console.log('hello'))  // logs 'hello'
```

I found this when i  want try to use `express-session` with h3 and nuxt3. 

```js 
import session from 'express-session'
export default async (_nitroApp) => { 
_nitroApp.h3App.use(session({}))
}
```

**Comment by 516310460** [comment] 2022-08-11 06:34
Maybe you should use `https://nitro.unjs.io/guide/storage.html#defining-mountpoints`

**Comment by modelair** [comment] 2022-08-11 09:14
@516310460 not looks like solution

**Comment by 516310460** [comment] 2022-08-11 09:15
There is no such document now, but I am not sure whether this function is experimental. I will submit a document later to see if it will be included

**Comment by 516310460** [comment] 2022-08-11 09:17
@danielroe @pi0
`nitro` is it experimental

**Comment by 516310460** [comment] 2022-08-11 09:49
@modelair  See link: https://github.com/nuxt/framework/pull/6507

**Comment by danielroe** [comment] 2022-08-11 09:56
The issue is that you are adding a route _after_ a catchall middleware (nuxt rendering) so it will never be hit.

This is similar to https://github.com/nuxt/framework/issues/5527 and perhaps there is a use case for adding middleware in the same way that you can now to `nitroApp.router.use('/some/route', handler)`.

**Comment by 516310460** [comment] 2022-08-11 09:57
> The issue is that you are adding a route _after_ a catchall middleware (nuxt rendering) so it will never be hit.
> 
> This is similar to #5527 and perhaps there is a use case for adding middleware in the same way that you can now to `nitroApp.router.use('/some/route', handler)`.

nitro is it experimental

**Comment by modelair** [comment] 2022-08-11 10:35
@danielroe thx for reply.  so, i can use ```express-session``` or some other express or connect middleware like this? 
```ts
nitroApp.router.use('/', expressSession({secret: 'mysecret-key'}))
```

is it a correct way?

**Closed** 2022-08-13 09:08 UTC
Labels: pending triage
