### ISSUE TITLE
production build issue with `date-fns`

### ISSUE THREAD

**Issue by Gyurmatag** [nuxt/framework#6495] opened 2022-08-10 19:18 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.6-27668034.5232c1b`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `buildModules`, `modules`, `intlify`, `css`, `colorMode`, `build`, `publicRuntimeConfig`, `meta`
- Runtime Modules:  `@nuxtjs/color-mode@3.1.4`
- Build Modules:    `@intlify/nuxt3@0.2.3`, `@pinia/nuxt@0.3.1`

### Reproduction

https://www.evgyuru.hu/
https://answers.netlify.com/t/this-function-has-crashed-but-i-have-no-netlify-functions/72053/9?u=gyurmatag
This repo is not working when deployed to Netlify
https://bitbucket.org/gyurmaland/nuxt-app/src/

### Describe the bug

I have a Nuxt site deployed to Netlify but for over 2 weeks the site can't be reached because it says the following:
<img width="890" alt="Képernyőfotó 2022-08-10 - 21 16 38" src="https://user-images.githubusercontent.com/22452368/184000813-c9baaebd-57c3-462e-b66f-1cec0cf4b016.png">

Here is my site live, so you can see it in action:
https://www.evgyuru.hu/
Also somebody from Netlify said that is a bug in Nuxt:
https://answers.netlify.com/t/this-function-has-crashed-but-i-have-no-netlify-functions/72053/9?u=gyurmatag
I provided the complete logs for this error.

### Logs

```shell
Aug 10, 09:11:29 PM: 93e58501 ERROR  [h3] [unhandled] H3Error: Directory import '/var/task/node_modules/date-fns/fp' is not supported resolving ES modules imported from /var/task/chunks/app/server.mjs
Did you mean to import date-fns/fp/index.js?
    at createError (file:///var/task/node_modules/h3/dist/index.mjs:238:15)
    at nodeHandler (file:///var/task/node_modules/h3/dist/index.mjs:428:21)
    at async ufetch (file:///var/task/node_modules/unenv/runtime/fetch/index.mjs:9:17)
    at async $fetchRaw2 (file:///var/task/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
    at async Object.errorhandler [as onError] (file:///var/task/chunks/nitro/aws-lambda.mjs:319:16)
    at async nodeHandler (file:///var/task/node_modules/h3/dist/index.mjs:436:9)
    at async ufetch (file:///var/task/node_modules/unenv/runtime/fetch/index.mjs:9:17)
    at async $fetchRaw2 (file:///var/task/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
    at async Object.errorhandler [as onError] (file:///var/task/chunks/nitro/aws-lambda.mjs:319:16)
    at async nodeHandler (file:///var/task/node_modules/h3/dist/index.mjs:436:9) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
```

**Comment by danielroe** [comment] 2022-08-10 20:53
@Gyurmatag Have you tried changing the import as the error message suggests?

**Comment by itzaks** [comment] 2022-08-10 23:09
Crashing here as well. Also timing out, seems to be remote async data that doesn't load properly when building on netlify. Happens both on Netlify and Vercel.

**Comment by danielroe** [comment] 2022-08-10 23:14
Please check whether [the edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/) resolves things for you, and if not, please do provide a minimal reproduction. 🙏

**Comment by itzaks** [comment] 2022-08-10 23:40
> Please check whether [the edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/) resolves things for you, and if not, please do provide a minimal reproduction. 🙏

Edge seems to solve the problem above. But introduces a new error.

````
[Debug] [vite] connected. (client, line 268)
[Error] SyntaxError: Importing binding name 'GraphQLClient' is not found.
	link
	linkAndEvaluateModule
````

**Comment by Gyurmatag** [comment] 2022-08-11 07:33
> @Gyurmatag Have you tried changing the import as the error message suggests?
> 
> Would you provide a minimal reproduction? 🙏

@danielroe I am on the edge channel, so the latest version of nuxt and the problem still persist. I can't provide a reproduction because the error is on Netlify only, on my machine it works fine. What should I do? Because my site is offline and it's very annoying...

**Comment by danielroe** [comment] 2022-08-11 07:53
You can provide a minimal repository that doesn't work when deployed.

**Comment by mwohlan** [comment] 2022-08-11 11:27
Can confirm the issue with netlify even with rc7. Gonna wait a bit for op to post a reproduction first.

**Comment by Mokkapps** [comment] 2022-08-12 15:57
I have the same problem with rc7 and rc8 (also edge). I saw this error in the Netlify logs of my function:

```
Aug 12, 04:11:04 PM: 703edbc4 ERROR  [nuxt] [request error] [unhandled] [500] Named export 'w3cwebsocket' not found. The requested module 'websocket' is a CommonJS module, which may not support all module.exports as named exports.
Aug 12, 04:11:04 PM: 703edbc4 ERROR  CommonJS modules can always be imported via the default export, for example using:
Aug 12, 04:11:04 PM: 703edbc4 ERROR  import pkg from 'websocket';
Aug 12, 04:11:04 PM: 703edbc4 ERROR  const { w3cwebsocket } = pkg;
Aug 12, 04:11:04 PM: 703edbc4 ERROR    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)  
Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)  
Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async Promise.all (index 0)  
Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)  
Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ./chunks/handlers/renderer.mjs:11089:24  
Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ./chunks/handlers/renderer.mjs:11143:64  
Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ./chunks/handlers/renderer.mjs:14:22  
Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ./node_modules/h3/dist/index.mjs:492:19  
Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async nodeHandler (./node_modules/h3/dist/index.mjs:438:7)  
Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async handler2 (./chunks/nitro/aws-lambda.mjs:4182:13)
```

**Comment by mwohlan** [comment] 2022-08-12 16:16
> I have the same problem with rc7 and rc8 (also edge). I saw this error in the Netlify logs of my function:
> 
> ```
> Aug 12, 04:11:04 PM: 703edbc4 ERROR  [nuxt] [request error] [unhandled] [500] Named export 'w3cwebsocket' not found. The requested module 'websocket' is a CommonJS module, which may not support all module.exports as named exports.
> Aug 12, 04:11:04 PM: 703edbc4 ERROR  CommonJS modules can always be imported via the default export, for example using:
> Aug 12, 04:11:04 PM: 703edbc4 ERROR  import pkg from 'websocket';
> Aug 12, 04:11:04 PM: 703edbc4 ERROR  const { w3cwebsocket } = pkg;
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async Promise.all (index 0)  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ./chunks/handlers/renderer.mjs:11089:24  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ./chunks/handlers/renderer.mjs:11143:64  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ./chunks/handlers/renderer.mjs:14:22  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ./node_modules/h3/dist/index.mjs:492:19  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async nodeHandler (./node_modules/h3/dist/index.mjs:438:7)  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async handler2 (./chunks/nitro/aws-lambda.mjs:4182:13)
> ```

Getting the same error

**Comment by matthewmaribojoc** [comment] 2022-08-13 03:35
> I have the same problem with rc7 and rc8 (also edge). I saw this error in the Netlify logs of my function:
> 
> ```
> Aug 12, 04:11:04 PM: 703edbc4 ERROR  [nuxt] [request error] [unhandled] [500] Named export 'w3cwebsocket' not found. The requested module 'websocket' is a CommonJS module, which may not support all module.exports as named exports.
> Aug 12, 04:11:04 PM: 703edbc4 ERROR  CommonJS modules can always be imported via the default export, for example using:
> Aug 12, 04:11:04 PM: 703edbc4 ERROR  import pkg from 'websocket';
> Aug 12, 04:11:04 PM: 703edbc4 ERROR  const { w3cwebsocket } = pkg;
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async Promise.all (index 0)  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ./chunks/handlers/renderer.mjs:11089:24  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ./chunks/handlers/renderer.mjs:11143:64  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ./chunks/handlers/renderer.mjs:14:22  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async ./node_modules/h3/dist/index.mjs:492:19  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async nodeHandler (./node_modules/h3/dist/index.mjs:438:7)  
> Aug 12, 04:11:04 PM: 703edbc4 ERROR    at async handler2 (./chunks/nitro/aws-lambda.mjs:4182:13)
> ```

Ran into the same problem with a Vercel build. Build runs fine, but function errored out. 

I was able to fix it adding `websocket` to `transpile`...
```
// nuxt.config.json
build: {
  transpile: ['websocket'],
},
```

Not sure the root cause, but I did get a new warning during the build that went away after the above "fix".

```
[start] [nitro] Building server...
23:20:28.210 | [warn] Multiple major versions of package debug are being externalized. Picking latest version.
23:20:28.210 | - /vercel/path0/node_modules/websocket/node_modules/debug@2.6.9
23:20:28.210 | - /vercel/path0/node_modules/debug@4.3.4
23:20:28.454 | [start] [nitro] Writing server bundle...
```

**Comment by geyermichael** [comment] 2022-08-13 05:07
Get a quite similar error on `build` and run `node .output/server/index.mjs` on local machine. After open `http://0.0.0.0:3000` following error message runs in a loop till `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`

```
[nuxt] [request error] [unhandled] [500] Named export 'w3cwebsocket' not found. The requested module 'websocket' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'websocket';
const { w3cwebsocket } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)  
  at async ./.output/server/chunks/handlers/renderer.mjs:11096:24  
  at async ./.output/server/chunks/handlers/renderer.mjs:11150:64  
  at async ./.output/server/chunks/handlers/renderer.mjs:14:22  
  at async ./.output/server/node_modules/h3/dist/index.mjs:492:19  
  at async Server.nodeHandler (./.output/server/node_modules/h3/dist/index.mjs:438:7)
```

My Nuxt project info:
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/supabase@0.1.19`, `@nuxtjs/tailwindcss@5.3.2`, `@pinia/nuxt@0.4.0`, `@vueuse/nuxt@9.1.0`
- Build Modules:    `-`

I do not get this error with RC6.

**Comment by Gyurmatag** [comment] 2022-08-13 18:32
@danielroe Finally I got a reproduction sorry for the late reply, but here it is:
https://bitbucket.org/gyurmaland/nuxt-app/src/
This is not working when deployed to Netlify. Can you please fix this very annoying problem?

**Comment by jonnyparris** [comment] 2022-08-14 07:43
this is also happening for Cloudflare Pages, and I can reproduce locally both with official release and on edge channel

**Comment by danielroe** [comment] 2022-08-14 08:30
cc: @pi0

**Comment by pi0** [comment] 2022-08-14 10:10
Hi, @Gyurmatag quickly checking your reproduction, it seems date-fns has externalization issues. I've saw similar issue couple of times seems a regression but in the meantime, you can use this as workaround and fix:


```js
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  nitro: {
    externals: {
      inline: ['date-fns']
    }
  }
})
```

Other issues for `w3cwebsocket` might be solved with similar workaround but reproduction would be nice 🙏🏼 

@jonnyparris Can you please provide a reproduction for cloudflare? Are are using `nuxt generate` or custom nitro preset?

**Comment by jonnyparris** [comment] 2022-08-14 10:18
@pi0 repro here: https://github.com/jonnyparris/bug-repro-nuxt3; using `nuxt generate`; no `date-fns`

**Comment by pi0** [comment] 2022-08-14 10:50
Thanks for repro @jonnyparris. I've made an upstream issue in `@nuxtjs/supabase` module with a similar quick fix (add `websocket` to `build.transpile`) for `w3cwebsocket` issue.

**Comment by Gyurmatag** [comment] 2022-08-14 10:55
@pi0 Thank you for the quick workaround. It works now. Waiting for the final fix!

**Comment by pi0** [comment] 2022-08-14 11:02
Happy hearing it fixed. To be honest it is tricky to fix all CommonJS-related issues. Nuxt 3 is fully ESM native and neither `date-fns` (tracker issue: https://github.com/date-fns/date-fns/issues/1781) and `vue3-date-picker` are ESM friendly.  

We made an extensive compatibility framework within [Nitro](https://github.com/unjs/nitro) and [unenv](https://github.com/unjs/unenv) for such libraries but unfortunately they will get broken from time to time.

Anyway I will try to see if we can make an improvement in nitro to fix this issue out of the box.

**Comment by Mokkapps** [comment] 2022-08-15 15:25
Thanks @pi0, the following workaround works for the deployed version:

```ts
  build: {
    transpile: ['websocket']
  }
```

But if I try to start it locally with `nuxi dev` then I receive this error:

```
[nuxt] [request error] [unhandled] [500] require is not defined in ES module scope, you can use import instead
  at $id_sEPSfxeQ04 (./.nuxt/dist/server/server.mjs:39984:1)  
  at __instantiateModule__ (./.nuxt/dist/server/server.mjs:56642:9)  
  at __ssrLoadModule__ (./.nuxt/dist/server/server.mjs:56580:25)  
  at ssrImport (./.nuxt/dist/server/server.mjs:56605:13)  
  at $id_976n4XWvUA (./.nuxt/dist/server/server.mjs:39623:37)  
  at __instantiateModule__ (./.nuxt/dist/server/server.mjs:56642:9)  
  at __ssrLoadModule__ (./.nuxt/dist/server/server.mjs:56580:25)  
  at ssrImport (./.nuxt/dist/server/server.mjs:56605:13)  
  at $id_gZLsYJZ6jg (./.nuxt/dist/server/server.mjs:39359:37)  
  at async __instantiateModule__ (./.nuxt/dist/server/server.mjs:56642:3)
```

Any idea how to fix this?

**Comment by matthewmaribojoc** [comment] 2022-08-15 15:28
I fixed it by adding conditional logic transpile based on env

``` js
build: {
    transpile: [process.env.NODE_ENV === 'production' ? 'websocket' : ''],
}
```

**Comment by Mokkapps** [comment] 2022-08-15 15:30
> @Mokkapps I fixed it by adding conditional logic transpile based on env
> 
> ```js
> build: {
>     transpile: [process.env.NODE_ENV === 'production' ? 'websocket' : ''],
> }
> ```

Perfect, that works! Thanks @matthewmaribojoc!

**Comment by pi0** [comment] 2022-08-15 15:30
What dependencies are you using @Mokkapps? A reproduction would be nice 🙏🏼 Since trying `build.transpile` on the one in https://github.com/nuxt/framework/issues/6495#issuecomment-1214328486, also seems fine for dev.

**Comment by larbish** [comment] 2022-08-16 10:16
Concerning this error with `websocket` when using the supabase module. It should be fixed in [v0.1.22](https://github.com/nuxt-community/supabase-module/releases/tag/v0.1.22) of the supabase module.

**Comment by danielroe** [comment] 2022-09-26 11:47
Let's track the more general issue in https://github.com/nuxt/framework/issues/7206.

**Closed** 2022-09-26 11:47 UTC
Labels: pending triage

**Comment by ozgurkisa** [comment] 2022-09-26 20:17
> ```js
> build: {
>     transpile: [process.env.NODE_ENV === 'production' ? 'websocket' : ''],
> }
> ```

Resolved my problem this: 

build: {
    transpile: [process.env.NODE_ENV === 'production' ? 'date-fns' : ''],
}
