### ISSUE TITLE
Allow modules to define nuxi commands

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/framework#7644] opened 2022-09-19 11:23 UTC
### Describe the feature

Currently, the list of nuxi commands is hard coded at
https://github.com/nuxt/framework/blob/2b57bfe36c7632e0379121559b31a153d1b80e35/packages/nuxi/src/cli.ts#L21
https://github.com/nuxt/framework/blob/2b57bfe36c7632e0379121559b31a153d1b80e35/packages/nuxi/src/commands/index.ts#L5-L24

However, for some modules it would be nice to add additional commands to nuxi. Essentially, this would make sense for every module that wraps around a cli which need vite (or nuxt) specific config. Examples are (although I'm sure there are more):
- `nuxi storybook build`: Build storybook (using config in `nuxt.config.ts` instead of the traditional storybook config). Refs https://github.com/nuxt-community/storybook/pull/385
- `nuxi vitest`: Run vitest (using nuxt-generated config instead of the traditional `vite.config.ts` file). Refs https://github.com/vitest-dev/vitest/issues/2044

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by pi0** [comment] 2022-09-19 11:25
This is duplicate of https://github.com/nuxt/framework/issues/4060

**Closed by pi0** 2022-09-19 11:25 UTC
Labels: pending triage

**Comment by tobiasdiez** [comment] 2022-09-19 11:32
You are right, sorrry for the noise, didn't found that other ticket it in my initial search.
