### ISSUE TITLE
Build output image path always show /__NUXT_BASE__/

### ISSUE THREAD

**Issue by huuhait** [nuxt/framework#2793] opened 2022-01-19 03:25 UTC
https://github.com/nuxt/framework/blob/c80870ad8c4a1c1b044d7a5ae27e41e997f8a75f/packages/vite/src/vite.ts#L53
but all image in /_nuxt/

**Comment by dungonfq** [comment] 2022-01-19 06:44
I'm facing the same issue. I'm so frustrated because all folders in public were copied wrongly to /_nuxt/ but empty

Why there are 2 folders img in .output ??
<img width="309" alt="Screen Shot 2022-01-19 at 1 42 53 PM" src="https://user-images.githubusercontent.com/57652048/150078184-e298b85c-d74b-4de7-ac5a-e6f6ffdc1145.png">

**Comment by danielroe** [comment] 2022-01-19 07:35
Would you provide a reproduction please? :pray:

**Comment by dungonfq** [comment] 2022-01-19 09:51
Hi @danielroe , for my case:

1. I created `/public/img` folder to store all my project logos & icons
<img width="266" alt="Screen Shot 2022-01-19 at 4 44 25 PM" src="https://user-images.githubusercontent.com/57652048/150106512-9ba43774-261f-4042-bba6-b588bbaeb193.png">

2. I run `nuxi build` then `nuxi preview`:
- All images were served on URL '/_nuxt/img/icons/xxx.svg' which causes 404 error
- `.output` folder generated 2 `img` folders:

-- 1st one is in `_nuxt` but it's emty => this cause 404 error
<img width="261" alt="Screen Shot 2022-01-19 at 4 45 58 PM" src="https://user-images.githubusercontent.com/57652048/150106404-9e49a593-4757-44a1-a60b-0e857b1d02fd.png">

-- 2nd one is in `.output` directly, all my public files were copied here instead in `_nuxt` folder
<img width="269" alt="Screen Shot 2022-01-19 at 4 46 07 PM" src="https://user-images.githubusercontent.com/57652048/150106439-a111e86d-2beb-45fa-be8b-42ecb5d3c7df.png">

3. Then I tried to disabled Vite (I'm using Nuxt 3) in `nuxt.config.js`, Webpack built and served those images normally.

Seem like the error came from ViteJs?

**Comment by danielroe** [comment] 2022-01-19 10:00
@dungonfq This is likely a consequence of https://github.com/nuxt/framework/pull/2655. Could you create a demo repro or use https://stackblitz.com/github/nuxt/starter/tree/v3?terminal=dev?

**Comment by dungonfq** [comment] 2022-01-19 11:14
Thank @danielroe, here's my repo: https://github.com/dungonfq/nuxt3

Step to reproduce:
1. `npm run build`
2. `npm run start` OR `npm run preview`

If the logo doesn't appear => u reproduced my error successfully 😎
<img width="436" alt="Screen Shot 2022-01-19 at 6 01 15 PM" src="https://user-images.githubusercontent.com/57652048/150118791-026ac0dc-f32c-4030-91fe-8a6d271486b1.png">

**Comment by danielroe** [comment] 2022-01-19 11:24
I believe it's fixed in a newer version. Would you try running `npx nuxi upgrade`?

**Comment by dungonfq** [comment] 2022-01-19 11:34
`npx nuxi upgrade` worked for me. Now the image loaded as expected, without the prefix `/_nuxt/`

<img width="1440" alt="Screen Shot 2022-01-19 at 6 32 10 PM" src="https://user-images.githubusercontent.com/57652048/150122077-a56accaf-2146-482d-ae8b-452d3ea69a5c.png">

🙌🏻 U save my day, thank a lot @danielroe

**Comment by danielroe** [comment] 2022-01-19 11:44
Glad that's resolved @dungonfq!

I suspect @huuhait's original issue is the same as https://github.com/nuxt/framework/issues/2777, so I'll close to track there. But if not, just let me know and I'll reopen. 🙏

**Closed by danielroe** 2022-01-19 11:44 UTC
Labels: vite, nuxt3, needs reproduction, pending triage
