### ISSUE TITLE
Page Title Meta Tags "Page Not Found | Nuxt"

### ISSUE THREAD

**Issue by niyonx** [nuxt/framework#5722] opened 2022-07-04 22:39 UTC
### Versions

- nuxt: 3.0.0-rc.1
- node: v16.15.0

### Reproduction

Configure nuxt.config.ts the title of the website.

```
app: {
      head: {
        title: 'Custom title',
        meta: [
          // <!-- Primary Meta Tags -->
          { name: 'viewport', content: 'width=device-width, initial-scale=1' },
          {
            name: 'title',
            content: 'Custom title'
          },
          // <!-- Open Graph / Facebook -->
          {
            property: 'og:title',
            content: 'Custom title'
          },
          // <!-- Twitter -->
          {
            property: 'twitter:title',
            content: 'Custom title'
          },
        ],
      }
    }
```

The title will display well on the page. However, when bots load the preview, it will display "500 - Page Not Found | Nuxt". As you can see in metatags.io with the website merchant.pikapoint.io.

### What is Expected?

It should display the proper title.

### What is actually happening?

Does not display the proper title

**Comment by danielroe** [comment] 2022-07-04 22:43
Would you provide a reproduction please? 🙏

**Comment by niyonx** [comment] 2022-07-08 14:17
Hi @danielroe, you can reproduce by changing the nuxt.config.ts and adding the head title as the code snippet above. Please let me know if you are able to reproduce, thank you

**Comment by danielroe** [comment] 2022-07-08 14:26
The reason I asked for one is that I cannot reproduce with the information you've given me so far.

**Comment by danielroe** [comment] 2022-07-11 11:58
Thanks! I'm closing the issue in the interim but please feel free to comment whenever you can reproduce and I'll happily reopen it 😊

**Closed by danielroe** 2022-07-11 11:58 UTC
Labels: needs reproduction, pending triage
