### ISSUE TITLE
Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

### ISSUE THREAD

**Issue by lihanspace** [nuxt/framework#5432] opened 2022-06-13 03:09 UTC
I found where the error occurred.

```bash
npx nuxi init nuxt3-error

cd nuxt3-error
yarn install

yarn add -D sass
```

```ts [nuxt.config.ts]
// nuxt.config.ts
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  postcss: {
    plugins: {
      cssnano: {},
    },
  },
})
```

```vue [app.vue]
// app.vue
<template>
  <div>
    <NuxtWelcome />
  </div>
</template>

<style lang="scss" scoped>
.box1 {
  background-image: url("./assets/img/img.png");
  .t0:after {
    content: 'h';
  }
}
</style>
```

```bash
yarn build
```

Then you can see the console output ` ERROR  Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.` error message.

The path being processed by `vite:import-analysis` is `D:/work/code/web/pc/nuxt3-error/app.vue?vue&type=style&index=0&scoped=true&lang.scss`

_Originally posted by @lihanspace in https://github.com/nuxt/framework/discussions/5317#discussioncomment-2935125_

**Comment by danielroe** [comment] 2022-06-15 09:27
This should be resolved in rc4 with https://github.com/nuxt/framework/pull/5409 - I could not reproduce using latest rc. Let me know if not and we can reopen.

**Closed by danielroe** 2022-06-15 09:27 UTC
