### ISSUE TITLE
[worker] definePageMeta is not defined    

### ISSUE THREAD

**Issue by Moskovskiy** [nuxt/framework#2920] opened 2022-01-26 00:41 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27385496.7a1cf62`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `head`, `css`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/hardcore-grass-965dh?file=/pages/index.vue

### Describe the bug

Instructions from official Nuxt3 tutorial can't be executed
![image](https://user-images.githubusercontent.com/33791294/151083149-179a466c-1c12-4175-859b-c5d17e9f641f.png)

### Additional context

Check out this topic: https://github.com/nuxt/framework/discussions/2770

Any of flows:
1. Having 'pages' folder and no lock.json/node_modules -> installing -> running (after clone)
2. Having 'pages' folder, deleting lock.json/node_modules -> installing -> running
3. Having no pages folder (e.g no vue-router) 
will result in lack of definePageMeta

In this example I use definePageMeta for middleware, but it doesn't depend on it (this is not the source of the error)
I do get the following warning though:

[Vue warn]: Unhandled error during execution of setup function 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined >  key="/some_page" >
definePageMeta is not defined
  at setup (file://./.nuxt/dist/server/server.mjs:11102:1)  

### Logs

```shell
ERROR  [worker] definePageMeta is not defined                                                                          

  at setup (.nuxt/dist/server/server.mjs:11102:1)
  at _sfc_main.setup (.nuxt/dist/server/server.mjs:11491:23)
  at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6621:22)
  at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6247:29)
  at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6203:11)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)
  at renderVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)
  at renderVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:17)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
```

**Comment by Moskovskiy** [comment] 2022-01-26 00:46
Plausible solution is listed in this answer: https://github.com/nuxt/framework/discussions/2770#discussioncomment-2005938, yet I was not able to execute it on nuxt3:latest

**Comment by Oldwo1f** [comment] 2022-01-26 00:50
For me it with Layout.
`<script setup>
	definePageMeta({
  layout: "secondary"
});`


and i get the following error in chrome console

``client.js?06a0:101 ReferenceError: definePageMeta is not defined
    at __sfc_main.setup (_id.vue?21cd:27)
    at mergedSetupFn (vue-composition-api.mjs?ed09:2118)
    at eval (vue-composition-api.mjs?ed09:1930)
    at activateCurrentInstance (vue-composition-api.mjs?ed09:1845)
    at initSetup (vue-composition-api.mjs?ed09:1928)
    at VueComponent.wrappedData (vue-composition-api.mjs?ed09:1911)
    at getData (vue.runtime.esm.js?2b0e:4761)
    at initData (vue.runtime.esm.js?2b0e:4717)
    at initState (vue.runtime.esm.js?2b0e:4655)
    at VueComponent.Vue._init (vue.runtime.esm.js?2b0e:5020)``

**Comment by franzus5** [comment] 2022-01-26 07:58
@Moskovskiy #2914 same problem here

**Comment by danielroe** [comment] 2022-01-26 09:44
This codesandbox is working for me as far as the `definePageMeta is not defined` error - though note that codesandbox seems to be a bit glitchy right now with the CF protection it has in place.

@Oldwo1f - `definePageMeta` won't work in anywhere but in `pages/` - it's tightly coupled to Vue Router. And it's also not a feature usable in Nuxt Bridge.

**Comment by Moskovskiy** [comment] 2022-01-26 10:23
Apparently this has to do something with the following warning

`Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
`
I'm currently investigating it

**Comment by Oldwo1f** [comment] 2022-01-26 10:23
Ok i see. I am indeed using nuxt bridge.
Is there any work around to change page meta like pageTransition or layout
Note that i am now using the <script setup></script>

**Comment by Oldwo1f** [comment] 2022-02-08 04:30
hi there. i am back to this topic.

I really need to use more than one layout on my nuxt-bridge app.

Since definePageMeta is not working in nuxt bridge, I wonder if anyone have a work around.

**Comment by Oldwo1f** [comment] 2022-02-08 04:31
Reproduction is kinda easy to create.
- create a new nuxt-bridge app by following the documentation.
- create a new page in the page folder and copy this inside the file.

**Comment by danielroe** [comment] 2022-02-08 07:17
@Oldwo1f In Nuxt Bridge, you still set the layout the same way you always have. You can create a second script block just to do this.

**Comment by danielroe** [comment] 2022-02-08 12:47
@Moskovskiy I can't replicate even with the codesandbox - it appears to be working fine. Would you update the reproduction so it fails? Or create a GitHub repository and share the code with me?

I would suggest deleting your `node_modules/.vite` and `node_modules/.cache` folders. Also try upgrading with `npx nuxi upgrade --force`.

**Comment by Oldwo1f** [comment] 2022-02-08 18:45
> @Oldwo1f In Nuxt Bridge, you still set the layout the same way you always have. You can create a second script block just to do this.


This is working like a charm.
Thank you very much budy

**Comment by eden** [comment] 2022-02-11 17:23
> I would suggest deleting your `node_modules/.vite` and `node_modules/.cache` folders. Also try upgrading with `npx nuxi upgrade --force`.

I encountered this issue in my project, but completely removing `node_modules` and reinstalling from NPM from scratch fixed everything.

**Comment by danielroe** [comment] 2022-02-11 17:26
I'm going to close this issue. We've implemented a helper in Nuxi to clear the vite cache (which was the likely culprit) automatically on upgrade.

If anyone experiences this in future, even after trying the steps above, please create a new issue with a reproduction.

**Closed by danielroe** 2022-02-11 17:26 UTC
Labels: nuxt3, needs reproduction, pending triage

**Comment by wesley-spencer** [comment] 2022-02-22 18:45
"@nuxt/bridge": "npm:@nuxt/bridge-edge@^3.0.0-27406801.569aaeb",
What do I use? 
useMeta, useNuxt2Meta, or definePageMeta

Also how do I use the correct one with middleware?

Currently trying to convert Options API to Composition API 
OPTIONS API
`
export default {
  middleware: ["checkRole"],
  meta: {
    roles: ["role_1"],
  },
}
`
COMPOSITION API
`
useMeta({
  title: "TITLE OF PAGE",
  middleware: [ "checkRole" ],
  meta:{ roles: [ "role_1", "role_2" ] }
})
`
