### ISSUE TITLE
build Error：Could not resolve './use-prevent-globalThis' from ./use-prevent-globalThis?commonjs-external

### ISSUE THREAD

**Issue by hlbj105** [nuxt/framework#1006] opened 2021-10-14 08:03 UTC
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3-3.0.0-27235989.d52b1e8`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `meta`, `alias`, `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

build error 
`Could not resolve './use-prevent-globalThis' from ./use-prevent-globalThis?commonjs-external  `

![image](https://user-images.githubusercontent.com/16408650/137275969-f6658ad3-c7a5-4bf3-a3d1-94169a956f60.png)

### Reproduction

https://github.com/element-plus/element-plus-nuxt-starter
这个项目在我这边build也报同样错误

**Comment by keithchin** [comment] 2021-10-14 09:00
Same issue here. 

<img width="447" alt="Screenshot 2021-10-14 at 4 59 59 PM" src="https://user-images.githubusercontent.com/13880871/137285766-2a2f2ad6-1e51-45fd-b3df-0603c4c0e7fd.png">

**Comment by YunYouJun** [comment] 2021-11-09 09:47
Nuxt build seems add `-globalThis` for `use-prevent`.

**Comment by andoshin11** [comment] 2021-11-09 10:00
Found out that it's caused by Vite & [Element Plus](https://github.com/element-plus/element-plus).

As described in [here](https://github.com/vitejs/vite/issues/4796), Vite does try to convert a word `global` into `globalThis`, thus it affects a critical import statement inside Element Plus show belo.

https://github.com/element-plus/element-plus/blob/66043aa3b56ecdf2f19b03c463d081800cd51c35/packages/hooks/index.ts#L9

**Comment by danielroe** [comment] 2021-11-09 11:59
closing in favour of https://github.com/nuxt/framework/issues/1713

**Closed by danielroe** 2021-11-09 11:59 UTC
Labels: bug, nuxt3

**Comment by nachtfunke** [comment] 2021-11-09 13:59
> Found out it's caused by Vite & [Element Plus](https://github.com/element-plus/element-plus).
> 
> As described in [here](https://github.com/vitejs/vite/issues/4796), Vite does try to convert a word `global` into `globalThis`, thus it affects a critical import statement inside Element Plus show below.
> 
> https://github.com/element-plus/element-plus/blob/66043aa3b56ecdf2f19b03c463d081800cd51c35/packages/hooks/index.ts#L9

Does that mean, renaming the file in question to anything but "global" might fix the issue? I have the same issue, but with a sass file.
