### ISSUE TITLE
[DOCS] NuxtLayout warn vs documentation

### ISSUE THREAD

**Issue by Triloworld** [nuxt/framework#8416] opened 2022-10-23 08:38 UTC
### Environment

Oficial page - https://v3.nuxtjs.org/api/components/nuxt-layout
Local env is:
> Nuxt 3.0.0-rc.12 with Nitro 0.6.0

### Reproduction

https://v3.nuxtjs.org/api/components/nuxt-layout

### Describe the bug

App.vue have issue on declared way to use layouts:

> You can use <NuxtLayout /> component to activate default layout on **_app.vue_** or error.vue.

And in app get this message: 

` WARN  Using <NuxtLayout> inside app.vue will cause unwanted layout shifting in your application.Consider removing <NuxtLayout> from app.vue and using it in your pages.`

### Additional context

`App.vue`
```js
<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>
```

**Comment by danielroe** [comment] 2022-10-23 12:54
This warning comes from `nuxt/content`. The issue is an upstream one and should be resolved when https://github.com/vuejs/core/pull/6736 is merged.

**Closed by danielroe** 2022-10-23 12:54 UTC
Labels: pending triage
