### ISSUE TITLE
allow manually redirecting to 404 route within a dynamic slug

### ISSUE THREAD

**Issue by misaon** [nuxt/framework#4520] opened 2022-04-22 07:35 UTC
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-yyumyt?file=pages/404.vue

### Describe the bug

I have defined three pages (routes):
- `car.vue`
- `[slug].vue`
- `404.vue`

If I go to `http://.../hi` => it loads `[slug].vue` => **OK**
If I go to `http://.../car` => it loads `car.vue` => **OK**
If I go to `http://.../404` => it loads `[slug].vue` => **FAIL**

**Comment by danielroe** [comment] 2022-04-22 08:05
`404.vue` is a special route that handles otherwise unmatched routes: see https://v3.nuxtjs.org/guide/directory-structure/pages#catch-all-route.

**Comment by misaon** [comment] 2022-04-22 08:09
If I have logic in setup inside [slug].vue where I call useFetch and the api returns 404, I would like to redirect to the /404 route which is not possible now.

**Comment by misaon** [comment] 2022-04-22 08:17
@danielroe Example: I have a bike shop. A customer accesses the route: http//bike.com => index.vue. The customer wants to view the bike categories http://bike.com/blue-bikes => [slug].vue. The customer selects one of the bikes from the category, http://bike.com/best-blue-bike.html => [slug].html.vue. Everything works great, but how do I catch the condition where I want to redirect to a 404 page?

**Comment by danielroe** [comment] 2022-04-22 08:18
> which is not possible now.

Are you saying this used to work? Would you provide an example of what you're wanting to do?

(I'm asking as this is a key behaviour and we need to make this as straightforward as we can, so we either need to improve DX or document some examples.)

**Comment by Aareksio** [comment] 2022-04-22 14:25
I am positive the broad idea of this issue is to ask "how to handle 404 on dynamic path".

```js
  const $route = useRoute()
  const { data } = await useAsyncData(`product:${$route.params.id}`, () => $fetch(`/api/products/${$route.params.id}`))

  // TODO: Display proper 404 when accessing unknown product id
  // Requirements:
  // - Using default error page - big "404" with small "Page not found: /42" - just like native nuxt 404
  // - On all types of navigation:
  //   a) Home -> Product/42 (client)
  //   b) Home -> Product/42 -> Home -> Product/42 (client + cache)
  //   c) Product/42 (server)
  //   d) Product/42 -> Home -> Product/42 (server into client + cache)
  // - Proper status code and status message when SSR (404, Not Found)
  ```

There is currently no documentation on how to properly handle API's 404 response in the docs. From my experience it is also extremely hard, as all of the 4 navigation types listed in comments above require different logic each.

**Comment by danielroe** [comment] 2022-04-22 15:58
Thanks for that link @Aareksio.

I've submitted a related PR to fix an issue, add some basic docs and improve DX (by avoiding import of `createError`), but check out https://stackblitz.com/edit/github-jwfbey. Does that answer your questions?

**Comment by Aareksio** [comment] 2022-04-22 16:30
You got around checking for 404 in pretty clever way @danielroe! 

This surely answers on how to display 404 when the server returns an error, but we may need different handling for different kind of errors, eg. 5xx, 403, 429 all should stay on the path and return specific status codes. In all cases, the `data` will be empty and with demonstrated approach we'll end up sending 404. This may signal crawler bots to delist URL despite the real cause being server malfunction or rate limit. Here's rebuilt example covering error code: https://stackblitz.com/edit/github-jwfbey-kyfof4

I think your solution answers this particular issue, as the OP didn't seem to be concerned with proper status code.

**Comment by Allypost** [comment] 2022-05-22 21:54
@danielroe Even with your fix, when using SSR the backend still throws internal an error (and flashes it until the hidration takes over):
```
[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable
    at Module.useNuxtApp (file:///home/projects/nuxt-starter-nlacpe/.nuxt/dist/server/server.mjs:416:13)
    at Module.clearError (file:///home/projects/nuxt-starter-nlacpe/.nuxt/dist/server/server.mjs:1004:41)
    at eval (file:///home/projects/nuxt-starter-nlacpe/.nuxt/dist/server/server.mjs:3106:33)
    at triggerAfterEach (/home/projects/nuxt-starter-nlacpe/node_modules/vue-router/dist/vue-router.cjs.js:3156:13)
    at eval (/home/projects/nuxt-starter-nlacpe/node_modules/vue-router/dist/vue-router.cjs.js:3059:13)
    at async eval (file:///home/projects/nuxt-starter-nlacpe/.nuxt/dist/server/server.mjs:2584:7)
    at async createNuxtAppServer (file:///home/projects/nuxt-starter-nlacpe/.nuxt/dist/server/server.mjs:60:7)
    at async Object.renderToString (file:///home/projects/nuxt-starter-nlacpe/node_modules/vue-bundle-renderer/dist/index.mjs:277:19)
    at async eval (file:///home/projects/nuxt-starter-nlacpe/.nuxt/dev/index.mjs:476:20)
    at async eval (file:///home/projects/nuxt-starter-nlacpe/node_modules/h3/dist/index.mjs:475:19)
```
It's visible in the logs of the example you provided, but here's a minimal example nontheless: [https://stackblitz.com/edit/nuxt-starter-nlacpe](https://stackblitz.com/edit/nuxt-starter-nlacpe?file=plugins%2Frouter.fix.ts,pages%2Findex.vue)

https://user-images.githubusercontent.com/5151543/169717529-9f1a377b-30d9-4466-b576-bab9ffa550ff.mp4

The error is thrown whenever `throwError` is used after an `await` in the setup function

**Comment by AndersNielsen85** [comment] 2022-08-16 09:45
@danielroe the throwError seems to be marked as deprecated now.

Swapping for throw createError seems to output fails in the server console "[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable

```
if (!data.value) {
  throw createError({ statusCode: 404, statusMessage: 'Page Not Found' })
}

**Comment by danielroe** [comment] 2022-08-16 10:07
Seems working fine on latest RC8 to me, without any workarounds: https://stackblitz.com/edit/nuxt-starter-fbuud2. Let me know if not and I'll reopen.

**Closed by danielroe** 2022-08-16 10:07 UTC
Labels: enhancement, dx

**Comment by AndersNielsen85** [comment] 2022-08-16 10:42
@danielroe indeed it works on the initial "faulty" load.

It seems to me it is failing if I am doing some clientside navigation to something faulty though.
So navigating from index to test404
https://stackblitz.com/edit/nuxt-starter-mdhxps?file=pages/index.vue

Is just a limitation to be aware of, or should it be working?

**Comment by danielroe** [comment] 2022-08-16 10:48
We deliberately don't throw a full page error in this case by default. If you want that, you can add `fatal: true` to the options of `createError`.

**Comment by some-user123** [comment] 2022-08-23 19:46
I'm having a related problem rendering a 404 error:

```html
<!-- test404.vue -->
<template>
  <div>Content: {{ data.id }}</div>
</template>

<script lang="ts">
export default defineComponent({
  async setup() {
    const { data, error } = await useAsyncData<{ id: number }>(async () => {
      // URL returns 404, causing fetch to throw an error
      return await $fetch('https://run.mocky.io/v3/b764d683-f7cd-4128-9de0-077d891d3886')
    })
    if (error.value) {
      console.log('error detected')
      throw createError({
        statusCode: 404,
        fatal: true,
      })
    }

    return { data }
  },
})
</script>
```

The console shows:
```
error detected
[Vue warn]: Unhandled error during execution of setup function
  at <Test404 onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >
[Vue warn]: Property "data" was accessed during render but is not defined on instance.
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'id')
```

So, instead of 404, a 500 error is rendered, because the template is trying to access a property of `undefined` (`data.id`). It works (404 rendered) if I remove `data.id` from the template.
Is this the intended behavior?

I'd like to avoid to wrap my whole template into a `<div v-if="data"></div>` as the template should not be rendered at all (I'm throwing an exception even before the `return`) and I'm using `useAsyncData` instead of `useLazyAsyncData` to not have to handle the empty data situation in the template.

**Comment by Aareksio** [comment] 2022-08-23 21:18
Minimal reproduction for the above, using script setup for readability: https://stackblitz.com/edit/github-5jhffm

**Comment by Aareksio** [comment] 2022-08-23 21:39
@danielroe I am afraid the error handling of API responses is still not perfect. This time no shortcuts, need to handle **both** 404 and 500 properly (read error value): https://stackblitz.com/edit/github-cmeky2?file=pages/movie/[id].vue

**Comment by danielroe** [comment] 2022-08-24 09:09
@Aareksio This seems to work for me. As far as retrying requests in certain conditions, you can provide an `onResponseError` callback in `$fetch` options for more fine grained handling of issues.

```js
const { data: movie, error } = await useAsyncData(`movie:${$route.params.id}`, () => $fetch(`/api/movie/${$route.params.id}`));

if (error.value && error.value.response) {
  throw createError({
    fatal: true,
    statusCode: error.value.response.status
  })
}
```

Please feel free to open a feature request if you think something is missing. Though do note that this overlaps slightly with https://github.com/nuxt/framework/issues/2122, which I think is a valid issue we need to improve.

**Comment by Aareksio** [comment] 2022-08-24 09:48
@danielroe https://yko.im/1_it.mp4
Shall I open issue for this, or #2122 already covers this?

Case b: Home -> Movie/[id] -> Home -> Movie/[id] (client + cache)
And also new case: Movie/[id] -> Home -> Movie/[id] -> Home -> Movie/[id] (ssr + client + cache)

Breaks after repetitive visit after client request.

**Comment by danielroe** [comment] 2022-08-24 10:09
Agreed - I think it does make sense to add more caching strategies.

**Comment by danielroe** [comment] 2022-08-24 10:25
Created two issues to follow:

* https://github.com/nuxt/framework/issues/6899
* https://github.com/nuxt/framework/issues/6900

Feel free to open a new one if you think there's another one to track.

**Comment by some-user123** [comment] 2022-08-24 10:33
> Minimal reproduction for the above, using script setup for readability: https://stackblitz.com/edit/github-5jhffm

Should I open a separate issue for that?
