### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by marckent04** [nuxt/framework#940] opened 2021-10-13 12:18 UTC
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3-3.0.0-27234503.d5127e9`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

![image](https://user-images.githubusercontent.com/36090455/137129129-485213f7-b67a-4cc1-8edc-a2d25418e5ce.png)

When i install Element Plus it's the error that i see

### Reproduction

https://github.com/marckent04/nuxt3-first-app/tree/frontend

**Comment by matthewpull** [comment] 2021-10-13 17:27
I think this is a duplicate of #858

**Comment by wobsoriano** [comment] 2021-10-14 08:37
I'm currently creating a nuxt plugin and got the same error. To fix it I added it to the list of deps prevented from being externalized for SSR.

```ts
import {
  defineNuxtModule,
  addPlugin,
  extendViteConfig
} from '@nuxt/kit';
import { resolve } from 'path';

export default defineNuxtModule({
  name: 'nuxt3-module',
  configKey: 'options',
  setup(options) {
    addPlugin({
      src: resolve(__dirname, './plugin.mjs')
    });

    extendViteConfig((config) => {
      // @ts-expect-error: vite
      config.ssr = {
        noExternal: [
          'some-module',
        ]
      };
    });
  }
});
```

**Comment by Akryum** [comment] 2021-11-04 10:02
https://codesandbox.io/s/fervent-roman-0dhv2

**Comment by danielroe** [comment] 2021-11-04 13:05
@Akryum The issue is that `v-tooltip/dist/v-tooltip.esm.js` isn't a valid Node import, and there is also a similar issue with `'@popperjs/core`. The workaround is:

```js
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  build: {
    transpile: ['@popperjs/core', 'v-tooltip']
  }
})
```

I'm looking to improve our documentation on this - I've just submitted a PR with more info (https://github.com/nuxt/framework/pull/1694), and you can read the rendered draft [here](https://deploy-preview-1694--nuxt3-docs.netlify.app/concepts/esm). I'd really value your feedback on the guide, particularly from a library author point of view.

**Comment by productdevbook** [comment] 2021-11-04 13:32
@danielroe https://github.com/productdevbook/productdevbook.com some problem, transpile test local but dont fixed

**Comment by danielroe** [comment] 2021-11-04 13:56
@productdevbook You might need also to transpile the packages that are being imported by the package you've added to transpile. I've created a PR to help expose which packages they are: #1696.

**Comment by Akryum** [comment] 2021-11-04 14:39
Would it be possible for Nuxt to auto-transpile the ES packages not recognized by node?

**Comment by danielroe** [comment] 2021-11-04 14:49
@Akryum Yes, it is possible to an extent, and we do it:

https://github.com/nuxt/framework/blob/main/packages/vite/src/dev-bundler.ts#L46
https://github.com/unjs/externality/blob/main/src/externals.ts#L109
https://github.com/unjs/mlly/blob/main/src/syntax.ts#L50

But what we aren't currently doing is looking at the dependencies that _those_ packages are importing (ie. building a dependency tree). It would be possible but would result in a lot more fs access...

**Comment by Akryum** [comment] 2021-11-04 14:56
Or maybe add the dependency to transpile when the error occurs?

**Closed** 2021-11-04 23:24 UTC
Labels: bug, nuxt3
