### ISSUE TITLE
Vite problem with ufo when creating new project

### ISSUE THREAD

**Issue by MonoPT** [nuxt/framework#9110] opened 2022-11-17 09:24 UTC
When creating a new project and starting it, it throws this error:
[vite-node] [ERR_INVALID_URL_SCHEME] /node_modules/ufo/dist/index.mjs

at /node_modules/ufo/dist/index.mjs

Haven´t done anything except following the document installation process for nuxt 3.0

**Comment by danielroe** [comment] 2022-11-17 10:10
Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by manLuke** [comment] 2022-11-17 10:17
Same problem when creating a new project.

**Comment by leo91000** [comment] 2022-11-17 10:22
@manLuke @MonoPT 
I had this problem with pnpm without shamefully hoist.
Could this be the same issue ?

**Comment by manLuke** [comment] 2022-11-17 10:28
@leo91000 
I use yarn. This is my environment: 
```- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-````

**Comment by leo91000** [comment] 2022-11-17 10:55
Okay then this is not related sorry.

**Comment by manLuke** [comment] 2022-11-17 11:53
Duplicate of #9074

**Closed** 2022-11-17 12:39 UTC
Labels: needs reproduction, pending triage
