### ISSUE TITLE
Plugin with nuxtApp.hook('app:created') breaks event hooks in Vue

### ISSUE THREAD

**Issue by Tech-Non** [nuxt/framework#6976] opened 2022-08-26 13:22 UTC
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.17.5`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@6.14.14`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I have written the following Code in a plugins/getFileLinks.ts File and added a button in a .vue component with a function that just does `console.log('hi')`:
```
import fs from 'fs'
import path from 'path'

export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.hook('app:created', () => {
        let creationData = {}
        // iterate over files in data folder
        fs.readdirSync(path.resolve('./data')).forEach(file => {
            // get file extension
            const ext = path.extname(file)
            // if file is .md, add to database
            if (ext === '.md') {
                // read yaml frontmatter from markdown file
                const content = fs.readFileSync(path.resolve(`./data/${file}`), 'utf8')
                const yaml = content.split('---')[1]
                if (yaml) {
                    let type = yaml.split('Type: ')[0].replace(/\n/g, '').replace(/\r/g, '')
                    // remove trailing newline characters from type
                    creationData[file.replace('.md', '')] = type
                }
            }
        })
        // write creationData to json file
        fs.writeFileSync(path.resolve('./creationData.json'), JSON.stringify(creationData))
    })
})
```

### Describe the bug

In doing so I don't get a console.log output anymore, or basically any event hooks cease working to my understanding

### Logs

```shell
There is no error output or anything happening in neither the terminal nor the browser console
```

**Comment by danielroe** [comment] 2022-08-30 13:49
The error is caused by having no `fs` access on client.

This issue (of no error message) has been resolved via https://github.com/nuxt/framework/pull/6389 and is present on the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/).

**Closed by danielroe** 2022-08-30 13:49 UTC
Labels: pending triage
