### ISSUE TITLE
Tailwindcss 3 loading after 500ms-1sec

### ISSUE THREAD

**Issue by binods-gintaa** [nuxt/framework#3018] opened 2022-02-01 07:33 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `pwa`, `build`, `env`, `firebase`, `analytics`, `remoteConfig`, `tailwindcss`, `alias`, `bridge`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/firebase@8.2.2`
- Build Modules:    `@nuxt/postcss8@1.1.3`, `@nuxt/bridge@3.0.0-27389502.88da719`

### Reproduction

Configure tailwind css 3 with nuxt bridge project
[https://tailwindcss.com/docs/guides/nuxtjs](tailwindcss)

Then simply run `yarn dev`

### Describe the bug

Tailwind css 3 with nuxt bridge
Loading after 1 second
It is occurring for build as well as dev time

### Additional context
`
// nuxt.config.js

import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  // bridge: false,
  
  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: 'gintaa-web-app-nuxt',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
      { name: 'format-detection', content: 'telephone=no' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },

  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [
    '@/assets/css/main.css',
  ],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [
  ],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    // https://go.nuxtjs.dev/tailwindcss
    // '@nuxtjs/tailwindcss'
    '@nuxt/postcss8'
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    // https://go.nuxtjs.dev/pwa
    // '@nuxtjs/pwa',
    '@nuxtjs/firebase'
  ],

  // Axios module configuration: https://go.nuxtjs.dev/config-axios
  axios: {
    // Workaround to avoid enforcing hard-coded localhost:3000: https://github.com/nuxt-community/axios-module/issues/308
    baseURL: 'https://dev.api.gintaa.com/'
  },

  // PWA module configuration: https://go.nuxtjs.dev/pwa
  pwa: {
    manifest: {
      lang: 'en'
    }
  },

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    postcss: {
      plugins: {
        tailwindcss: {},
        autoprefixer: {},
      },
    },
  },

  env: {
    FIRE_ENV: process.env.NODE_ENV
  },
  firebase: {
    config: {
      development: {
        apiKey: '***',
        authDomain: '***',
        databaseURL: '***',
        projectId: '***',
        storageBucket: '***',
        messagingSenderId: '***',
        appId: '***',
        measurementId: '***',
      },
      alpha: {
        apiKey: '***',
        authDomain: '***',
        databaseURL: '***',
        projectId: '***',
        storageBucket: '***',
        messagingSenderId: '***',
        appId: '***',
        measurementId: '***',
      }
    },
    services: {
      auth: true,
      firestore: true,
      functions: true,
      storage: true,
      database: true,
      messaging: true,
      performance: true,
      analytics: true,
      remoteConfig: true
    }
  },
  analytics: {
    collectionEnabled: true // default
  },
  remoteConfig: {
    settings: {
      fetchTimeoutMillis: 60000, // default
      minimumFetchIntervalMillis: 43200000 // default
    },
    defaultConfig: {
      // 'welcome_message': 'Welcome'
    }
  },

  tailwindcss: {
    viewer: false
  },
  alias: {
    tslib: 'tslib/tslib.es6.js'
  }
})

`

**Comment by danielroe** [comment] 2022-02-01 08:05
Would you provide a reproduction? 🙏 

Is this different behaviour compared to enabling bridge vs not enabling bridge? Do you mean the styles aren't visible for .5-1s? Or the page doesn't load?

**Comment by binods-gintaa** [comment] 2022-02-01 08:11
Hi @danielroe , Thanks for quick reply
1. Create nuxt 2 project
2. Add tailwind css https://tailwindcss.com/docs/guides/nuxtjs
3. Enable nuxt bridge as per https://v3.nuxtjs.org/getting-started/bridge/

After 1 & 2 it will work file but after point 3 facing the issue

**Comment by danielroe** [comment] 2022-04-07 11:49
I belive this is a duplicate of https://github.com/nuxt/framework/issues/1207. Let's follow there.

**Closed by danielroe** 2022-04-07 11:49 UTC
Labels: needs details, bridge, needs reproduction, pending triage
