### ISSUE TITLE
[vite-node] [ERR_MODULE_NOT_FOUND]

### ISSUE THREAD

**Issue by aslero** [nuxt/framework#7534] opened 2022-09-15 06:43 UTC
### Environment

[vite-node] [ERR_MODULE_NOT_FOUND]

### Reproduction

[vite-node] [ERR_MODULE_NOT_FOUND]

### Describe the bug

[vite-node] [ERR_MODULE_NOT_FOUND]

**Comment by marcelxpfeifer** [comment] 2022-09-15 07:08
Are you using pnpm?

**Comment by danielroe** [comment] 2022-09-15 07:17
Would you provide a reproduction? 🙏

**Comment by aslero** [comment] 2022-09-15 07:19
> Are you using pnpm? If so you probably just need to run _pnpm install --shamefully-hoist_

no, use npm

**Comment by hbilal9** [comment] 2022-09-15 07:33
same error is coming with me:

i Vite client warmed up in 2963ms
√ Nitro built in 1292 ms
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')
  at _sfc_main.setup (H:/Workspace/Web Workspace/Productions/axlic-nuxt/node_modules/nuxt/dist/app/components/nuxt-root.vue:67:16)
  at callWithErrorHandling (H:\Workspace\Web Workspace\Productions\axlic-nuxt\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
  at setupStatefulComponent (H:\Workspace\Web Workspace\Productions\axlic-nuxt\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7109:29)
  at setupComponent (H:\Workspace\Web Workspace\Productions\axlic-nuxt\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7064:11)
  at renderComponentVNode (H:\Workspace\Web Workspace\Productions\axlic-nuxt\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:172:17)
  at renderToString (H:\Workspace\Web Workspace\Productions\axlic-nuxt\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:450:26)
  at Object.renderToString$1 [as renderToString] (/H:/Workspace/Web%20Workspace/Productions/axlic-nuxt/.nuxt/dev/index.mjs:472:24)
  at Object.renderToString (/H:/Workspace/Web%20Workspace/Productions/axlic-nuxt/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async /H:/Workspace/Web%20Workspace/Productions/axlic-nuxt/.nuxt/dev/index.mjs:527:21
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function
  at <NuxtRoot>
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function
  at <NuxtRoot>

![Screenshot 2022-09-15 123323](https://user-images.githubusercontent.com/25703314/190343267-aede88c3-01c3-4e77-998a-58bd4ed31301.png)

**Comment by hbilal9** [comment] 2022-09-15 07:35
node --version: v16.17.0
npm --version: 8.19.2

**Comment by cfires** [comment] 2022-09-15 07:52
node --version:16.15.0
npm  --version:8.9.0
yarn --version:1.22.15

use yarn
![image](https://user-images.githubusercontent.com/17745971/190347255-1660ee13-f6df-4cb1-97bb-fcbb152bda6a.png)

**Comment by marcelxpfeifer** [comment] 2022-09-15 08:22
Is this happening after updating from an older RC version? 
If so does running _npm install_ resolve the error? I think I was running into the same error, but simply running install again resolved the problem.

**Comment by hbilal9** [comment] 2022-09-15 08:25
> Is this happening after updating from an older RC version? If so does running _npm install_ resolve the error? I think I was running into the same error, but simply running install again resolved the problem.

already did install npm resolve but same error

**Comment by ewilan-riviere** [comment] 2022-09-15 08:41
I've this problem with `defineAsyncComponent`

```vue
<script lang="ts" setup>
// import type { SvgLibrary } from '@/.nuxt/types/svg-library'

const props = defineProps<{
  name?: string
}>()

const currentIcon = computed(() =>
  defineAsyncComponent({
    loader: () => import(`@/assets/svg/${props.name}.svg`),
    loadingComponent: {
      template: '<span></span>'
    },
    errorComponent: {
      template: '<span>error</span>'
    },
    delay: 200,
    timeout: 3000,
    suspensible: true
  })
)
const attrs = useAttrs()
</script>

<template>
  <span>
    <Suspense>
      <template #default>
        <current-icon :class="attrs.class" />
      </template>
      <template #fallback>
        <div :class="attrs.class" />
      </template>
    </Suspense>
  </span>
</template>
```

If I replace this line...

```ts
loader: () => import(`@/assets/svg/${props.name}.svg`),
```

...with direct path of a SVG file, it's works

```ts
loader: () => import(`@/assets/svg/download.svg`),
```

**Comment by manniL** [comment] 2022-09-15 13:38
This looks like a duplicate of https://github.com/nuxt/framework/issues/7220

**Comment by aslero** [comment] 2022-09-15 14:27
> Would you provide a reproduction? 🙏

I sent you invite to repo

**Comment by danielroe** [comment] 2022-09-15 20:39
Thanks. There's an issue with here with logging the error in `vite-node` bundler. (cc: @pi0) You can see it by setting `vite.devBundler` to `legacy`.

The issue is resolved with:

```diff
- import 'dayjs/locale/ru';
+ import 'dayjs/locale/ru.js';
```

(Note: please do not use a separate vite.config.js file - but configure vite via `vite` key in nuxt.config.)

**Comment by danielroe** [comment] 2022-09-15 20:41
Simple reproduction for vite node error logging issue: https://stackblitz.com/edit/github-5zmqlz

**Comment by danielroe** [comment] 2022-09-15 22:07
(The issue you are experiencing can be followed at https://github.com/nuxt/framework/issues/7206.)

**Closed** 2022-09-16 17:43 UTC
Labels: needs reproduction, pending triage

**Comment by SATHISH099** [comment] 2022-12-01 06:47
[vite-node] [plugin:vite:vue] [UnsupportedImport] ./app.vue:2:2

**Comment by manniL** [comment] 2022-12-01 07:02
> [vite-node] [plugin:vite:vue] [UnsupportedImport] ./app.vue:2:2

Please open a new issue with a reproduction instead of commenting on an old PR ☺️

**Comment by SATHISH099** [comment] 2023-01-02 13:04
Yeah sure.
