### ISSUE TITLE
support http proxy when using `nuxi init`

### ISSUE THREAD

**Issue by ikexing-cn** [nuxt/framework#8002] opened 2022-10-05 05:23 UTC
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `-`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Not exist

### Describe the bug

```
 ERROR  Failed to download template from registry: request to https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json failed, reason: connect ECON3

  at /Users/xdclass/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:13269:11
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async downloadTemplate (/Users/xdclass/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:13268:20)
  at async Object.invoke (/Users/xdclass/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:13336:15)
  at async _main (/Users/xdclass/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/cli.mjs:50:20)
```

### Additional context

` curl https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json`
```JSON
{
  "name": "v3",
  "defaultDir": "nuxt-app",
  "url": "https://v3.nuxtjs.org",
  "tar": "https://codeload.github.com/nuxt/starter/tar.gz/refs/heads/v3"
}
```

Everything works fine when I request the URL directly, I think this might be a bug in nuxt.

**Comment by danielroe** [comment] 2022-10-05 06:02
What happens when you run:

```bash
node -e "require('https').get('https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json')"
```

**Comment by ikexing-cn** [comment] 2022-10-05 06:05
`node -e "require('https').get('https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json')"`

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 443
}
```

It looks like the same error is reported...

**Comment by danielroe** [comment] 2022-10-05 06:56
It seems there is something stopping your node from connecting. Maybe an application firewall?

**Comment by ikexing-cn** [comment] 2022-10-05 07:14
That's strange, my application firewall is always off...... any other possible reasons?

**Comment by danielroe** [comment] 2022-10-05 07:25
Are you using a proxy?

Would you run:

```bash
env | grep -i proxy
npm config list | grep -i proxy
```

**Comment by ikexing-cn** [comment] 2022-10-05 07:30
Yes, I using proxy with clash.

`env | grep -i proxy`
```shell
all_proxy=sock5://127.0.0.1:8889
http_proxy=http://127.0.0.1:8889
https_proxy=http://127.0.0.1:8889
ALL_PROXY=sock5://127.0.0.1:8889
```

And then `npm config list | grep -i proxy` has not output.

**Comment by danielroe** [comment] 2022-10-05 07:33
So the issue is that HTTPS is not working over your HTTP proxy: https://github.com/lovell/sharp/issues/679.

We will need to implement a similar fix.

**Comment by so1ve** [comment] 2022-10-06 02:13
In fact, it is difficult to access Github and Raw in China, and we often use proxies. However, nuxi seems to be the same as degit, the default tar mode does not use the set proxy.

**Comment by codingcn** [comment] 2022-11-02 14:25
I can't init nuxt，have an update on the case?

**Comment by codingcn** [comment] 2022-11-03 02:08
In china, I succeeded

Just set DNS 114.114.114.114

**Comment by yonhung** [comment] 2022-11-03 05:46
I got the same error. 
It worked for me after I added `raw.githubusercontent.com` Ip address to my Windows hosts file. 
It seems a firewall dns cache pollution problem.

**Comment by so1ve** [comment] 2022-11-03 07:36
Does degit use https_proxy and https_proxy?

**Comment by pi0** [comment] 2022-11-03 14:40
Created issue for `giget` (used by nuxi cli). PR welcome.

https://github.com/unjs/giget/issues/23

**Comment by davinma** [comment] 2022-11-18 07:30
> It worked for me

Thanks!

**Comment by pi0** [comment] 2022-11-18 12:23
Landed by https://github.com/unjs/giget/pull/24

**Closed by pi0** 2022-11-18 12:23 UTC
Labels: bug, good first issue, 🔨 p3-minor-bug

**Comment by codername-123** [comment] 2023-01-02 14:23
I'm still having this issue on my windows machine

**Comment by danielroe** [comment] 2023-01-04 14:31
@codername-123 Would you try using `npx nuxi@latest` in case your npm is caching an old version?

**Comment by codername-123** [comment] 2023-01-06 08:22
My bad @danielroe it was a problem with my ISP... As soon as I changed my ISP it started working properly

**Comment by danielroe** [comment] 2023-01-06 11:22
Glad everything is resolved 😊

**Comment by HoneyDemon** [comment] 2023-01-13 08:31
in china ,I'm failed

**Comment by HoneyDemon** [comment] 2023-01-13 08:31
in china ,I'm failed
