### ISSUE TITLE
Route '/app' returns source code instead of rendered page in development

### ISSUE THREAD

**Issue by ghost** [nuxt/framework#4557] opened 2022-04-23 22:03 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v17.6.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `pnpm@6.32.8`
- Builder:          `vite`
- User Config:      `app`, `buildModules`, `css`, `experimental`, `postcss`, `runtimeConfig`, `ssr`, `target`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@vueuse/nuxt@8.3.1`

### Reproduction

https://stackblitz.com/edit/github-qyn5ga-lhthhn

### Describe the bug

While running in development mode, the route '/app' returns the source code instead of the rendered page. It works fine after build, and also if you navigate to the route via <NuxtLink> component but on reload or visiting the route, via entering the url it shows the code.

Visit reproduction link and add '/app' to the url and it returns 

```js
import { createHotContext as __vite__createHotContext } from "/_nuxt/@vite/client";import.meta.hot = __vite__createHotContext("/app.vue");import { default as __nuxt_component_0 } from "/_nuxt/node_modules/nuxt/dist/app/components/nuxt-link.mjs";
const _sfc_main = {}
import { resolveComponent as _resolveComponent, createVNode as _createVNode, createTextVNode as _createTextVNode, withCtx as _withCtx, openBlock as _openBlock, createElementBlock as _createElementBlock } from "/_nuxt/node_modules/.vite/deps/vue.js?v=eac54970"

const _hoisted_1 = /*#__PURE__*/_createTextVNode("Home")
const _hoisted_2 = /*#__PURE__*/_createTextVNode("App")
const _hoisted_3 = /*#__PURE__*/_createTextVNode("About")

function _sfc_render(_ctx, _cache) {
  const _component_NuxtPage = _resolveComponent("NuxtPage")
  const _component_NuxtLink = __nuxt_component_0

  return (_openBlock(), _createElementBlock("div", null, [
    _createVNode(_component_NuxtPage),
    _createVNode(_component_NuxtLink, { to: "/" }, {
      default: _withCtx(() => [
        _hoisted_1
      ]),
      _: 1 /* STABLE */
    }),
    _createVNode(_component_NuxtLink, { to: "/app" }, {
      default: _withCtx(() => [
        _hoisted_2
      ]),
      _: 1 /* STABLE */
    }),
    _createVNode(_component_NuxtLink, { to: "/about" }, {
      default: _withCtx(() => [
        _hoisted_3
      ]),
      _: 1 /* STABLE */
    })
  ]))
}


_sfc_main.__hmrId = "381730fa"
typeof __VUE_HMR_RUNTIME__ !== 'undefined' && __VUE_HMR_RUNTIME__.createRecord(_sfc_main.__hmrId, _sfc_main)
export const _rerender_only = true
import.meta.hot.accept(({ default: updated, _rerender_only }) => {
  if (_rerender_only) {
    __VUE_HMR_RUNTIME__.rerender(updated.__hmrId, updated.render)
  } else {
    __VUE_HMR_RUNTIME__.reload(updated.__hmrId, updated)
  }
})
import _export_sfc from '/_nuxt/@id/plugin-vue:export-helper'
export default /*#__PURE__*/_export_sfc(_sfc_main, [['render',_sfc_render],['__file',"/home/projects/github-qyn5ga-lhthhn/app.vue"]])
```

**Comment by danielroe** [comment] 2022-04-25 10:43
Related: https://github.com/nuxt/framework/issues/4137#issuecomment-1090680449.

**Comment by danielroe** [comment] 2022-04-25 14:20
@antfu any ideas to disable this behaviour in vite?

**Comment by antfu** [comment] 2022-04-25 16:42
Interestingly I can't reproduce this behaviour on plain Vite. Still investigating

**Comment by antfu** [comment] 2022-04-25 16:59
Found, we added `.vue` here so Vite resolves to it

https://github.com/nuxt/framework/blob/73ba30fb69b91a25ee595daa447f3d6988b4dc8c/packages/schema/src/config/vite.ts#L28-L30

I am not sure what's the consequence of changing this so I will leave it to you to PR :) (or let me know if there is any thing more I can help

**Comment by pi0** [comment] 2022-04-25 17:04
Thanks for investigation @antfu ❤️ I believe we added in initially to reduce breaking changes surface and allowing to import SCF components without explicit extension. I think even without having `.vue` in the list, something like `app.ts` or `app.mjs` with custom render function will produce same bug.

**Comment by grmnn** [comment] 2022-04-25 17:15
Thank you already for your efforts, I have tried now to remove `.vue` from the extensions array inside my `nuxt.config.ts` file and the ` /app ` route is working as it should. 

Looking at https://vitejs.dev/config/#resolve-extensions, it states it is not recommended to add something like `.vue`, but I am not sure what consequences this could have for Nuxt but for me it seems to work locally and also deployed with `target: 'static'`.

**Comment by pi0** [comment] 2022-04-25 17:26
> Since if every file that refers to the app.ts module, is actually been served as https://localhost:3000/app.ts. Eventually, we might need to disable all extensions for explicitness.

I see. Is there a way that we make to have an explicit base for loading js files like webpack from `/_nuxt/`? I guess such cases can happen even for nested paths.

> Meanwhile, I will research and see if we can have a middleware to distinguish the direct request and code requests.

That would be nice! Maybe we can check request headers or at least ensure they have an extension before serving?

**Comment by danielroe** [comment] 2022-09-20 12:30
This should be resolved in https://github.com/nuxt/framework/pull/7234.

**Closed by danielroe** 2022-09-20 12:30 UTC
Labels: bug, vite, 🔨 p3-minor-bug
