### ISSUE TITLE
3.0.0-rc.11 - $fetchRaw2 error - reason: connect EADDRNOTAVAIL :::3000 - Local

### ISSUE THREAD

**Issue by sduncan-mbt** [nuxt/framework#7828] opened 2022-09-26 10:01 UTC
### Environment

- Operating System: `Linux` - Ubuntu 20.04.5 LTS
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

run....

npx nuxi init test-app

npm i

npm run dev

### Describe the bug

After having an issue upgrading to the latest release candidate I get error...

500

request to http://[::]:32100/__nuxt_vite_node__/manifest failed, reason: connect EADDRNOTAVAIL :::32100 - Local (:::0) ()

at async $fetchRaw2 (./node_modules/ohmyfetch/dist/shared/ohmyfetch.c2a48baf.mjs:132:20)
at async ./.nuxt/dev/index.mjs:457:20
at async ./.nuxt/dev/index.mjs:526:64
at async ./.nuxt/dev/index.mjs:106:22
at async ./node_modules/h3/dist/index.mjs:592:19
at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:538:7)

So I created a completely clean install but still get the same issue.

**Comment by danielroe** [comment] 2022-09-26 10:48
Would you provide a reproduction? 🙏

**Comment by NMohm** [comment] 2022-09-26 15:50
I've got the same issue with every new nuxt installation. RC10 works fine though!

Here are the basic install steps (on Node v16.17.0)
```
npx nuxi init app
cd app
yarn install
yarn dev
```
This will lead me to the mentioned error. Setting host or url in nuxt.config does not help.


I personally run nuxt in a docker container. I pushed a fast version with the issue here: [https://github.com/NMohm/nuxt-rc11-docker](https://github.com/NMohm/nuxt-rc11-docker)

**Comment by gstamosbg** [comment] 2022-09-26 20:40
Same here

`500
Invalid URL ()

at async $fetchRaw2 (./node_modules/ohmyfetch/dist/shared/ohmyfetch.c2a48baf.mjs:132:20)
at async ./.nuxt/dev/index.mjs:465:20
at async ./.nuxt/dev/index.mjs:534:64
at async ./.nuxt/dev/index.mjs:106:22
at async ./node_modules/h3/dist/index.mjs:592:19
at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:538:7)`

**Comment by clowNay** [comment] 2022-09-27 06:01
Same issue as issue creator here.

**Comment by mblachlov24** [comment] 2022-09-27 06:45
Same error without Docker

**Comment by danielroe** [comment] 2022-09-27 09:03
**Reproduction without Nuxt**:

```bash
> const server = require('http').createServer((req, res) => { res.end('hi') })
> server.listen(4000)
> server.address()
{ address: '::', family: 'IPv6', port: 4000 }
> require('http').request('http://[::]:4000')
Uncaught Error: connect EADDRNOTAVAIL :::4000 - Local (:::0)
```

I think it might be best to default to `127.0.0.1` for vite-node as this will work even if no ipv4 port is open.

A workaround for now is either to run `nuxt dev --host 0.0.0.0` (or `127.0.0.1` if you are not running within a docker container) or to update your Dockerfile:

```diff
  EXPOSE 3000

+ ENV HOST=0.0.0.0

  ENTRYPOINT yarn dev
```

**Comment by NMohm** [comment] 2022-09-27 09:17
Yes this works. I thought the host variable belongs in the nuxt.config.ts... Thank you!

**Comment by dargmuesli** [comment] 2022-10-04 22:58
It took me a long time to find this issue as what Nuxt showed me was only:
![image](https://user-images.githubusercontent.com/4778485/193945640-02f97997-67a0-4686-b405-a9c721866d7e.png)
The reason why `fetch failed` was not given. Is it up to me to find out why or is there something that can be done to make Nuxt show the cause directly? If so, I can surely open an issue to track this.

**Comment by HerrSammyDE** [comment] 2022-10-11 19:54
same

**Comment by Dawntraoz** [comment] 2022-10-30 21:00
Hi @danielroe 👋

In my case, I'm having this issue when I install the project and add SSL parameters to the script (using Node >= v18).
```
"dev": "nuxt dev --host 0.0.0.0 --https --ssl-cert localhost.pem --ssl-key localhost-key.pem"
```

Complains about a `failed fetch` like the other comments https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#fetch-experimental

If I downgrade to node version 17.9.1, it works.

**Comment by danielroe** [comment] 2022-11-03 17:22
resolved in https://github.com/nuxt/framework/pull/8616

**Closed by danielroe** 2022-11-03 17:22 UTC
Labels: bug, 🔨 p3-minor-bug, workaround available

**Comment by roberto-butti** [comment] 2022-11-07 08:15
Hi everyone,
just for providing some feedback, updating to 3.0.0-rc.13 , i still have the error.
The issue is related to the check that node LTS performs on the certificates.
The workarounds I'm using to make it work are:
- using Node 16 with basic ssl plugin and binding to 0.0.0.0.
OR
- using 18 but setting an env var. In my case I set a new script in package.json, section script:
```
"devs": "NODE_TLS_REJECT_UNAUTHORIZED=0 nuxt dev --https --host=0.0.0.0",
```

About node18 workaround ... this workaround disable the certification check (so it is not the best option, you are enabling SSL for security reason, but now i'm disabling the check, on my __local__ environment)
About node18 I'm using 18.2.0 , i'm going to update with the latest version of node18.
