### ISSUE TITLE
Defining HMR breaks and results in indefinite reload

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/framework#4926] opened 2022-05-10 21:12 UTC
### Environment

Nuxt CLI v3.0.0-rc.2                                                                                                                                                                                                21:10:28
RootDir: /app                                                                                                                                                                                                       21:10:35
Nuxt project info:                                                                                                                                                                                                  21:10:35

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `privateRuntimeConfig`, `publicRuntimeConfig`, `buildModules`, `modules`, `googleFonts`, `css`, `vite`, `ngrok`
- Runtime Modules:  `~/modules/ngrok`
- Build Modules:    `~/modules/google-fonts`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                                                                                    21:10:35

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

in nuxt config define:
```ts
    vite: {
        server: {
            hmr: {
                protocol: "ws",
                host: "localhost"
            },
        }
    }
```

This is exactly the same as is being used when I load using `localhost` - but then it breaks even loading from localhost. I am trying to define this so when I load ngrok URL it still loads the websocket

### Describe the bug

See above.

### Additional context

Connection to websocket [address] failed

**Comment by danielroe** [comment] 2022-07-04 14:11
Closing as I can't reproduce this: https://stackblitz.com/edit/github-ij4eox. If it's still the case for you, let me know with a reproduction and I'll reopen.

**Closed by danielroe** 2022-07-04 14:11 UTC
Labels: pending triage
