### ISSUE TITLE
useFetch returns data.result === null on RC.6 in production mode.

### ISSUE THREAD

**Issue by mlbonniec** [nuxt/framework#6249] opened 2022-07-29 18:56 UTC
### Environment

```
Nuxt CLI v3.0.0-rc.6
RootDir: /Users/.../Documents/development/professional/MY_PROJECT
Nuxt project info:

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.6.0`
- Nuxt Version:     `3.0.0-rc.5`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `modules`, `head`, `css`, `vite`, `srcDir`, `progress`
- Runtime Modules:  `nuxt-progress@0.1.4`
- Build Modules:    `-`
------------------------------
```

### Reproduction

I'm sorry, but I can't reproduce the bug except on my project.
However, I know the bug is due to the `v3.0.0-rc.6` because I tried an old commit, with the `v3.0.0-rc.4` so it was working. And just with upgrading to the `rc.6`, the bug appears.
Using the code below, outside of my project, it's working. But it was working on `rc.4`, so I don't understand 😕 

### Describe the bug

`useFetch` returns data.value `null` on client (**at the first fetch**), but it seems to have a value on server.
When I fetch again (with a "load more" button) I get my results.

```js
<script lang="ts" setup>
import { useFetch } from '#app';

async function fetchArticles (): Promise<void> {
  articles.isLoading = true;
  const { data } = await useFetch<{ posts: GhostPage[] } & BrowseResults>('GHOST CONTENT API', {
    params: {
      key: 'API',
      include: ['authors', 'tags'].join(','),
      page: articles.currentPage
    },
    pick: ['posts', 'meta']
  });
  if (data.value.meta.pagination.pages === articles.currentPage)
    articles.hasMore = false;
  articles.data.push(...data.value.posts);
  articles.filteredData = filterArticles(articles.data);
  articles.isLoading = false;
}
</script>
```

**Comment by wzy1935** [comment] 2022-07-29 19:01
Save problem. I'm just about to submit my issue😂

my reproduction: https://stackblitz.com/edit/github-vyfip2?file=app.vue

await sames not work with this fetchData. In development mode it will show 'success', but in production it's just failed.

**Comment by pi0** [comment] 2022-07-29 19:23
Hi, @wzy1935. Trying your reproduction, upgrading to [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel) seems to solve production issue 👍🏼 

As another fix, you can explicitly pass fetch key:

```js
const { data: arr } = await useFetch('/api/hello', { key: 'hello' });
```

**Comment by pi0** [comment] 2022-07-29 19:28
@mlbonniec Do you mind to also try with explicit key? Also i can see you are modifying async fetcher data. You have `pending` (`{ data, pending }`) that indicates loading status. You can also use transform to modify the response within the fetcher. Otherwise, you can directly use `useState` + `$fetch` to implement your own logic.
 
(will share an example lately)

**Comment by mlbonniec** [comment] 2022-07-29 20:26
@pi0 thanks for sharing you tips of passing `key`! It's now working as well. However, upgrading to the edge channel isn't working for me.
Do you know explain to us why this isn't working without the `key` property? Is it normal, or an issue?
Thanks again!

**Comment by danielroe** [comment] 2022-07-29 22:30
The repro seems to be working on edge channel: https://stackblitz.com/edit/github-vyfip2-rinvts.

**Comment by wzy1935** [comment] 2022-07-30 00:39
@pi0 @danielroe Edge channel works for me, thanks! Looking forward to the final release👍

**Comment by danielroe** [comment] 2022-08-15 11:04
I'm closing as RC8 is now out. Let me know if it wasn't resolved and I'll reopen!

**Closed by danielroe** 2022-08-15 11:04 UTC
Labels: pending triage
