### ISSUE TITLE
Try cloudflare modules

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#484] opened 2021-09-05 23:02 UTC
https://developers.cloudflare.com/workers/cli-wrangler/configuration#modules

Using this, we can natively use imports for chunks instead of using one entry (maybe behind a flag?)

Alternative might be using KV + eval but last time checked both `eval` and `importScripts` was forbidden due to security concerns they had. So it is probably only way to use native option.

**Comment by ScriptedAlchemy** [comment] 2021-12-10 06:29
I'm currently working around this to enable Module Federation code streaming at edge. My idea is pretty much same as yours. Replace how webpack gets a chunk with KV get. 

So far I know if 2 ways to make this happen. 

1) use wasm and embed your own JS engine. Counterproductive as this sounds, running js->rust->eval(js) 

You can circumvent the limits cloudflare imposes. QuickJs is my current approach but I'm still working this out. Main problem is how bindings for quick were designed (not for cloudflare) 

2) if you have an enterprise account, you can get the edge compute team to enable eval() 

Wasm option is possible, but I need more time.

**Comment by ScriptedAlchemy** [comment] 2021-12-11 00:35
Solved it

**Comment by warflash** [comment] 2022-02-03 22:15
Just stumbled across this discussion https://github.com/nuxt/framework/discussions/1528 while looking for a way to get nuxt to work with cloudflare pages functions.  
As the first release candidate seems to be confirmed for q1 I was wondering if there is any news on this issue and whether the ability to leverage functions will be included with the rc?
Thanks alot for the work on this, super excited for nuxt + cf pages!

**Closed** 2022-04-12 17:16 UTC
Labels: nitro, experiment
