### ISSUE TITLE
On windows_nt aka win10 setting target - static option breaks build.

### ISSUE THREAD

**Issue by genesem** [nuxt/framework#4350] opened 2022-04-14 10:08 UTC
### Environment

Nuxt project info:
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27498764.32c798c`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `target`, `telemetry`, `meta`, `components`, `css`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

just set   target: 'static' - makes a bug on working basic code on windows 10.

### Describe the bug

Enabling:  "target: 'static', " in nuxt.config.ts breaks **build and generate**:

```
D:\Dev\nuxt3-tw3-base>make build
Nuxt CLI v3.0.0-27498764.32c798c                                                                              15:04:48
i Vite client warmed up in 810ms                                                                              15:04:52
i Client built in 1909ms                                                                                      15:04:53
i Building server...                                                                                          15:04:53
√ Server built in 583ms                                                                                       15:04:53
√ Generated public .output/public                                                                       nitro 15:04:53
start Preparing prerenderer...                                                                          nitro 15:04:53

 ERROR  Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

  at new NodeError (node:internal/errors:371:5)
  at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1035:11)
  at defaultResolve (node:internal/modules/esm/resolve:1105:3)
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
  at ESMLoader.import (node:internal/modules/esm/loader:332:22)
  at importModuleDynamically (node:internal/modules/esm/translators:106:35)
  at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
  at prerender (/D:/Dev/nuxt3-tw3-base/node_modules/nitropack/dist/chunks/prerender.mjs:2169:39)
  at async /D:/Dev/nuxt3-tw3-base/node_modules/nuxt3/dist/index.mjs:1215:9

makefile:37: recipe for target 'build' failed
make: *** [build] Error 1
```

### Additional context

probably nitro issue.

**Comment by danielroe** [comment] 2022-04-14 11:14
would you provide a reproduction? 🙏

**Comment by genesem** [comment] 2022-04-14 11:54
mkdir app2; cd app2
npx nuxi init .
yarn

`D:\Dev\_TESTS\app2>npx nuxi info
Nuxt CLI v3.0.0-27498764.32c798c                                                                              16:46:56
RootDir: D:\Dev\_TESTS\app2                                                                                   16:46:57
Nuxt project info:                                                                                            16:46:57

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27498764.32c798c`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
`

at this step 'yarn dev' works.

**nuxt.config.ts** content: 

`import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({

  target: 'static', // makes a bug.

})
`

command: 'npx nuxi build'

`
D:\Dev\_TESTS\app2>npx nuxi build
Nuxt CLI v3.0.0-27498764.32c798c                                                                              16:53:59
i Vite client warmed up in 1445ms                                                                             16:54:03
i Client built in 1446ms                                                                                      16:54:03
i Building server...                                                                                          16:54:03
√ Server built in 537ms                                                                                       16:54:04
√ Generated public .output/public                                                                       nitro 16:54:04
start Preparing prerenderer...                                                                          nitro 16:54:04

 ERROR  Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

  at new NodeError (node:internal/errors:371:5)
  at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1035:11)
  at defaultResolve (node:internal/modules/esm/resolve:1105:3)
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
  at ESMLoader.import (node:internal/modules/esm/loader:332:22)
  at importModuleDynamically (node:internal/modules/esm/translators:106:35)
  at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
  at prerender (/D:/Dev/_TESTS/app2/node_modules/nitropack/dist/chunks/prerender.mjs:2169:39)
  at async /D:/Dev/_TESTS/app2/node_modules/nuxt3/dist/index.mjs:1215:9`

**Comment by turkhero** [comment] 2022-04-14 19:57
I'm facing the exact same problem

**Comment by mctweb** [comment] 2022-04-14 20:20
I believe that these are all related:
https://github.com/nuxt/framework/issues/4330
https://github.com/nuxt/framework/issues/4350
https://github.com/nuxt/framework/issues/4256
https://github.com/nuxt/framework/issues/4232

The issue is present for `nuxt generate`, `nuxi generate`, and `nuxi build` with `target: static`. However is isn't present when building using the following settings in nuxt.config.
```
nitro: {
    preset: 'nitro-prerender',
  }
```
This setting doesn't work using `nuxi dev` however. When running dev, this error is shown:
```
Error: [worker] exited
    at Worker. (file:///C:/Users/Fraser/Websites/2022/nuxt3-test/node_modules/nitropack/dist/chunks/prerender.mjs:2038:14)
    at Object.onceWrapper (events.js:520:26)
```

**Comment by lihbr** [comment] 2022-05-02 12:12
Was facing the same on Windows, can you try:
1. Deleting `node_modules`
2. Deleting `package-lock.json` (or `yarn.lock`)
3. Updating Nuxt to `rc.1` in `package.json`
4. Installing dependencies and trying again

You should now face #4555 (not solving the issue but at least making sure whether it's a similar one to #4555 or not)

**Comment by danielroe** [comment] 2022-06-16 06:56
This should be resolved in the latest nitropack. Let me know if not and I can reopen.

**Closed by danielroe** 2022-06-16 06:56 UTC
Labels: nitro, needs reproduction, pending triage
