### ISSUE TITLE
Runtime.ImportModuleError - netlify deploy 

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#1865] opened 2021-11-11 14:34 UTC
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27277330.202617b`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.5`
------------------------------

### Describe the bug

https://v3nuxt.netlify.app

<img width="1287" alt="CleanShot 2021-11-11 at 17 33 30@2x" src="https://user-images.githubusercontent.com/38668796/141315700-5cf252bf-66c9-4414-b2ba-bc58c9def2ad.png">

### Reproduction

https://github.com/productdevbook/nuxt3-app

**Comment by J-Kern** [comment] 2021-11-11 14:40
This is a duplicate of #1826 .

Please refer to this answer from the [netlify-team-account](https://github.com/nuxt/framework/issues/1826#issuecomment-966190438).

**Closed** 2021-11-11 14:42 UTC
Labels: bug, nuxt3
