### ISSUE TITLE
upgrade to rc10,page styles cannot use in another page

### ISSUE THREAD

**Issue by GITleonine1989** [nuxt/framework#7581] opened 2022-09-16 03:58 UTC
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.6.0`
- Builder:          `vite`
- User Config:      `builder`, `experimental`, `runtimeConfig`, `css`, `app`, `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

rc8 : https://stackblitz.com/edit/github-crzvsj?file=nuxt.config.ts,app.vue
rc10: https://stackblitz.com/edit/github-vuepdp?file=pages%2FpageB.vue,pages%2FpageA.vue,pages%2Findex.vue

### Describe the bug

under rc8 i can use pageA style on pageB,but under rc10 can not . it seemed before rc9 page and compoent preload everywhere.
is there any way to use style cross page?

**Comment by lukaszflorczak** [comment] 2022-09-16 05:17
IMO the approach as shown in the example is incorrect and insecure. 

If you have global styles keep them separate and load in `nuxt.config.ts`:

```ts
export default defineNuxtConfig({
  css: [
    '@/assets/styles/global.scss',
  ],
})
```

**Comment by GITleonine1989** [comment] 2022-09-16 05:55
@lukaszflorczak you are right about the global.css,but i have already write many style in the page  and share them on different page ,if i have to find the shared style out extract to a global css file...that will take times

**Comment by richgcook** [comment] 2022-09-16 09:51
This is maybe related but since moving to rc10 the CSS order seems incorrect? See the screenshots. The reset styles are prioritised before the global styles. This only happens on static build (npm run generate) – is fine when running npm run dev

![Screenshot 2022-09-16 at 10 34 58@2x](https://user-images.githubusercontent.com/901289/190611836-c849d37c-5b27-414f-a571-82e05bdb9bf6.jpg)

![Screenshot 2022-09-16 at 10 32 08@2x](https://user-images.githubusercontent.com/901289/190611832-c44f2bed-b5bc-4e9a-9273-cb40d609ae1c.jpg)

I haven't adjusted this from rc9 so the rc10 update has caused this. Any thoughts?

**Comment by danielroe** [comment] 2022-09-16 10:15
@richgcook This is likely a change from injecting styles inline. The issue is that the _inlined_ styles are taking priority over the styles in your separate CSS file. It's a different issue from the one described above, but I think we can likely resolve. Would you mind opening a new issue with a minimal reproduction?

**Comment by richgcook** [comment] 2022-09-16 10:21
@danielroe Thanks for this. In rc10 has this changed then? Was rc9 not injecting inline styles? 

What's strange is how is it knowing which to to add as inline styles (reset.css) and which to include as a separate CSS file when they're both declared in the config file as separate CSS files?

**Comment by richgcook** [comment] 2022-09-16 10:22
Looking at the screenshot below it appears both the reset and the global styles are being included in files (entry.9ee5cc77.css) but the reset is ALSO being inserted inline?

![Screenshot 2022-09-16 at 11 21 51@2x](https://user-images.githubusercontent.com/901289/190618037-68eee625-83fd-4cc3-addf-979abddebf22.jpg)

**Comment by g4w3l** [comment] 2022-09-17 08:30
Same issue here, where inline styles for `<button>` seem to take the priority over the CSS properties set in the page or layout : 

![image](https://user-images.githubusercontent.com/621235/190847867-5fa2bcaa-101c-4741-98fc-c97fc5627028.png)

Resulting in having my buttons to be transparent instead of having the set background.

**Comment by danielroe** [comment] 2022-09-17 08:50
It would be really helpful if you could share a reproduction.

**Comment by g4w3l** [comment] 2022-09-17 10:18
> It would be really helpful if you could share a reproduction.

@danielroe I tried but I couldn't reproduce on a brand new project, the problem only shows on the built bundle, not with `npm run dev`, and all was working fine on rc8 (with UnoCSS for the styles). It could be another issue, I will investigate more on how to reproduce, and maybe open a new issue if I find something interesting :)

**Comment by danielroe** [comment] 2022-09-17 11:05
For now, you can workaround by setting `experimental.inlineSSRStyles` to false.

I'm closing this issue as pages shouldn't rely on styles defined in other pages - they are _meant_ to be separate.

@g4w3l if you get a chance, I'd be very grateful of that new issue + reproduction...

**Closed** 2022-09-17 11:06 UTC
Labels: needs reproduction, pending triage, workaround available

**Comment by richgcook** [comment] 2022-10-07 11:05
> I'm closing this issue as pages shouldn't rely on styles defined in other pages - they are meant to be separate.

This isn't the issue. For some reason, with the two global CSS imports within the config file, both are being imported but but only one is also being included inline. This wasn't happening before.

**Comment by danielroe** [comment] 2022-10-07 11:23
@richgcook If you are experiencing something else, would you open a new issue? :pray:
