### ISSUE TITLE
Named export 'provider' not found - std-env

### ISSUE THREAD

**Issue by Redemption198** [nuxt/framework#4319] opened 2022-04-13 08:25 UTC
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.1`
- Nuxt Version:     `3.0.0-27496606.e43ba6e`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `head`, `css`, `build`, `modules`, `buildModules`, `components`, `runtimeConfig`, `strapi`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.2`
- Build Modules:    `@vueuse/nuxt@8.2.5`, `@nuxtjs/strapi@1.3.1`, `@unlighthouse/nuxt@0.3.21`
------------------------------

### Reproduction

Can't reproduce

### Describe the bug

Error in console caused by std-env

ERROR  [worker reload] [worker init] Named export 'provider' not found. The requested module 'file:///home/user/Documents/GitHub/project-name/node_modules/std-env/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'file:///home/user/Documents/GitHub/project-name/node_modules/std-env/index.js';
const { provider, isWindows } = pkg;

  import { provider, isWindows } from 'node_modules/std-env/index.js';
  ^^^^^^^^
  SyntaxError: Named export 'provider' not found. The requested module 'node_modules/std-env/index.js' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'node_modules/std-env/index.js';
  const { provider, isWindows } = pkg;

### Additional context

I've already tried the following solutions:

- Running `npx nuxi upgrade --force` (as suggested in nuxt/bridge#175)
- Removing `@nuxtjs/strapi`
- Upgrading Nuxt to the latest version using `npx nuxi upgrade`
- Adding `std-env` to devDependencies (as suggested in nuxt/bridge#175) causes the error to become:

[worker reload] [worker init] Cannot find module '/home/user/Documents/GitHub/project-name/node_modules/std-env/index.js' imported from /home/user/Documents/GitHub/project-name/.nuxt/dev/index.mjs

  at finalizeResolution (internal/modules/esm/resolve.js:271:11)
  at moduleResolve (internal/modules/esm/resolve.js:694:10)
  at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:805:11)
  at Loader.resolve (internal/modules/esm/loader.js:88:40)
  at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
  at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:72:40)
  at link (internal/modules/esm/module_job.js:71:36)

By looking inside the `yarn.lock` I found two versions of `std-env`, `^2.3.0` and `^3.0.1`, the first one is being used by `"@nuxt/cli@^2.15.8"` and `"@nuxt/config@2.15.8"`

Also if I visit the local server I still get the error reported in nuxt/framework#4274

**Comment by danielroe** [comment] 2022-04-13 09:03
For Bridge, you should be using `nuxt-edge`, which has an upgraded version of dependency. The remaining module with an old dep (`@nuxt/telemetry`) will be upgraded shortly.

**Comment by danielroe** [comment] 2022-04-13 09:41
Just looked at your issue again. It looks like you've filed it as a Nuxt 3 issue, but clearly you have Nuxt 2 dependencies in place (`@nuxt/cli` and `@nuxt/config`). Would you provide a reproduction so I can see your setup?

**Comment by Redemption198** [comment] 2022-04-13 10:46
I've marked it as a nuxt 3 issue because it is a Nuxt 3 project that started from zero (no migration from Nuxt 2), I have no idea why there are Nuxt 2 dependencies I just upgraded the project with the usual command _npx nuxi upgrade_ and it broke, when I get back home I'll check again the dependencies and try to create a reproduction.

**Comment by Redemption198** [comment] 2022-04-13 13:21
After some more debugging I found out that the issue seems to be caused by [unlighthouse](https://github.com/harlan-zw/unlighthouse), removing it causes the server to start even though I still get the error reported in #4274

**Comment by Redemption198** [comment] 2022-04-13 14:04
> > the error persists
> 
> Which error?

#4274

**Comment by danielroe** [comment] 2022-04-13 14:06
In that case I'll close this issue. Would you be able to provide a reproduction on that issue, or a new one, so we can get to the bottom of it?

**Closed by danielroe** 2022-04-13 14:06 UTC
Labels: nuxt3, needs reproduction, pending triage
