### ISSUE TITLE
nuxi genetate with wrong baseURL to _payload.js

### ISSUE THREAD

**Issue by loo2k** [nuxt/framework#8104] opened 2022-10-11 07:55 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-egtlnd-lkqx3b?file=nuxt.config.ts

nuxt@3.0.0-rc.11 with config `app.baseURL`

```ts
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  app: {
    baseURL: '/sub-path/',
  },
});
```

### Describe the bug

I made configuration of `app.baseURL` with `/sub-path/`, and tried to use `npm run generate` to build static site.

I get result of the *.html in ./dist directory show that:

- `_paylaod.js` get the wrong path
- the other assets files are correct

```html
  <link rel="modulepreload" href="/_payload.js">
  <link rel="modulepreload" as="script" crossorigin href="/sub-path/_nuxt/entry.96a10300.js">
  <link rel="modulepreload" as="script" crossorigin href="/sub-path/_nuxt/index.a407e84c.js">
  <link rel="modulepreload" as="script" crossorigin href="/sub-path/_nuxt/fetch.e898b128.js">
  <link rel="prefetch" as="script" crossorigin href="/sub-path/_nuxt/error-component.236c792e.js">
  <link rel="prefetch stylesheet" href="/sub-path/_nuxt/entry.26effea5.css">
```

It will lead to a 404 error when i deploy these file to my site. 

### Additional context

https://github.com/nuxt/framework/blob/ed1c704835c280cd2d7ad795452f2da9c8401e2a/packages/nuxt/src/core/runtime/nitro/renderer.ts#L191

The `payloadURL` is resolve incorrect.

**Comment by danielroe** [comment] 2022-10-11 10:24
I believe this has already been resolved via https://github.com/nuxt/framework/pull/7809.

Would you confirm by testing with [the edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/)?

**Comment by loo2k** [comment] 2022-10-12 04:12
> 

I trie to confirm in the edge channel, but when i reinstall dependecis, i got the errors below.

```sh
$ npm i --registry=https://registry.npmjs.com/

> postinstall
> nuxt prepare

Nuxi 3.0.0-rc.9-27702110.abd5dc5                                                                                                           12:10:34

 ERROR  defineNuxtConfig is not defined                                                                                                    12:10:34

  at nuxt.config.ts:2:16
  at Object.jiti (node_modules/jiti/dist/jiti.js:1:247502)
  at resolveConfig (node_modules/c12/dist/index.mjs:220:21)
  at loadConfig (node_modules/c12/dist/index.mjs:104:40)
  at async loadNuxtConfig (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:678:18)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:1563:19)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:732:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:29:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)

npm ERR! code 1
npm ERR! path /Users/vm/Code/test
npm ERR! command failed
npm ERR! command sh -c nuxt prepare

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vm/.npm/_logs/2022-10-12T04_10_32_934Z-debug-0.log
```

**Comment by danielroe** [comment] 2022-10-12 08:35
It looks like you are not using the latest edge version - you seem to be using an edge version from rc9.

Here's a reproduction of everything working fine with latest edge version: https://stackblitz.com/edit/github-vtrl2t. I'm going to close this issue, tentatively, but if you can provide a reproduction with an issue I will very happily reopen it. 🙏

**Closed by danielroe** 2022-10-12 08:35 UTC
Labels: needs reproduction, pending triage
