### ISSUE TITLE
Auto-import engine treats non-component files as components

### ISSUE THREAD

**Issue by MorevM** [nuxt/framework#8922] opened 2022-11-11 17:11 UTC
### Environment

No matter

### Reproduction

https://stackblitz.com/edit/github-g7riij?file=nuxt.config.ts

Run `npm run dev` and check the console.
There are three "components" registered, but actually only one of them is a Vue component.

### Describe the bug

The auto-import engine treat any (?) `vue`/`ts` file as component and register it.
However, developers may put the types alongside the component, or even they want to put any other file with logic related to component for decomposition purposes. 

There should be a more robust check if the file is really a Vue component.
As I can see it breaks nothing but autocomplete..

![example-of-wrong-autocomplete](https://user-images.githubusercontent.com/49679666/201392603-dd79d7a1-fc47-4693-9192-43a5ba4260d0.jpg)

**Comment by danielroe** [comment] 2022-11-11 18:03
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC via https://github.com/nuxt/framework/pull/8787.

Let me know if not and I'll reopen.

**Closed by danielroe** 2022-11-11 18:03 UTC
Labels: pending triage

**Comment by MorevM** [comment] 2022-11-11 18:38
@danielroe if this is the only MR related, then I can already say that it will not help.
Please look at the filenames in the [reproduction](https://stackblitz.com/edit/github-g7riij?file=nuxt.config.ts) more carefully - there is no `.d.ts` files at all, just `.ts`.

I also updated the [reproduction](https://stackblitz.com/edit/github-g7riij?file=nuxt.config.ts) to use Nuxt from the Edge channel, and this is still an issue.

I made a picture with points of attention to make it easier to understand what I'm talking about:

![points-of-attention](https://user-images.githubusercontent.com/49679666/201408565-d94760e5-c0c5-46bf-b5b0-6a8defa8905f.jpeg)

**Comment by danielroe** [comment] 2022-11-11 18:50
Ah. If you are placing `.ts` files in the components folder, they will be scanned as components. That's intended behaviour. To change this, you can configure `extensions`:

```js
export default defineNuxtConfig({
  components: [
    {
      path: '~/components',
      extensions: ['.vue']
    }
  ]
})
```

**Comment by MorevM** [comment] 2022-11-11 19:03
@danielroe thanks, it solves the problem. 

I noticed it's not documented anywhere. Do you need a docs update in that part?

**Comment by danielroe** [comment] 2022-11-11 19:04
That would be very welcome - thank you.
