### ISSUE TITLE
After upgrading to nuxt3-rc2 Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/ufo.js?v=9947c87e' does not provide an export named 'isEqual'

### ISSUE THREAD

**Issue by lyykfi** [nuxt/framework#4883] opened 2022-05-08 12:43 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-rc.2-27530889.9e5a3cd`
- Package Manager:  `npm@8.4.1`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `buildModules`, `css`, `intlify`, `googleFonts`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.7-ffbc354`
- Build Modules:    `@intlify/nuxt3@0.1.10`, `@pinia/nuxt@0.1.9`

### Reproduction

I have the error if I open any page.

### Describe the bug

I have the bug in a browser console and seems like client-only part doesn't work.

**Comment by itshizhan** [comment] 2022-05-08 12:56
delete node_modole, and npm install dependencies

**Comment by lyykfi** [comment] 2022-05-08 19:42
> delete node_modole, and npm install dependencies

The same. :-(

**Comment by lyykfi** [comment] 2022-05-08 19:43
The problem is on this string: 

import { withoutBase, isEqual } from "/_nuxt/node_modules/.vite/deps/ufo.js?v=8e2ce077";

**Comment by pi0** [comment] 2022-05-09 14:55
Hi @lyykfi. Please try removing lockfile and `node_modules` directory. This is likely a vite cache issue.

**Comment by j0Shi82** [comment] 2022-05-09 19:42
Had the same issue and got it working by enforcing `ufo 0.8.4` across all dependencies.

```json
resolutions: {
  "ufo": "^0.8.4"
}
```

That said, removing `node_modules` and the lockfile did also work for me and I could remove the `resolution` again.

**Comment by danielroe** [comment] 2022-05-10 10:01
I'm closing this as an issue with package resolution. If you have a reproduction that can't be fixed, please provide it and I will reopen.

**Comment by michaelpumo** [comment] 2022-05-10 16:48
This is still an issue on Nuxt `3.0.0-rc.3`.

Fresh install after deleting `package-lock.json` and removing `node_modules` completely.

**Error**:
`Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/ufo.js?v=3d76fa91' does not provide an export named 'isEqual' (at router.mjs:8:23)`

**From this line**:
`import { withoutBase, isEqual } from "/_nuxt/node_modules/.vite/deps/ufo.js?v=3d76fa91";`

**Comment by lucassimines** [comment] 2022-05-10 20:28
I'm facing the same issue.

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.8.0`
- Builder:          `vite`
- User Config:      `alias`, `head`, `runtimeConfig`, `components`, `typescript`, `css`, `vite`, `dir`, `build`, `nitro`, `modules`, `postcss`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.4`
- Build Modules:    `-`
------------------------------
```

**Comment by cdowning** [comment] 2022-05-10 22:08
@danielroe @pi0 

I am experiencing the same issue as others. I deleted my node_modules & package-lock.json and opened window in incognito - I am still getting the error. I did put my code on a repo to see if you might be able to reproduce. Maybe I am doing something wrong?

Code to reproduce: https://github.com/cdowning/nuxt3-rc

### Environment

Operating System: Linux
Node Version: v16.14.0
Nuxt Version: 3.0.0-rc.3
Package Manager: npm@8.3.1
Builder: vite
User Config: ssr: false, target: 'static', tailwindcss, buildModules
Build Modules: @nuxtjs/tailwindcss

### Reproduction
When I run `npm run dev -- -o`, I get a blank page with an error in the console.

**Error:** Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/ufo.js?v=50c827e2' does not provide an export named 'isEqual' (at router.mjs:2:45)

**Comment by cdowning** [comment] 2022-05-10 22:59
After looking through the package-lock, I noticed tailwind was still using ufo v0.7.11. I forced the version to be ^0.8.4 in package.json. After making that change, it worked.

```
// package.json
"overrides": {
   "ufo": "^0.8.4"
}
```

**Comment by Archetipo95** [comment] 2022-05-11 07:24
Yesterday I wasted some hours to debug this, at the end I solved it by removing node_modules and .lock file(s) and using yarn.

**Comment by danielroe** [comment] 2022-05-11 07:55
What was the package depending on an old version of ufo?

(`yarn why ufo` should show the details.)

cc: @pi0

**Comment by Archetipo95** [comment] 2022-05-11 08:18
> yarn why ufo

I don't know if this can be helpful, sorry I'm a new newbie

`=> Found "ufo@0.8.4"
info Has been hoisted to "ufo"
info Reasons this module exists
   - Hoisted from "@nuxt#schema#ufo"
   - Hoisted from "nuxt#ufo"
   - Hoisted from "nuxt#h3#ufo"
   - Hoisted from "nuxt#ohmyfetch#ufo"
   - Hoisted from "nuxt#@nuxt#vite-builder#ufo"
   - Hoisted from "nuxt#nitropack#ufo"
   - Hoisted from "nuxt#nitropack#unstorage#ufo"
   - Hoisted from "nuxt-lodash#@nuxt#kit#@nuxt#schema#ufo"
   - Hoisted from "@vueuse#nuxt#@nuxt#kit#@nuxt#schema#ufo"
   - Hoisted from "nuxt#@nuxt#telemetry#@nuxt#kit#@nuxt#schema#ufo"
info Disk size without dependencies: "64KB"
info Disk size with unique dependencies: "64KB"
info Disk size with transitive dependencies: "64KB"
info Number of shared dependencies: 0
=> Found "@nuxtjs/tailwindcss#ufo@0.7.11"
info This module exists because "@nuxtjs#tailwindcss" depends on it.
info Disk size without dependencies: "60KB"
info Disk size with unique dependencies: "60KB"
info Disk size with transitive dependencies: "60KB"
info Number of shared dependencies: 0
=> Found "@intlify/nuxt3#ufo@0.7.11"
info Reasons this module exists
   - "@intlify#nuxt3" depends on it
   - Hoisted from "@intlify#nuxt3#@nuxt#kit#ufo"
info Disk size without dependencies: "60KB"
info Disk size with unique dependencies: "60KB"
info Disk size with transitive dependencies: "60KB"
info Number of shared dependencies: 0
=> Found "externality#ufo@0.7.11"
info This module exists because "nuxt#@nuxt#vite-builder#externality" depends on it.
info Disk size without dependencies: "60KB"
info Disk size with unique dependencies: "60KB"
info Disk size with transitive dependencies: "60KB"
info Number of shared dependencies: 0
=> Found "@nuxtjs/tailwindcss#@nuxt/schema#ufo@0.8.4"
info This module exists because "@nuxtjs#tailwindcss#@nuxt#kit#@nuxt#schema" depends on it.
info Disk size without dependencies: "64KB"
info Disk size with unique dependencies: "64KB"
info Disk size with transitive dependencies: "64KB"
info Number of shared dependencies: 0`

**Comment by vanling** [comment] 2022-05-12 11:58
Same here. Not resolve able by above steps and I got the feeling its because of tailwindcss which uses older ufo version.

```
node_modules/ufo
  ufo@"^0.7.11" from externality@0.2.1
  node_modules/externality
    externality@"^0.2.1" from @nuxt/vite-builder@3.0.0-rc.3
    node_modules/@nuxt/vite-builder
      @nuxt/vite-builder@"^3.0.0-rc.3" from nuxt@3.0.0-rc.3
      node_modules/nuxt
        dev nuxt@"3.0.0-rc.3" from the root project
  ufo@"^0.7.11" from @nuxtjs/tailwindcss@5.0.4
  node_modules/@nuxtjs/tailwindcss
    dev @nuxtjs/tailwindcss@"^5.0.4" from the root project
    ```

**Comment by benoitdemaegdt** [comment] 2022-05-16 09:18
Hey there 👋 

I am having the same issue in my `nuxt rc.3` project.

I tried many times to delete `package-lock.json` and the `node_modules` folder and reinstall everything, but it didn't change anything.

Using an npm version >= 8.3 and adding
```json
"overrides": { "ufo": "^0.8.4" }
```
in my package.json seems to fix the issue 🤔 

If this can help, I am also using tailwind 👇 
```json
  "devDependencies": {
    "@headlessui/vue": "^1.5.0",
    "@heroicons/vue": "^1.0.6",
    "@nuxtjs/tailwindcss": "^5.0.2",
    "@tailwindcss/forms": "^0.5.0",
    "@tailwindcss/typography": "^0.5.2",
    "nuxt": "^3.0.0-rc.3"
  },
  "overrides": { "ufo": "^0.8.4" }
```

**Comment by vanling** [comment] 2022-05-17 08:40
I hope this is not going to be an issue with every update:) 
I know this one is closed now @danielroe i guess that is because tailwind is the culprit here with using older ufo, which [is fixed](https://github.com/nuxt-community/tailwindcss-module/commit/3492982ea93801921cc2d95d2a5ce2e317ea36bb) in the tailwind module but not yet released in a version.

_I 'like' to switch back to npm7 because of other issues [vue3 vs vue2 with vueuse in npm 8](https://github.com/vueuse/vueuse/issues/1488) :(_

**Comment by pi0** [comment] 2022-05-17 17:30
While this is not an issue with Nuxt 3, let's keep the issue until at least the majority of deps migrate to the latest of `ufo`.

We probably also need to create some follow-up issues to ensure the chances of codependency mismatch are less.

Based on the above `npm why` reports, the reasons for ufo `0.7.x` hosting are:
- `@nuxtjs/tailwindcss`: Will released shortly
- `externality`: /cc @danielroe can you please do the release?

**Comment by shaif-dorIT** [comment] 2022-05-18 12:57
Hi,
I also have an issue with the rc3 and tailwindcss nuxt3 module.

Work perfectly with rc2.


I'm using pnpm and the official guide on how to get started and on ho to install tailwind module.

Also, with pnpm the override suggetion user made earlier did not work foe me I do not know if it's I misplaced it in my package.config.

**Comment by KonradDeskiewicz** [comment] 2022-05-23 11:24
`@nuxtjs/tailwindcss` Just release a new version and the issue is gone.

**Closed** 2022-05-24 15:10 UTC
Labels: discussion

**Comment by TangsWang** [comment] 2022-05-27 02:29
> `@nuxtjs/tailwindcss` Just release a new version and the issue is gone.

i didn't use tailwindcss, but also got this issue.

rc2 is ok, so what is the final answer about this.

**Comment by cinob** [comment] 2022-06-17 01:35
Same issue with the rc4 on vercel.
`overrides` is not work for me

**Comment by gustawdaniel** [comment] 2022-06-20 05:34
@pi0, This issue should not be closed. Is sth wrong event in `3.0.0-rc.4`

In all places I have `ufo@0.8.4` but there is one that requre `0.7.11`.

```
ufo@0.7.11                                                                                                                       
node_modules/ufo                                                                                                                 
  ufo@"^0.7.4" from @nuxt/vue-app@2.15.8                                                                                         
  node_modules/@nuxt/vue-app                                                                                                     
    @nuxt/vue-app@"^2.15.8" from the root project                                                                                
    peer @nuxt/vue-app@"^2.15" from @nuxtjs/composition-api@0.32.0                                                               
    node_modules/@nuxtjs/composition-api                                                                                         
      @nuxtjs/composition-api@"^0.32.0" from the root project                                                                    
  ufo@"^0.7.9" from @nuxtjs/composition-api@0.32.0                                                                               
  node_modules/@nuxtjs/composition-api                                                                                           
    @nuxtjs/composition-api@"^0.32.0" from the root project 
```

**Comment by danielroe** [comment] 2022-06-20 06:33
You should not have `@nuxtjs/composition-api` installed. It is pulling in Nuxt 2 with all its dependencies.
