### ISSUE TITLE
Router Scrollbehavior

### ISSUE THREAD

**Issue by folamy** [nuxt/framework#1989] opened 2021-11-17 12:51 UTC
### Environment

Linux

### Reproduction

New feature

### Describe the bug

Is there a way to set a custom scroll behavior on the router? I don't think there is any as of now. 
It will be good to have that configuration from a plugin file or nuxt.config.ts

**Comment by nandi95** [comment] 2021-11-17 14:20
Duplicate of https://github.com/nuxt/framework/issues/1707

**Closed** 2021-11-18 09:50 UTC
Labels: nuxt3, pending triage

**Comment by folamy** [comment] 2021-11-18 11:57
Thanks @danielroe. Yeah, I got the hack from  #1707.
