### ISSUE TITLE
Flash of unstyled content in generated page when using scss  nuxt 3.0.0-rc.12 

### ISSUE THREAD

**Issue by nurRiyad** [nuxt/framework#8352] opened 2022-10-20 06:12 UTC
#### package.json
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "HOST=0.0.0.0 nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.12",
    "sass": "^1.55.0"
  }
}

```
#### nuxt.config.ts
```
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  css: ['@/main.scss'],
  experimental: {
    // Temporary workaround for stackblitz
    writeEarlyHints: false,
  },
});

```

### Reproduction
**StackBlitz minimal reproduction link**
https://stackblitz.com/edit/github-hywqdd?file=app.vue

### Describe the bug

At reload time it shows unstyled pages. But in the dev server, it seems fine. It only appears when I generate the project with 
`npm run generate` and serve with `npm run preview`

### Additional context

**In my project, this problem doesn't appear until nuxt3 rc-11.0.0. It only starts appearing  after updating my project to nuxt3 rc-12.0.0**

**Comment by danielroe** [comment] 2022-10-20 08:22
This is a regression of the inline styles implementation and you can work around it by setting `experimental.inlineSSRStyles` to `false`.

**Comment by BlakeB415** [comment] 2022-10-23 07:25
> This is a regression of the inline styles implementation and you can work around it by setting `experimental.inlineSSRStyles` to `false`.

This workaround breaks our styling on the initial page load.

**Comment by danielroe** [comment] 2022-10-23 09:52
@BlakeB415 Would you provide a reproduction? 🙏

**Comment by kwright02** [comment] 2022-10-23 16:42
> @BlakeB415 Would you provide a reproduction? 🙏

We'll do our best but we're not sure how to. We set the option like you said above and as Blake mentioned it breaks the styling on initial page load. Is there something specific we could do or provide for you?

**Comment by danielroe** [comment] 2022-10-23 16:57
@kwright02 Some info [here](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction).

Basically, start with your project and remove as much as you can until the problem can't be reproduced. 🙏

I have a fix for this issue in progress but want to make sure it also solves your situation.

**Comment by kwright02** [comment] 2022-10-23 17:55
Ok, I'll see what I can test, any recommendations for where to start removing from? Or does it really matter?

**Comment by danielroe** [comment] 2022-10-23 18:09
Try to remove as much complexity as possible, as quickly as possible. Start with your `app.vue`, remove layouts, remove all pages but index page, gradually remove components in that page, etc.

**Comment by BlakeB415** [comment] 2022-10-23 21:14
> Try to remove as much complexity as possible, as quickly as possible. Start with your `app.vue`, remove layouts, remove all pages but index page, gradually remove components in that page, etc.

https://stackblitz.com/edit/github-hywqdd-nehtut?file=components/Test.vue

I've narrowed it down to our use of ClientOnly. Using ClientOnly inside of a component seems to break scoped CSS on SSR when inlineSSRStyles is false. The server and client's data-v-* attributes do not seem to match up when this occurs.

**Comment by danielroe** [comment] 2022-10-23 21:15
Thanks. I appreciate it.

**Comment by BlakeB415** [comment] 2022-10-23 21:19
> Thanks. I appreciate it.

Note that this only occurs with the build and not the dev server.

**Comment by monkemedia** [comment] 2022-10-24 23:36
Oh my god this has taken me hours to resolve since upgrading to rc.12. The unstyled flash was extremely annoying :/ Thankfully `experimental: {
    inlineSSRStyles: false
  },` fixed it for me. Thank you @danielroe

**Comment by codingcn** [comment] 2022-10-26 03:22
this only seems to occur with the build and not the dev server.

**Comment by codingcn** [comment] 2022-10-26 04:21
when `experimental.inlineSSRStyles` to `false` and `yarn build`

I have 3 `<style>`
```
<template>
  <div>
  </div>
</template>

<style lang="scss">
// Valid
</style>

<style lang="scss">
// Invalid
</style>

<style scoped lang="scss">
// Invalid
</style>

```

**Comment by danielroe** [comment] 2022-10-26 06:24
@codingcn That sounds like https://github.com/nuxt/framework/issues/8397.

**Comment by codingcn** [comment] 2022-10-26 07:54
@danielroe RC11 is normal, but RC12 is abnormal

this is my `nuxt.config.ts`
```
export default defineNuxtConfig({
    telemetry: false,
    experimental: {
        writeEarlyHints: false,
        reactivityTransform: true,
        inlineSSRStyles:false
    },
    vite: {
        esbuild: {
            drop: process.env.NODE_ENV === 'production' ? ['console', 'debugger'] : [],
        },
        build: {
            minify: 'esbuild',
            chunkSizeWarningLimit: 500,
            cssCodeSplit: true,
            },
      },

}
```

**Comment by manniL** [comment] 2022-11-05 11:37
Should be resolved via https://github.com/nuxt/framework/pull/8666 - cannot reproduce [with rc.13 anymore](https://stackblitz.com/edit/https-github-comnuxtframeworkissues8352?file=nuxt.config.ts,package.json).

**Closed by manniL** 2022-11-05 11:37 UTC
Labels: bug, ❗ p4-important, workaround available
