### ISSUE TITLE
Image assets imported relatively in components are not processed properly

### ISSUE THREAD

**Issue by doomspec** [nuxt/framework#2939] opened 2022-01-26 16:28 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27386759.b449d0b`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/prod-cdn-2g32p

### Describe the bug

I am trying to put the image assets in the components path (next to the .vue component files) and try to use them by a relative path like `<img src="./play.svg" />`, the assets are not loaded properly in `nuxi build`, though they work well in `nuxi dev`.

**Comment by StevenJPx2** [comment] 2022-01-27 04:00
Try putting this in your nuxt.config: 
```ts
//...  
  vite: {
    build: { assetsInlineLimit: 0 },
   },
```

**Comment by doomspec** [comment] 2022-01-28 00:00
> Try putting this in your nuxt.config:
> 
> ```ts
> //...  
>   vite: {
>     build: { assetsInlineLimit: 0 },
>    },
> ```

I updated the sandbox and added this config. But it still doesn't work.

**Comment by Der-Alex** [comment] 2022-02-03 09:44
The same goes for images that are inside the assets folder. I have the structure `./assets/img/test-img.jpg` and try to use it inside a picture tag with `srcset="~/assets/img/test-img.jpg"` which doesn't work when running `npm run dev`. 
Using `srcset="assets/img/test-img.jpg"` or `srcset="/assets/img/test-img.jpg"` works. 
I created a sample project to check and reproduce this issue. I am using NodeJs version 14.16.1.

Sample Project: https://github.com/Der-Alex/image-asset-example

**Comment by StevenJPx2** [comment] 2022-02-04 13:55
Hmm, I just checked this out in my own project. Yes, this is a troubling issue. Don't know why this is marked as a minor bug if it doesn't have a workaround.

**Comment by baronkoko** [comment] 2022-02-16 09:43
@Der-Alex have you tried using a larger image or adding this config?
```
vite: {
  build: { assetsInlineLimit: 0 },
},
```
Because when I did in your example none of the methods worked with `npm run start`

**Comment by StevenJPx2** [comment] 2022-02-16 09:48
@baronkoko See: https://github.com/nuxt/framework/issues/2939#issuecomment-1022825138

**Comment by baronkoko** [comment] 2022-02-16 10:29
@StevenJPx2 thank you for the quick response. 

I set this config and tried to import assets in two ways `/assets/...` and `assets/...`.
Both of these methods work great with `npm run dev`. But none works with `npm run build` `npm run start`.
Сan you take a look, please? Maybe I made a mistake somewhere, but in another project, I have the same thing.

`Nuxt CLI v3.0.0-27415326.3c563fa`

Reproduction: https://github.com/baronkoko/nuxt3-assets

**Comment by StevenJPx2** [comment] 2022-02-18 09:03
@baronkoko As it stands, you can't use `srcset` or add an image path into a component, because it won't render in build. For the component fix, I have given a workaround, `srcset` would probably need you to do a JS workaround by detecting screen-size and changing the image that way.

**Comment by baronkoko** [comment] 2022-02-18 09:44
> stands

`<img>` `src` attribute works great, it doesn't need a workaround. Or maybe I misunderstood you in this regard. 
The only problem with `srcset`. It does not work with `npm run build` `npm run start`. The path is generated, even with a hash, but there are no assets in the `_nuxt` folder.
![Screenshot 2022-02-18 at 11 40 56](https://user-images.githubusercontent.com/27996386/154657835-12089c33-2b81-4a31-8c51-2489d99ffbfd.png)

**Comment by StevenJPx2** [comment] 2022-02-18 11:36
@baronkoko Yeah, I mentioned how to work around srcset not working by using src alone.

**Comment by StevenJPx2** [comment] 2022-02-21 17:02
No idea. I hope it gets fixed soon. @danielroe?

**Comment by StevenJPx2** [comment] 2022-03-05 08:56
When is this getting resolved? This might have to do with Vue-loader, maybe?

**Comment by StevenJPx2** [comment] 2022-04-02 05:45
Okay, so this is a Vite issue. I had to move away from using Nuxt 3 to Vitesse to see what the incompatibilities are and this props up there as well. 

[This](https://stackoverflow.com/questions/69490057/vite-img-src-alias-not-working-when-passing-as-component-props) solved the issue for me.

Essentially, you have to import the image as a module of sorts, line this:

```vue
<script setup>
import imgSrcWithAlias from '@/assets/icon-1.svg'
</script>

<template>
  <component-a :img-src="imgSrcWithAlias" />
</template>
```

And this works in Vitesse. @baronkoko I don't know if this fixes your `srcset` issue but I think this fixes @doomspec issue.

**Comment by hoomb** [comment] 2022-04-02 06:42
@StevenJPx2 this will mark all images as `prefetch` to read them on page load.
don't do this if you are using responsive images for various resolutions. Then they will be all loaded at the beginning.

**Comment by StevenJPx2** [comment] 2022-04-02 07:17
@hoomb I wasn't aware of that. Either way, this looks to be a Vite issue, right?

**Comment by hoomb** [comment] 2022-04-02 12:49
@StevenJPx2 yes. It is a Issue with Vite

This works for me:
```
  <img src="@/assets/images/myimage.jpg" alt="my image">
```

And regarding to the Problem with responsive images and `srcset`, this is the solution which I'm using till there comes a fix from Vite

```
<style lang="scss" scoped>
@mixin bg-image($img) {
  background: url(~/assets/images/#{$img}_sm.jpg) no-repeat center center;
  background-size: cover;

  @media (min-width: 720px) {
    background: url(~/assets/images/#{$img}_md.jpg) no-repeat center center;
    background-size: cover;
  }

  @media (min-width: 1024px) {
    background: url(~/assets/images/#{$img}_lg.jpg) no-repeat center center;
    background-size: cover;
  }

  @media (min-width: 1920px) {
    background: url(~/assets/images/#{$img}_xl.jpg) no-repeat center center;
    background-size: cover;
  }
}

.slide-image {
  width: 100%;
  height: 100%;

  &.slide-0 {
    @include bg-image(image1);
  }

  &.slide-1 {
    @include bg-image(image2);
  }
}
</style>
```

**Comment by StevenJPx2** [comment] 2022-04-02 13:00
@hoomb Problem is not with adding the image source directly to an image element. The problem is with passing the image path as a prop to a component which then loads it into an image element. Vite seems to not resolve paths which do not load directly into an `img[src]`.

**Comment by baronkoko** [comment] 2022-04-04 07:29
@StevenJPx2 @hoomb Thank you both. I tried `srcset` in Vite Vue and there it works fine with the relative path. I updated my example of using `srcset` in the Nuxt 3 (https://github.com/baronkoko/nuxt3-assets) using the relative path, but unfortunately, it also only works with `npm run dev`, but not with `npm run build` `npm run start`.
As I noticed, with `npm run build` `npm run start` Nuxt 3 does not create these files in the `.output/public/_nuxt` folder, although the paths are correct and a hash is added.
![Screenshot 2022-04-04 at 10 26 06](https://user-images.githubusercontent.com/27996386/161494178-2cf6be50-6931-4f0a-859b-f078d0ddd32e.png)

**Comment by StevenJPx2** [comment] 2022-04-04 07:47
@baronkoko It will work with bare Vite Vue because it is processing the page as an SPA. Everything rendered will be on the client side. So, Vitesse uses SSG which prerender items on the page and Nuxt uses both SSR and SSG. This is what causes the build issues.

**Comment by baronkoko** [comment] 2022-04-04 07:53
@StevenJPx2 so, since we know what the problem is, we only have to wait until it is fixed, right?

**Comment by iamandrewluca** [comment] 2022-04-27 08:38
I looked more into the problem.

- `@vue/compiler-sfc` allows to handle `srcset` via `transformAssetUrls` option, and has some defaults [link](https://github.com/vuejs/core/blob/4a3237ad9300693e465f82a6be3552565a1c4be3/packages/compiler-sfc/src/templateTransformAssetUrl.ts#L40)
- `vite` is using that option to transform `picture#srcset` [link](https://github.com/vitejs/vite/blob/5c1ee5abf987e25bd39d5af8013ed907a33d4d14/packages/vite/src/node/plugins/html.ts#L123)
- In nuxt found 2 places where `transformAssetUrls` is used, and no `srcset` there [link1](https://github.com/nuxt/framework/blob/e789a5727b06184fa5aa6b8ed2c78451e53ca06c/packages/schema/src/config/build.ts#L263), [link2](https://github.com/nuxt/framework/blob/e789a5727b06184fa5aa6b8ed2c78451e53ca06c/packages/schema/src/config/webpack.ts#L156)

**Comment by iamandrewluca** [comment] 2022-04-27 09:09
I went into my node_modules and found [this](https://github.com/vuejs/core/blob/4a3237ad9300693e465f82a6be3552565a1c4be3/packages/compiler-sfc/src/templateTransformAssetUrl.ts#L42) code and added there `srcset` and it works fine. 🤔

**Comment by StevenJPx2** [comment] 2022-04-27 12:55
> I looked more into the problem.
> 
> 
> 
> - `@vue/compiler-sfc` allows to handle `srcset` via `transformAssetUrls` option, and has some defaults [link](https://github.com/vuejs/core/blob/4a3237ad9300693e465f82a6be3552565a1c4be3/packages/compiler-sfc/src/templateTransformAssetUrl.ts#L40)
> 
> - `vite` is using that option to transform `source#srcset` [link](https://github.com/vitejs/vite/blob/5c1ee5abf987e25bd39d5af8013ed907a33d4d14/packages/vite/src/node/plugins/html.ts#L126)
> 
> - In nuxt found 2 places where `transformAssetUrls` is used, and no `srcset` there [link1](https://github.com/nuxt/framework/blob/e789a5727b06184fa5aa6b8ed2c78451e53ca06c/packages/schema/src/config/build.ts#L263), [link2](https://github.com/nuxt/framework/blob/e789a5727b06184fa5aa6b8ed2c78451e53ca06c/packages/schema/src/config/webpack.ts#L156)

So, this was something I noticed, but it doesn't solve for any components not loading any image sources.

**Comment by Block81838** [comment] 2022-08-08 20:34
Same,it seems these image assets are not packed by nuxt. All image tags are still using the relative path.

**Comment by Block81838** [comment] 2022-08-09 01:44
There is a possible way via importing the image, and then bind the img src prop with imported image.

**Comment by StevenJPx2** [comment] 2022-08-18 04:14
> There is a possible way via importing the image, and then bind the img src prop with imported image.

Yes, we did discuss that above. But @danielroe, is there any movement on this?

**Comment by danielroe** [comment] 2022-08-18 07:12
I can't reproduce this now on RC8 - I believe the Vite 2 -> 3 upgrade has resolved this issue. If not, please provide a reproduction and I'll look into it.

**Closed by danielroe** 2022-08-18 07:13 UTC
Labels: bug, vite, nuxt3, ❗ p4-important
