### ISSUE TITLE
&.something scss syntax breaks styles

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt/framework#3624] opened 2022-03-12 13:29 UTC
### Environment

Latest Nuxt 3 and windicss, see reproduction...

### Reproduction

https://stackblitz.com/edit/nuxt3-windi-css-bug

### Describe the bug

The following `scss` syntax broke somewhere between version `3.0.0-27424151.dbab979` and the latest version `3.0.0-27451165.114cbe3`

```scss
.repo-list-item {
  @apply p-4 bg-white dark:bg-gray-800 md:(shadow-lg rounded-lg);
  &.status-0 {
    .indicator {
      @apply border-gray-300 dark:border-gray-600;
    }
  }
}
```

What happens is that once `&.something...` is added the styles for `.repo-list-item` under `@apply p-4 ...` are no longer added. Note that this is windicss.

### Additional context

The version where it still works had a bug and required `components: { global: true }`, maybe the fix for that created the problem, but just a wild guess...

<hr>

**Update** 

The following also doesn't work:

```scss
.repo-list-item {
  @apply p-4 bg-white dark:bg-gray-800 md:(shadow-lg rounded-lg);
  .indicator {
    @apply border-gray-300 dark:border-gray-600;
  }
}
```

It seems like nested `@apply`s break the ones on the top-level selector.

**Comment by danielroe** [comment] 2022-03-12 14:01
Would you raise this on `nuxt-windicss`? 🙏 

By the way, the reproduction doesn't seem to be behaving as you're suggesting - both components display the same as each other on both of versions of nuxt you mention (though on the recent version not even the grey background is showing - even without nesting).

**Comment by toniengelhardt** [comment] 2022-03-12 14:43
@danielroe so sorry, I tested something in the reproduction and forgot to fork 🙈

Now you can see the difference again. What I found is that actually not the `&` is responsible, but actually any nested selector that has an `@apply` breaks the `@apply` on the top-level selector. 

In my app the problem seems to be coming from Nuxt, not nuxt-windicss, bc it works with `3.0.0-27424151.dbab979` and doesn't work with `3.0.0-27451165.114cbe3`, every other package version and the code being the same.

I'll try to fully reproduce this in StackBlitz 🙏🏽

**Comment by toniengelhardt** [comment] 2022-03-12 14:56
@danielroe I managed to reproduce.

`3.0.0-27451165.114cbe3` broken:
https://stackblitz.com/edit/nuxt3-windi-css-bug

`3.0.0-27424151.dbab979` working: 
https://stackblitz.com/edit/nuxt3-windi-css-bug-part-2

Everything but the nuxt version is the same.

**Comment by danielroe** [comment] 2022-03-22 10:28
This seems to be an issue with `nuxt-windicss` (see https://github.com/windicss/nuxt-windicss/issues/165#issuecomment-1074994084) - likely a small change in how the plugin is added to the array...

Having said that, I've added some code to ensure that from the Nuxt end we're adding plugins in the right order: https://github.com/nuxt/framework/pull/3827

**Comment by danielroe** [comment] 2022-03-22 11:01
I'm going to close this issue in favour of https://github.com/windicss/nuxt-windicss/issues/165 as I suspect it just needs to ensure that the windicss plugin [isn't added to the end of the array](https://github.com/windicss/nuxt-windicss/blob/main/packages/nuxt-windicss/src/module.ts#L273). but if you think at any point this is a nuxt issue then ping me and I'll reopen.

**Closed by danielroe** 2022-03-22 11:01 UTC
Labels: upstream-bug
