### ISSUE TITLE
Nuxt Bridge: Cannot find module '.../.nuxt/dist/server/server.mjs'

### ISSUE THREAD

**Issue by crazymind** [nuxt/framework#4231] opened 2022-04-10 09:38 UTC
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.2`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `server`, `env`, `bridge`, `ssr`, `target`, `publicRuntimeConfig`, `privateRuntimeConfig`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `cloudinary`, `strapi`, `i18n`, `moment`, `eslint`, `axios`, `pwa`, `vuetify`, `generate`, `loading`, `build`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/pwa@3.3.5`, `@nuxtjs/strapi@1.3.1`, `@nuxtjs/cloudinary@1.0.3`, `@nuxtjs/i18n@7.2.1`
- Build Modules:    `@nuxtjs/eslint-module@3.1.0`, `@nuxtjs/vuetify@1.12.3`, `@nuxtjs/moment@1.6.1`, `@nuxtjs/device@2.1.0`, `@pinia/nuxt@0.1.8`, `@nuxt/bridge@3.0.0-27491748.3186841`
------------------------------

### Reproduction

Hi there,
I just wanted to migrate to Bridge from my Nuxt2 App.
Followed the steps from here: https://v3.nuxtjs.org/bridge/overview#ensure-everything-goes-well
Now I receive the following error as soon I open the app: 

### Describe the bug

`[nitro] [request error] Cannot find module '.../.nuxt/dist/server/server.mjs' imported from .../.nuxt/dev/index.mjs`

The file server.mjs will not be written at this place therefore the error makes sense. Error coming from here:
```
// index.mjs
const getSSRApp =
  !process.env.NUXT_NO_SSR &&
  cachedImport(() =>
    import(
      '.../.nuxt/dist/server/server.mjs'
    )
  )
```
Seems to be a problem with SSR, but I deactivated in my config. 

```
export default defineNuxtConfig({
  env: {},
  ssr: false,
  target: 'static',
  // ...
})
```

**Comment by Tragio** [comment] 2022-04-10 20:37
Duplicate of #886 😃

**Comment by crazymind** [comment] 2022-04-11 03:04
Disabling Nitro worked. Thanks for the hint @Tragio 

```
export default defineNuxtConfig({
// ....
  bridge: {
    nitro: false,
  }
// ...
})
```

**Closed** 2022-04-11 03:04 UTC
Labels: bridge, pending triage
