### ISSUE TITLE
router.extendRoutes support in nuxt.config.js for Nuxt 3

### ISSUE THREAD

**Issue by wzdxy** [nuxt/framework#2041] opened 2021-11-20 04:03 UTC
### Environment

PS D:\nuxt3-app> npx nuxi info
Nuxt CLI v3.0.0-27288761.d3fb512                                                                                    11:17:49
RootDir: D:\nuxt3-app                                                                                               11:17:52
Nuxt project info:                                                                                                  11:17:52

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0-27288761.d3fb512`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `router`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/laughing-tereshkova-3byow?file=/nuxt.config.ts
(visit /topic1 in Browser)

or

https://github.com/wzdxy/nuxt3-extend-routes-issue

### Describe the bug

I need a router like `/topic:id(\\d+)`.
So I config a `extendRoutes` in `nuxt.config.ts`
```ts
export default defineNuxtConfig({
  router: {
    extendRoutes(routes, resolve) {
      routes.push({
        path: '/product:id(\\d+)',
        name: product1',
        file: join(__dirname, 'pages/product.vue'),
      })
      console.log(routes)
    },
  },
})
```
But I got a 404 error. And ` No match found for location with path "/topic1"` on terminal.
![image](https://user-images.githubusercontent.com/12983764/142713061-fcaf4424-947a-4645-b7e7-51626c17635f.png)
![image](https://user-images.githubusercontent.com/12983764/142713047-4467f567-a9a3-420c-851d-acb29fb9f8a7.png)

### Additional context

https://github.com/nuxt/framework/pull/1757/commits/c8d8cfbbc438fcb0cccb2328b02b20e6469f3c20

I refer to this commit and rewrite my code，it worked，but very bloated.

```
  buildModules: [
    '~/modules/addRoutes'
  ],
```

**Comment by andysay** [comment] 2021-11-26 23:32
any update ?

**Comment by Nirlah** [comment] 2021-12-01 22:20
This is a much-needed feature...
I also wonder if there is a way we can have Router Matching Syntax inside the pages directory instead of a programmatic solution?

**Comment by theGC** [comment] 2021-12-20 08:02
we use wildcards to match any page within a headless CMS, in Nuxt 2 this was pretty straightforward:

```js
router: {
  extendRoutes (routes, resolve) {
    routes.push({
      name: 'cmsPage',
      path: '*',
      component: resolve(__dirname, 'cms/index.vue'),
    })
  },
},
```

Without access to the router this isn't possible.

**Comment by danielroe** [comment] 2021-12-20 09:15
This is how you can do it in Nuxt 3 at the moment (with the `extend:pages` hook):

```js
import { resolve } from 'path'
import { defineNuxtConfig } from 'nuxt3'
import { createCommonJS } from 'mlly'
const { __dirname } = createCommonJS(import.meta.url)

export default defineNuxtConfig({
  hooks: {
    'pages:extend' (pages) {
      pages.push({
        name: 'cmsPage',
        path: '*',
        file: resolve(__dirname, 'cms/index.vue')
      })
    }
  }
})
```

**Comment by Nirlah** [comment] 2021-12-20 12:45
@danielroe What about extending with redirects?

**Comment by danielroe** [comment] 2021-12-20 12:53
@Nirlah For that we have `useRouter` which you can call in a plugin.

**Comment by GithubMitch** [comment] 2021-12-21 17:15
Goodevening Nuxties,

I'm having a routes problem and cant get this nuxt.config.ts to work setting up routes, and this solution is not working for me currently.

> This is how you can do it in Nuxt 3 at the moment (with the `extend:pages` hook):
> 
> ```js
> import { resolve } from 'path'
> import { defineNuxtConfig } from 'nuxt3'
> import { createCommonJS } from 'mlly'
> const { __dirname } = createCommonJS(import.meta.url)
> 
> export default defineNuxtConfig({
>   hooks: {
>     'pages:extend' (pages) {
>       pages.push({
>         name: 'cmsPage',
>         path: '*',
>         file: resolve(__dirname, 'cms/index.vue')
>       })
>     }
>   }
> })
> ```

This is giving me the following error using Nuxt3 : 

Cannot read properties of undefined (reading 'forEach')
  at createRouterMatcher (./node_modules/vue-router/dist/vue-router.cjs.js:1468:12)  
  at Module.createRouter (./node_modules/vue-router/dist/vue-router.cjs.js:2795:21)  
  at file://./.nuxt/dist/server/server.mjs:1717:40  
  at file://./.nuxt/dist/server/server.mjs:197:57  
  at callWithNuxt (file://./.nuxt/dist/server/server.mjs:246:13)  
  at applyPlugin (file://./.nuxt/dist/server/server.mjs:197:29)  
  at Module.applyPlugins (file://./.nuxt/dist/server/server.mjs:207:11)  
  at async createNuxtAppServer (file://./.nuxt/dist/server/server.mjs:34:5)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:254:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:261:20)

Why cant i use this out of the box, is it still in a experimental phase ? 

I've also tried setting up vue-router in vue3 and it works like a charm...

I don't know how to use it in nuxt3, and there are allmost no to none references/documentation on this topic.
The main thing i noticed is in vue3 there is a main.js file where i can mount the router as following : 

import { createApp } from 'vue'
import App from './App.vue'
import router from './router'

createApp(App).use(router).mount('#app')

I dont really know how to to set it up in nuxt , ive tried : 
1. using vue-router as import , 
2. using a main.js file ( out of desperation ) 
3.  using 'wzdxy's solution as adding routes via plugin but that gives me the same forEach error.
4.  Setting up a folder >  router/index.js file 
5. Ive also tried adding routes in my main index file.
6.  Currently having bloated nested folder structure within pages/ but its very ugly, i.e.
     - category > [_categoryslug] > brand > [_brandslug] > subcategory > [_subcategoryslug] > product > [_productslug]
     - WIthin this structure pointing to some main-component with keep-alive and <NuxtChilds>  👎 
     - this is really messy and doesnt really do my app justice 


To no avail ...

My repo contains some sensitive information so if you want me to share it with you i'll clean that up.
But maybe some of you know the answer already by looking at the before-mentioned error.

Best Regards and have a nice holiday !

Mitch

**Comment by danielroe** [comment] 2021-12-21 17:22
@GithubMitch As long as you have a pages folder, Nuxt should setup vue-router integration for you.

As your issue isn't strictly related to this feature request, would you open a new one with a minimal reproduction? No need to include your whole project, just enough to cause the issue.

**Comment by GithubMitch** [comment] 2021-12-21 17:40
> @GithubMitch As long as you have a pages folder, Nuxt should setup vue-router integration for you.
> 
> As your issue isn't strictly related to this feature request, would you open a new one with a minimal reproduction? No need to include your whole project, just enough to cause the issue.

 
Yeah well as point 6 explains i got this folder structure to work , and it does what i want , but it's not the way to go.
Therefore im not sure if my explanation was clear.

I'm trying to extend routes so i wont need the ridiculous folder structure pointing to the same component.
I just want a catch all for category/brand/subcategory slugs , and route them properly to explicit appointed pages.

But if needed ill make a reproduction of the error i'm getting in a new issue...

Cheers for the fast reply !

**Comment by danielroe** [comment] 2021-12-21 17:45
@GithubMitch `extend:pages` only works if you have a pages directory. You don't have to have any files in it.

**Comment by awacode21** [comment] 2022-01-08 17:54
> ```js
> import { resolve } from 'path'
> ```
Hi @danielroe ,

i would like to try this solution. But i need to request the routes from cms with async request. Does this nuxt hook to extend pages also work with async request? What would be the right syntax? Don't get it to run.

**Comment by awacode21** [comment] 2022-01-08 17:55
> This is how you can do it in Nuxt 3 at the moment (with the `extend:pages` hook):
> 
> ```js
> import { resolve } from 'path'
> import { defineNuxtConfig } from 'nuxt3'
> import { createCommonJS } from 'mlly'
> const { __dirname } = createCommonJS(import.meta.url)
> 
> export default defineNuxtConfig({
>   hooks: {
>     'pages:extend' (pages) {
>       pages.push({
>         name: 'cmsPage',
>         path: '*',
>         file: resolve(__dirname, 'cms/index.vue')
>       })
>     }
>   }
> })
> ```

Hi @danielroe ,

i would like to try this solution. But i need to request the routes from cms with async request. Does this nuxt hook to extend pages also work with async request? What would be the right syntax? Don't get it to run.

**Comment by awacode21** [comment] 2022-01-08 18:04
ok, got it to work with:

```
import { resolve } from 'path'
import { defineNuxtConfig } from 'nuxt3'
import { createCommonJS } from 'mlly'
const { __dirname } = createCommonJS(import.meta.url)

export default defineNuxtConfig({
  hooks: {
    async 'pages:extend' (pages) {
      pages.push({
        name: 'cmsPage',
        path: '*',
        file: resolve(__dirname, 'cms/index.vue')
      })
    }
  }
})
```

**Comment by dungonfq** [comment] 2022-01-13 04:04
> This is how you can do it in Nuxt 3 at the moment (with the `extend:pages` hook):
> 
> ```js
> import { resolve } from 'path'
> import { defineNuxtConfig } from 'nuxt3'
> import { createCommonJS } from 'mlly'
> const { __dirname } = createCommonJS(import.meta.url)
> 
> export default defineNuxtConfig({
>   hooks: {
>     'pages:extend' (pages) {
>       pages.push({
>         name: 'cmsPage',
>         path: '*',
>         file: resolve(__dirname, 'cms/index.vue')
>       })
>     }
>   }
> })
> ```

My approach: created a custom module to add localized URL to existing page dynamically. In my case, since @nuxt/i18n has supported Nuxt3 yet, I have to add locale prefixes to every URLs manually
(https://i18n.nuxtjs.org/routing/)

1. In `modules/localeRoutes.ts`
```
export default function LocaleRoutesModule () {
  this.nuxt.hook('pages:extend', (pages: Array<any>) => {
    const localeRoutes = pages.map(page => {
      return {
        name: `locale-${page.name}`,
        path: `/:locale${page.path}`,
        file: page.file,
        children: []
      }
    })

    pages.push(...localeRoutes)
  })
}
```

2. Register module in `nuxt.config.ts`
```
export default defineNuxtConfig({
  buildModules: [
    ...,
    '~/modules/localeRoutes'
  ],
})

```

**Comment by nikcio** [comment] 2022-02-05 10:38
> This is how you can do it in Nuxt 3 at the moment (with the `extend:pages` hook):
> 
> ```js
> import { resolve } from 'path'
> import { defineNuxtConfig } from 'nuxt3'
> import { createCommonJS } from 'mlly'
> const { __dirname } = createCommonJS(import.meta.url)
> 
> export default defineNuxtConfig({
>   hooks: {
>     'pages:extend' (pages) {
>       pages.push({
>         name: 'cmsPage',
>         path: '*',
>         file: resolve(__dirname, 'cms/index.vue')
>       })
>     }
>   }
> })
> ```

This works with a slight change on  version 3.0.0-27398533.8edd481.

The path now needs to be `/:catchall(.*)` making the snippet:

```js
export default defineNuxtConfig({
    hooks: {
        'pages:extend'(pages) {
            pages.push({
                name: 'cmsPage',
                path: '/:catchall(.*)',
                file: resolve(__dirname, 'cms/index.vue')
            })
        }
    }
})
```

**Comment by danielroe** [comment] 2022-02-16 13:25
You should move `const router = useRouter()` to the beginning of the middleware... At the moment, you can't access the nuxt instance in middleware after `await`.

**Comment by cydrickn** [comment] 2022-02-16 14:44
It works, thanks

**Comment by danielroe** [comment] 2022-04-01 12:31
For now, if you want to extend routes, then using a hook is the way to go. It prevents arbitrary expansion of the config and also means things can be easily extracted into your own custom modules if you need to.

I'm closing this issue and will follow up with a PR to migration docs.

cc: @pi0

**Closed by danielroe** 2022-04-01 12:31 UTC
Labels: enhancement, nuxt3

**Comment by toddpadwick** [comment] 2022-11-17 12:03
Hi all, still not quite clear how this works. I have tried to follow the example above, but it doesn't seem to work - no error - just doesn't catch the routes:
```
import { resolve } from 'path'; 
import { createCommonJS } from 'mlly';
const { __dirname } = createCommonJS(import.meta.url); 

export default defineNuxtConfig({
	hooks: {
        'pages:extend'(pages) {
            pages.push(
	            {
	                name: 'site.gender',
	                path: '/products/:gender',
	                file: resolve(__dirname, '/pages/products/index.vue'),
	            },
	            {
	                name: 'site.collection',
	                path: '/products/collections/:collection/:gender?',
	                file: resolve(__dirname, '/pages/products/index.vue'),
	            }
            );
        },
    },
});

```

**Comment by toddpadwick** [comment] 2022-11-17 12:18
Ah Ive figured it out (if anyone else is struggling). The `--dirname` was causing it to break and it seems its not needed. So the following worked:
```
import { resolve } from 'path'; 

export default defineNuxtConfig({
	hooks: {
        'pages:extend'(pages) {
            pages.push(
	            {
	                name: 'site.gender',
	                path: '/products/:gender',
	                file: resolve('/pages/products/index.vue'),
	            },
	            {
	                name: 'site.collection',
	                path: '/products/collections/:collection/:gender?',
	                file: resolve('/pages/products/index.vue'),
	            }
            );
        },
    },
});

```
