### ISSUE TITLE
Errors in terminal make it difficult to pinpoint issues

### ISSUE THREAD

**Issue by ffxsam** [nuxt/framework#5167] opened 2022-05-26 22:46 UTC
### Environment

Nuxt CLI v3.0.0-rc.3
RootDir: /Volumes/SuperData/Sites/reelcrafter/v2-microservices
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@3.0.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-svfqm4?file=app.vue

### Describe the bug

In dev mode, errors dumped to the terminal are not very useful, e.g.:

```
[nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'leftAlign')
    at _sfc_ssrRender (file:///Users/samh/shwa/.nuxt/dist/server/server.mjs:3383:129)
    at renderComponentSubTree (/Users/samh/shwa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)
    at renderComponentVNode (/Users/samh/shwa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (/Users/samh/shwa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at default (file:///Users/samh/shwa/.nuxt/dist/server/server.mjs:2645:37)
    at Module.ssrRenderSuspense (/Users/samh/shwa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:941:9)
    at _sfc_ssrRender (file:///Users/samh/shwa/.nuxt/dist/server/server.mjs:2640:25)
    at renderComponentSubTree (/Users/samh/shwa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)
    at renderComponentVNode (/Users/samh/shwa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at renderToString (/Users/samh/shwa/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:446:26)
```

May be related/solvable via #5086.

**Comment by misaon** [comment] 2022-05-31 16:48
+1

**Comment by mitch1009** [comment] 2022-06-12 08:23
This is pne of the issues that gives me headache all the times. Error log is unclear and you cannot trace the cause

**Comment by danielroe** [comment] 2022-09-20 12:54
This should now be resolved with the new vite-node default dev-bundler.

**Closed by danielroe** 2022-09-20 12:54 UTC
Labels: enhancement, dx
