### ISSUE TITLE
Leaflet: runs fine in dev, but fails in build mode

### ISSUE THREAD

**Issue by dakt** [nuxt/framework#5245] opened 2022-06-01 12:29 UTC
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.2.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `pnpm@7.1.7`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

I have UI library which also imports `leaflet` dep. I made sure that `leaflet` is loaded dynamically in `onMounted` hooks and that solved the problem when running in dev mode via vite server, but it fails to run in build mode when using `node` command with error log:  
```
[nuxt] [request error] window is not defined
  at ./.output/server/chunks/app/server.mjs:17185:21
```
That line is from `leaflet` library, but why does it error out only in production? I also made sure I upgraded node to 18.2.0 which supports ESM, but still fails.

### Logs

```shell
[nuxt] [request error] window is not defined
  at ./.output/server/chunks/app/server.mjs:17185:21
  at ./.output/server/chunks/app/server.mjs:17058:5
  at ./.output/server/chunks/app/server.mjs:17059:5
  at ./.output/server/chunks/app/server.mjs:24886:3
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
  at async ./.output/server/chunks/handlers/renderer.mjs:11136:24
  at async ./.output/server/chunks/handlers/renderer.mjs:11192:64
  at async ./.output/server/node_modules/h3/dist/index.mjs:417:19
```

**Comment by pperzyna** [comment] 2022-06-09 20:46
You cannot use `window` on server side `./.output/server/chunks/app/server.mjs:17185:21`

**Comment by dakt** [comment] 2022-06-13 09:04
> You cannot use `window` on server side `./.output/server/chunks/app/server.mjs:17185:21`

I know that. What I don't know is why that happens in production build and not on dev server.

**Comment by dakt** [comment] 2022-06-13 09:05
> Would you provide a reproduction? 🙏

OK. I Will try to provide it sometimes this week.

**Comment by YonathanKevin20** [comment] 2022-06-16 07:13
It looks like this.
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/32832237/174013430-bf41f05f-bf24-4e6f-9c67-d214eaf5d8d5.png">

**Comment by danielroe** [comment] 2022-06-17 09:13
That looks like you probably need to add `leaflet` to your `build.transpile` array (as it's trying to import a .png file, which won't work without being transpiled).

**Comment by YonathanKevin20** [comment] 2022-06-20 04:26
`build: { transpile: ['@headlessui/vue', 'leaflet'] },`
I already add leaflet to build.transpile in nuxt.config.ts, but still got same error.

**Comment by benoitdemaegdt** [comment] 2022-06-27 08:15
I have the same issue with Nuxt3 and Leaflet : `[nuxt] [request error] window is not defined`
Are you using [vue-leaflet](https://github.com/vue-leaflet/vue-leaflet) or pure js leaflet ?

**Comment by dakt** [comment] 2022-06-27 23:16
> I have the same issue with Nuxt3 and Leaflet : `[nuxt] [request error] window is not defined` Are you using [vue-leaflet](https://github.com/vue-leaflet/vue-leaflet) or pure js leaflet ?

pure leaflet

**Comment by default64bit** [comment] 2022-09-13 17:37
if you're using "vue-leaflet" package, try adding both "leaflet" and "@vue-leaflet/vue-leaflet" to your `build.transpile`

**Comment by danielroe** [comment] 2022-09-26 11:50
I'm closing as there's no reproduction. Feel free to provide it and I will reopen.

**Closed by danielroe** 2022-09-26 11:50 UTC
Labels: needs reproduction, pending triage
