### ISSUE TITLE
Cannot start application, Nuxt loading node modules from incorrect directory

### ISSUE THREAD

**Issue by marcodarko** [nuxt/framework#7573] opened 2022-09-15 21:06 UTC
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.9.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

npx nuxi init nuxt-app
npm i
npm run dev

### Describe the bug

Immediately hit with "Cannot find package '@vue/server-renderer' imported from /Users/marco/node_modules/vue/server-renderer/index.mjs" 

I've tried installing multiple times but no luck so far.

### Additional context

<img width="1181" alt="Screen Shot 2022-09-15 at 2 03 51 PM" src="https://user-images.githubusercontent.com/23092057/190508781-38247e91-b9be-4f12-ae84-8fa07280bb01.png">

### Logs

```shell
✔ Nitro built in 481 ms
ℹ Vite client warmed up in 1322ms
[nuxt] [request error] [unhandled] [500] Cannot find package '@vue/server-renderer' imported from /Users/marco/node_modules/vue/server-renderer/index.mjs
  at new NodeError (node:internal/errors:372:5)
  at packageResolve (node:internal/modules/esm/resolve:908:9)
  at moduleResolve (node:internal/modules/esm/resolve:957:20)
  at defaultResolve (node:internal/modules/esm/resolve:1173:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:604:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
  at link (node:internal/modules/esm/module_job:78:36)
^C
```

**Comment by danielroe** [comment] 2022-09-15 21:53
I cannot reproduce this with the same node/npm/OS versions. Did you `cd` into the directory or run `npm i` in your home directory?

**Comment by marcodarko** [comment] 2022-09-15 21:56
@danielroe yes I did, I can't get past the simple startup setup. same error every time. I see that node module exists too. 
init > cd dir > npm i > run dev > 500

**Comment by danielroe** [comment] 2022-09-15 22:01
The error message complains it can't import from `/Users/marco/node_modules`. Does that folder exist? Surely your project isn't `/Users/marco`? What is your project folder name?

**Comment by marcodarko** [comment] 2022-09-15 22:04
no that's my user folder, why would it be looking there? hmmm will need to take another look and update if anything changes. thank you

**Comment by marcodarko** [comment] 2022-09-15 22:10
@danielroe I don't know why it tries to load modules from my `User` directory and not the project directory : `/Users/marco/Desktop/code/discovery-app/nuxt-app`

The steps to reproduce are the same, same result every time.  Maybe it's my system but I have no idea why it's doing this.

**Comment by marcodarko** [comment] 2022-09-15 22:21
Tried to uninstall my global vue module and rerun to see if it was interfering but no luck so then I re-installed it and now get a new error (probably because it loaded the wrong version of vue from /User/marco not the project dir): 

[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read property 'modules' of undefined
  at _sfc_main.setup (./node_modules/nuxt/dist/app/components/nuxt-root.vue:67:16)  
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7109:29)  
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7064:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)  
  at renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:450:26)  
  at Object.renderToString$1 [as renderToString] (./.nuxt/dev/index.mjs:472:24)  
  at Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)  
  at processTicksAndRejections (node:internal/process/task_queues:94:5)  
  at async ./.nuxt/dev/index.mjs:527:21
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read property 'modules' of undefined
  at _sfc_main.setup (./node_modules/nuxt/dist/app/components/nuxt-root.vue:67:16)  
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7109:29)  
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7064:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)  
  at renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:450:26)  
  at Object.renderToString$1 [as renderToString] (./.nuxt/dev/index.mjs:472:24)  
  at Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)  
  at processTicksAndRejections (node:internal/process/task_queues:94:5)  
  at async ./.nuxt/dev/index.mjs:527:21
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read property 'modules' of undefined
  at _sfc_main.setup (./node_modules/nuxt/dist/app/components/nuxt-root.vue:67:16)  
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7109:29)  
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7064:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)  
  at renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:450:26)  
  at Object.renderToString$1 [as renderToString] (./.nuxt/dev/index.mjs:472:24)  
  at Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)  
  at processTicksAndRejections (node:internal/process/task_queues:94:5)  
  at async ./.nuxt/dev/index.mjs:527:21
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read property 'modules' of undefined
  at _sfc_main.setup (./node_modules/nuxt/dist/app/components/nuxt-root.vue:67:16)  
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7109:29)  
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7064:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)  
  at renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:450:26)  
  at Object.renderToString$1 [as renderToString] (./.nuxt/dev/index.mjs:472:24)  
  at Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)  
  at processTicksAndRejections (node:internal/process/task_queues:94:5)  
  at async ./.nuxt/dev/index.mjs:527:21
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>

**Comment by marcodarko** [comment] 2022-09-16 00:34
Any idea why Nuxt is loading node modules from `/User/marco/node_modules `and not `/Users/marco/Desktop/code/discovery-app/nuxt-app/node_modules`? 

I can't get anywhere with this, I've exhausted all resources online but can't find similar issues and I've tried creating an app in multiple locations and all the same result. 

<img width="1199" alt="Screen Shot 2022-09-15 at 3 19 08 PM" src="https://user-images.githubusercontent.com/23092057/190531870-98c115fa-ef76-40bc-91d5-abf4d93d9887.png">

**Comment by lewisking** [comment] 2022-09-16 03:10
Having exactly the same issue as @marcodarko

**Comment by andreas83** [comment] 2022-09-16 06:55
Same here. 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.11-27720979.b933015`
- Nitro Version:    `0.5.4-27719614.c3af02d`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `buildModules`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.2.8`
------------------------------



```
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')
  at _sfc_main.setup (./node_modules/nuxt/dist/app/components/nuxt-root.vue:67:16)  
  at callWithErrorHandling (./node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7109:29)  
  at setupComponent (./node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7064:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)  
  at renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:450:26)  
  at Object.renderToString$1 [as renderToString] (./.nuxt/dev/index.mjs:472:24)  
  at Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async ./.nuxt/dev/index.mjs:527:21
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>

```

**Comment by marcodarko** [comment] 2022-09-16 14:51
create-nuxt-app is also not working for me:

```
create-nuxt-app v3.6.0
✨  Generating Nuxt.js project in nuxt-app
? Project name: nuxt-app
? Programming language: JavaScript
? Package manager: Npm
? UI framework: None
? Nuxt.js modules: (Press <space> to select, <a> to toggle all, <i> to invert se
lection)
? Linting tools: ESLint, Prettier
? Testing framework: Jest
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Server (Node.js hosting)
? Development tools: (Press <space> to select, <a> to toggle all, <i> to invert 
selection)
? Continuous integration: None
? Version control system: Git
Trace: ReferenceError: ejs:1
 >> 1| <%_ if (isWindows === true) { _%>
    2| command_exists () {
    3|   command -v "$1" >/dev/null 2>&1
    4| }

isWindows is not defined
    at eval (eval at compile (/Users/marco/.npm/_npx/711906bd95ed3b8c/node_modules/ejs/lib/ejs.js:652:12), <anonymous>:10:8)
    at Object.anonymous [as fn] (/Users/marco/.npm/_npx/711906bd95ed3b8c/node_modules/ejs/lib/ejs.js:682:17)
    at Transformer.render (/Users/marco/.npm/_npx/711906bd95ed3b8c/node_modules/jstransformer/index.js:289:25)
    at /Users/marco/.npm/_npx/711906bd95ed3b8c/node_modules/sao/lib/runActions.js:69:27
    at Array.forEach (<anonymous>)
    at /Users/marco/.npm/_npx/711906bd95ed3b8c/node_modules/sao/lib/runActions.js:61:20
    at /Users/marco/.npm/_npx/711906bd95ed3b8c/node_modules/majo/dist/majo.cjs.js:58:49 {
  path: ''
}
    at /Users/marco/.npm/_npx/711906bd95ed3b8c/node_modules/create-nuxt-app/lib/cli.js:51:17
```

**Comment by angelhdzmultimedia** [comment] 2022-09-16 16:29
Same issue here. It was working good with 3.0.0-rc.9 (if I'm remembering correctly) and not anymore with 3.0.0-rc.10.
I even recorded YouTube videos and it was working.

Now a fresh project with `npx nuxi init` gives this error even after installing depds with `npm i,` and deleting `node_modules` and `.nuxt` folders and `package.lock.json`.

I was experiencing a very slow startup and I submitted an Issue, and when I created a project as requested by one of the contributors/maintainers, got this error and now I haven't be able to create a working project, now I have 2 issues.

Had to stop the recording of my new YouTube Tutorial that it was gonna be with Nuxt 3 + tRPC.

My error says: **500 Cannot read properties of undefined (reading 'modules')** in Chrome and in VSCode's terminal:

![image](https://user-images.githubusercontent.com/10191085/190686261-b69292cf-5cf3-4334-8334-9e2968ab56a1.png)

**Comment by marcodarko** [comment] 2022-09-16 18:39
@danielroe is there any other ways to get Nuxt working? seems like other people are running into the same issue

**Comment by pi0** [comment] 2022-09-16 18:42
Would you please share a github repository to reproduce this issue? 🙏🏼

**Comment by marcodarko** [comment] 2022-09-16 18:47
@pi0 No repo to share, it's just the basic install, we can't get it to work.  https://github.com/nuxt/framework/issues/7573#issuecomment-1248674365

**Comment by pi0** [comment] 2022-09-16 18:52
It might be a regression from workspaceDir from rc.10. do you have a lockfile or package.json in your home directory?

**Comment by marcodarko** [comment] 2022-09-16 19:05
I do but I have tried creating a new project in multiple locations and all the same result. I've tried deleting them and reinstalling but same thing happens. These are the logs: https://github.com/nuxt/framework/issues/7573#issuecomment-1248694497

**Comment by pi0** [comment] 2022-09-16 19:17
I have some theories about the issue but rc.10 works fine on my machine so still need reproduction. It might be specific to your machine.

Can you please share output of this config:

```ts
export default defineNuxtConfig({
  hooks: {
    'ready'(nuxt) {
      console.log('Workspace dir:', nuxt.options.workspaceDir)
      console.log('Modules dir:', nuxt.options.modulesDir)
    }
  }
})
```

If there is `/Users/marco/node_modules` in there and specially you have `/Users/marco/node_modules/vue` (v2) it can cause the issue. You shouldn't have `node_modules` inside the home directory. If possible try to remove it.

**Comment by marcodarko** [comment] 2022-09-16 19:20
here's the result: 
```
Workspace dir: /Users/marco/Desktop/code/discovery-app
Modules dir: [
  '/Users/marco/Desktop/code/discovery-app/nuxt-app/node_modules',
  '/Users/marco/Desktop/code/discovery-app/nuxt-app/node_modules',
  '/Users/marco/Desktop/code/discovery-app/node_modules',
  '/Users/marco/Desktop/code/discovery-app/nuxt-app/node_modules/nuxt/node_modules'
]
```
where discovery-app is the main project and I'm trying to create 'nuxt-app' under that project directory.

**Comment by angelhdzmultimedia** [comment] 2022-09-16 19:22
> I have some theories about the issue but rc.10 works fine on my machine so still need reproduction. It might be specific to your machine.
> 
> Can you please share output of this config:
> 
> ```ts
> export default defineNuxtConfig({
>   hooks: {
>     'ready'(nuxt) {
>       console.log('Workspace dir:', nuxt.options.workspaceDir)
>       console.log('Modules dir:', nuxt.options.modulesDir)
>     }
>   }
> })
> ```
> 
> If there is `/Users/marco/node_modules` in there and specially you have `/Users/marco/node_modules/vue` (v2) it can cause the issue. You shouldn't have `node_modules` inside the home directory. If possible try to remove it.

"It works on my machine"

**Comment by angelhdzmultimedia** [comment] 2022-09-16 19:26
> I do but I have tried creating a new project in multiple locations and all the same result. I've tried deleting them and reinstalling but same thing happens. These are the logs: [#7573 (comment)](https://github.com/nuxt/framework/issues/7573#issuecomment-1248694497)

Yup, i've tried many things, from creating new fresh projects in other folders, to deleting package.lock.json .nuxt and node_modules, to restarting Typescript server, to restarting VSCode an even Windows.

I was exited because 3.0.0-rc.10 was announced and started spreading it, and bam, wild issues appeared.

It was working nicely on 3.0.0-rc.9 (besides it being very slow to server the app, as in previous versions, compared to a pure Vue 3 + Vite project) and it doesn't work anymore.

I have like 3 YouTube tutorials on hold that I haven't be able to record due to this.

**Comment by pi0** [comment] 2022-09-16 19:28
Dear @andreas83 keep repeating that you have an issue that doesn't help to resolve it! I'm sorry that you are encountering a bug. We are trying to help investigate and fix any possible regression but first need to reproduce it stably to pinpoint the issue.

**Comment by pi0** [comment] 2022-09-16 19:29
@marcodarko @andreas83 Any hope we can set a session so you can share your desktop? (Still trying to reproduce locally but might help to speed up)

**Comment by marcodarko** [comment] 2022-09-16 19:30
Happy to meet anytime

**Comment by angelhdzmultimedia** [comment] 2022-09-16 19:31
Marked as SPAM LOOOOOOOOOOOOOOOOL. 
So you can reply with comments implying that because it works in your side, then we are doing something wrong or the issue is in our machines!? What an attitude dude!

![image](https://user-images.githubusercontent.com/10191085/190716265-4682aa7b-4477-4689-b765-f9f456c7610e.png)

**Comment by pi0** [comment] 2022-09-16 19:34
@andreas83 Making reproductions is a standard process in all open source projects to track bugs. This issue is not caught by our CI nor (currently) locally by maintainers to resolve. Please stop spamming the thread if not gonna help.

**Comment by pi0** [comment] 2022-09-16 20:03
As an update, we had a quick call with @marcodarko. Removing or renaming stale `node_modules`  from home directory solves the issue. It _is_ an environment-specific issue. Trying to find a solution for it but as quick workaround, simply remove the directory.

**Comment by manniL** [comment] 2022-09-16 20:26
Could that issue be related to https://github.com/nuxt/framework/issues/7220 too?

**Comment by pi0** [comment] 2022-09-16 20:49
Thanks once again @marcodarko for reproduction. Moving this issue to https://github.com/nuxt/framework/issues/7609. It is related to the vite-node package that is enabled.

**Closed by pi0** 2022-09-16 20:49 UTC
Labels: bug, vite
